//************************************************************************************
//**  
//**  File name:     C:\Users\gerpe\OneDrive\GER-PER 2016\Documents\KennyNeutron\2020\RF\RF_flowcode\873_RF_TX.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Wednesday, July 29, 2020 10:43:31
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F873A
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_1
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 128
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 20000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f3a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f3a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_own_spi();
void FCM_rf_begin();
void FCM_set_writing_pipe0();
void FCM_rf_setpa();
void FCM_open_writing_pipe_address();
void FCM_radio_writepayload();
void FCM_tx_flush();
void FCM_activate();


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_BOOL FCV_SPB4 = (1);
MX_BOOL FCV_SPB5 = (1);
MX_BOOL FCV_OSPI_OUT_BIT = (1);
MX_UINT8 FCV_SPI_IHAP = (0x0);
MX_BOOL FCV_SPB6 = (1);
MX_BOOL FCV_SPB7 = (1);
MX_UINT8 FCV_RF_CONFIG;
MX_UINT8 FCV_OSPI_DATAIN = (0xff);
MX_BOOL FCV_OSPI_IN_BIT = (1);
MX_UINT8 FCV_OSPI_DATAOUT = (0xff);
MX_BOOL FCV_SPB0 = (1);
MX_BOOL FCV_SPB1;
MX_BOOL FCV_SPB2 = (1);
MX_BOOL FCV_SPB3 = (1);

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;



//LCDDisplay(0): //Defines:

/**** Macro Substitutions ****
a = Unique Component Reference Number
b = D1 Port Letter
c = D2 Port Letter
d = D3 Port Letter
e = D4 Port Letter
f = RS Port Letter
g = E Port Letter
h = Data 1_Pin
i = Data 2 Pin
j = Data 3 Pin
k = Data 4 Pin
l = RS Pin
m = Enable Pin
n = Row Count
o = Column Count
******************************/

	//component connections
	#define LCD_1__PORT0    portb
	#define LCD_1__PORT1    portb
	#define LCD_1__PORT2    portb
	#define LCD_1__PORT3    portb
	#define LCD_1__PORT4    portb
	#define LCD_1__PORT5    portb
	#define LCD_1__TRIS0    trisb
	#define LCD_1__TRIS1    trisb
	#define LCD_1__TRIS2    trisb
	#define LCD_1__TRIS3    trisb
	#define LCD_1__TRIS4    trisb
	#define LCD_1__TRIS5    trisb
	#define LCD_1__BIT0    	2
	#define LCD_1__BIT1    	3
	#define LCD_1__BIT2    	4
	#define LCD_1__BIT3    	5
	#define LCD_1__RS      	0
	#define LCD_1__E       	1
	#define LCD_1__ROWCNT	4
	#define LCD_1__COLCNT	16

	#ifdef _BOOSTC
	  #define LCD_1__DELAY   delay_10us(10)
	#endif
	#ifdef _C2C_
	  #define LCD_1__DELAY   delay_us(100)
	#endif
	#ifdef HI_TECH_C
	  #define LCD_1__DELAY   __delay_us(120)
	#endif
	#ifndef LCD_1__DELAY
	  #define LCD_1__DELAY   delay_us(100)
	#endif




//LCDDisplay(0): //Macro function declarations

void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask);
void FCD_LCDDisplay0_Start();
void FCD_LCDDisplay0_Clear();
void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character);
void FCD_LCDDisplay0_Command(MX_UINT8 in);
void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y);
void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number);
void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String);
void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions);
void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line);
void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7);



//LCDDisplay(0): //Macro implementations


void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask)
{
	
		MX_UINT8 pt;

		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		pt = ((in >> 4) & 0x0f);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		pt = (in & 0x0f);
		LCD_1__DELAY;
		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;

}

void FCD_LCDDisplay0_Start()
{
	
		FC_CAL_Bit_Low_DDR(LCD_1__PORT0, LCD_1__TRIS0, LCD_1__BIT0);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT1, LCD_1__TRIS1, LCD_1__BIT1);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT2, LCD_1__TRIS2, LCD_1__BIT2);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT3, LCD_1__TRIS3, LCD_1__BIT3);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT4, LCD_1__TRIS4, LCD_1__RS);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT5, LCD_1__TRIS5, LCD_1__E);

		Wdt_Delay_Ms(12);

		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x32, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x2c, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x06, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x0c, 0);
		Wdt_Delay_Ms(2);

		//clear the display
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Clear()
{
	
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character)
{
	
		FCD_LCDDisplay0_RawSend(Character, 0x10);

}

void FCD_LCDDisplay0_Command(MX_UINT8 in)
{
	
		FCD_LCDDisplay0_RawSend(in, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y)
{
	
	  #if (LCD_1__ROWCNT == 1)
	    y=0x80;
	  #endif

	  #if (LCD_1__ROWCNT == 2)
		if (y==0)
			y=0x80;
		else
			y=0xc0;
	  #endif

	  #if (LCD_1__ROWCNT == 4)
		if (y==0)
			y=0x80;
		else if (y==1)
			y=0xc0;

		#if (LCD_1__COLCNT == 16)
			else if (y==2)
				y=0x90;
			else
				y=0xd0;
		#endif

		#if (LCD_1__COLCNT == 20)
			else if (y==2)
				y=0x94;
			else
				y=0xd4;
		#endif
	  #endif

		FCD_LCDDisplay0_RawSend(y+x, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number)
{
	
		MX_SINT16 tmp_int;
		MX_UINT8 tmp_byte;

		if (Number < 0)
		{
			FCD_LCDDisplay0_RawSend('-', 0x10);
			Number = 0 - Number;
		}

		tmp_int = Number;
		if (Number >= 10000)
		{
			tmp_byte = tmp_int / 10000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10000;
				tmp_byte--;
			}
		}
		if (Number >= 1000)
		{
			tmp_byte = tmp_int / 1000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 1000;
				tmp_byte--;
			}
		}
		if (Number >= 100)
		{
			tmp_byte = tmp_int / 100;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 100;
				tmp_byte--;
			}
		}
		if (Number >= 10)
		{
			tmp_byte = tmp_int / 10;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10;
				tmp_byte--;
			}
		}
		FCD_LCDDisplay0_RawSend('0' + tmp_int, 0x10);

}

void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx = 0;

		for (idx=0; idx<MSZ_String; idx++)
		{
			if (String[idx] == 0)
			{
				break;
			}
			FCD_LCDDisplay0_RawSend(String[idx], 0x10);
		}

}

void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions)
{
	
		MX_UINT8 cmd = 0;
		MX_UINT8 count;

		//Choose the direction
		switch (Direction)
		{
			case 0:
			case 'l':
			case 'L':

				cmd = 0x18;
				break;

			case 1:
			case 'r':
			case 'R':

				cmd = 0x1C;
				break;

			default:
				break;
		}

		//If direction accepted then scroll the specified amount
		if (cmd)
		{
			for (count = 0; count < Num_Positions; count++)
				FCD_LCDDisplay0_Command(cmd);
		}

}

void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line)
{
	
		MX_UINT8 count;
		MX_UINT8 rowcount;

		//Define number of columns per line
		#if (LCD_1__ROWCNT == 1)
			rowcount=80;
		#endif

		#if (LCD_1__ROWCNT == 2)
			rowcount=40;
		#endif

		#if (LCD_1__ROWCNT == 4)
			#if (LCD_1__COLCNT == 16)
				rowcount=16;
			#endif
			#if (LCD_1__COLCNT == 20)
				rowcount=20;
			#endif
		#endif

		//Start at beginning of the line
		FCD_LCDDisplay0_Cursor (0, Line);

		//Send out spaces to clear line
		for (count = 0; count < rowcount; count++)
			FCD_LCDDisplay0_RawSend(' ', 0x10);

		//Move back to the beginning of the line.
		FCD_LCDDisplay0_Cursor (0, Line);

}

void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7)
{
	   //set CGRAM address

	   FCD_LCDDisplay0_RawSend(64 + (nIdx << 3), 0);
	   delay_ms(2);

	   //write CGRAM data
	   FCD_LCDDisplay0_RawSend(d0, 0x10);
	   FCD_LCDDisplay0_RawSend(d1, 0x10);
	   FCD_LCDDisplay0_RawSend(d2, 0x10);
	   FCD_LCDDisplay0_RawSend(d3, 0x10);
	   FCD_LCDDisplay0_RawSend(d4, 0x10);
	   FCD_LCDDisplay0_RawSend(d5, 0x10);
	   FCD_LCDDisplay0_RawSend(d6, 0x10);
	   FCD_LCDDisplay0_RawSend(d7, 0x10);

	   //Clear the display
	   FCD_LCDDisplay0_RawSend(0x01, 0);
	   delay_ms(2);
	   FCD_LCDDisplay0_RawSend(0x02, 0);
	   delay_ms(2);

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_own_spi()
{

	//csn
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Output
	//Output: 1 -> C5
	trisc = trisc & 0xDF;
	if ((1))
		portc = (portc & 0xDF) | 0x20;
	else
		portc = portc & 0xDF;

	//clk
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//Calculation
	//Calculation:
	//  spi_ihap = 0
	FCV_SPI_IHAP = 0;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP2=0; FCLV_LOOP2<8; FCLV_LOOP2++)
	{

		//Switch
		//Switch: spi_ihap?
		switch (FCV_SPI_IHAP)
		{
			case 1:
			{
				//Calculation
				//Calculation:
				//  spb1 = ospi_dataout AND 1
				FCV_SPB1 = FCV_OSPI_DATAOUT & 1;

				break;
			}
			case 2:
			{
				//Calculation
				//Calculation:
				//  spb2 = ospi_dataout AND 1
				FCV_SPB2 = FCV_OSPI_DATAOUT & 1;

				break;
			}
			case 3:
			{
				//Calculation
				//Calculation:
				//  spb3 = ospi_dataout AND 1
				FCV_SPB3 = FCV_OSPI_DATAOUT & 1;

				break;
			}
			case 4:
			{
				//Calculation
				//Calculation:
				//  spb4 = ospi_dataout AND 1
				FCV_SPB4 = FCV_OSPI_DATAOUT & 1;

				break;
			}
			case 5:
			{
				//Calculation
				//Calculation:
				//  spb5 = ospi_dataout AND 1
				FCV_SPB5 = FCV_OSPI_DATAOUT & 1;

				break;
			}
			case 6:
			{
				//Calculation
				//Calculation:
				//  spb6 = ospi_dataout AND 1
				FCV_SPB6 = FCV_OSPI_DATAOUT & 1;

				break;
			}
			case 7:
			{
				//Calculation
				//Calculation:
				//  spb7 = ospi_dataout AND 1
				FCV_SPB7 = FCV_OSPI_DATAOUT & 1;

				break;
			}
			case 0:
			{
				//Calculation
				//Calculation:
				//  spb0 = ospi_dataout AND 1
				FCV_SPB0 = FCV_OSPI_DATAOUT & 1;

				break;
			}
			// default:

		}

		//Calculation
		//Calculation:
		//  ospi_dataout = ospi_dataout >> 1
		//  spi_ihap = spi_ihap + 1
		FCV_OSPI_DATAOUT = FCV_OSPI_DATAOUT >> 1;
		FCV_SPI_IHAP = FCV_SPI_IHAP + 1;


	}

	//Calculation
	//Calculation:
	//  spi_ihap = 0
	FCV_SPI_IHAP = 0;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP3=0; FCLV_LOOP3<8; FCLV_LOOP3++)
	{

		//Switch
		//Switch: spi_ihap?
		switch (FCV_SPI_IHAP)
		{
			case 1:
			{
				//Output
				//Output: spb6 -> C5
				trisc = trisc & 0xDF;
				if ((FCV_SPB6))
					portc = (portc & 0xDF) | 0x20;
				else
					portc = portc & 0xDF;

				break;
			}
			case 2:
			{
				//Output
				//Output: spb5 -> C5
				trisc = trisc & 0xDF;
				if ((FCV_SPB5))
					portc = (portc & 0xDF) | 0x20;
				else
					portc = portc & 0xDF;

				break;
			}
			case 3:
			{
				//Output
				//Output: spb4 -> C5
				trisc = trisc & 0xDF;
				if ((FCV_SPB4))
					portc = (portc & 0xDF) | 0x20;
				else
					portc = portc & 0xDF;

				break;
			}
			case 4:
			{
				//Output
				//Output: spb3 -> C5
				trisc = trisc & 0xDF;
				if ((FCV_SPB3))
					portc = (portc & 0xDF) | 0x20;
				else
					portc = portc & 0xDF;

				break;
			}
			case 5:
			{
				//Output
				//Output: spb2 -> C5
				trisc = trisc & 0xDF;
				if ((FCV_SPB2))
					portc = (portc & 0xDF) | 0x20;
				else
					portc = portc & 0xDF;

				break;
			}
			case 6:
			{
				//Output
				//Output: spb1 -> C5
				trisc = trisc & 0xDF;
				if ((FCV_SPB1))
					portc = (portc & 0xDF) | 0x20;
				else
					portc = portc & 0xDF;

				break;
			}
			case 7:
			{
				//Output
				//Output: spb0 -> C5
				trisc = trisc & 0xDF;
				if ((FCV_SPB0))
					portc = (portc & 0xDF) | 0x20;
				else
					portc = portc & 0xDF;

				break;
			}
			case 0:
			{
				//Output
				//Output: spb7 -> C5
				trisc = trisc & 0xDF;
				if ((FCV_SPB7))
					portc = (portc & 0xDF) | 0x20;
				else
					portc = portc & 0xDF;

				break;
			}
			// default:

		}

		//clk
		//Output: 1 -> C3
		trisc = trisc & 0xF7;
		if ((1))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//Delay
		//Delay: 5 us
		delay_us(5);

		//clk
		//Output: 0 -> C3
		trisc = trisc & 0xF7;
		if ((0))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//Delay
		//Delay: 5 us
		delay_us(5);

		//Calculation
		//Calculation:
		//  spi_ihap = spi_ihap + 1
		FCV_SPI_IHAP = FCV_SPI_IHAP + 1;


	}

	//Output
	//Output: 1 -> C5
	trisc = trisc & 0xDF;
	if ((1))
		portc = (portc & 0xDF) | 0x20;
	else
		portc = portc & 0xDF;

	//Output
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//csn
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

}


void FCM_rf_begin()
{

	//write on rf_config
	//Calculation:
	//  ospi_dataout = 0b00100000
	FCV_OSPI_DATAOUT = 32;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//Calculation
	//Calculation:
	//  rf_config = 0b00001010
	FCV_RF_CONFIG = 10;

	//Calculation
	//Calculation:
	//  ospi_dataout = rf_config
	FCV_OSPI_DATAOUT = FCV_RF_CONFIG;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

}


void FCM_set_writing_pipe0()
{

	//RF_reg01
	//Calculation:
	//  ospi_dataout = 0b00100001
	FCV_OSPI_DATAOUT = 33;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0b00111110
	FCV_OSPI_DATAOUT = 62;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//RF_reg02
	//Calculation:
	//  ospi_dataout = 0b00100010
	FCV_OSPI_DATAOUT = 34;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0b00000010
	FCV_OSPI_DATAOUT = 2;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

}


void FCM_rf_setpa()
{

	//RF_reg06
	//Calculation:
	//  ospi_dataout = 0b00100110
	FCV_OSPI_DATAOUT = 38;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0b00001101
	FCV_OSPI_DATAOUT = 13;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

}


void FCM_open_writing_pipe_address()
{

	//RF_reg10
	//Calculation:
	//  ospi_dataout = 0b00110000
	FCV_OSPI_DATAOUT = 48;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0xE7
	FCV_OSPI_DATAOUT = 0xE7;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0xE7
	FCV_OSPI_DATAOUT = 0xE7;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0xE7
	FCV_OSPI_DATAOUT = 0xE7;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0xE7
	FCV_OSPI_DATAOUT = 0xE7;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0xE7
	FCV_OSPI_DATAOUT = 0xE7;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

}


void FCM_radio_writepayload()
{

	//RF_command
	//Calculation:
	//  ospi_dataout = 0b10100000
	FCV_OSPI_DATAOUT = 160;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//data
	//Calculation:
	//  ospi_dataout = 0x55
	FCV_OSPI_DATAOUT = 0x55;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

}


void FCM_tx_flush()
{

	//RF_command
	//Calculation:
	//  ospi_dataout = 0b11100001
	FCV_OSPI_DATAOUT = 225;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

}


void FCM_activate()
{

	//RF_reg10
	//Calculation:
	//  ospi_dataout = 0b01010000
	FCV_OSPI_DATAOUT = 80;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

	//RF_reg10
	//Calculation:
	//  ospi_dataout = 0x73
	FCV_OSPI_DATAOUT = 0x73;

	//Call Macro
	//Call Macro: own_spi()
	FCM_own_spi();

}



void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Call Component Macro
	//Call Component Macro: Start()
	FCD_LCDDisplay0_Start();

	//Call Component Macro
	//Call Component Macro: Clear()
	FCD_LCDDisplay0_Clear();

	//clk
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//csn
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//ce
	//Output: 1 -> C1
	trisc = trisc & 0xFD;
	if ((1))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

	//setup
	//Loop: Loop 1 times
	for (FCLV_LOOP1=0; FCLV_LOOP1<1; FCLV_LOOP1++)
	{

		//Call Macro
		//Call Macro: rf_begin()
		FCM_rf_begin();

		//Call Macro
		//Call Macro: set_writing_pipe0()
		FCM_set_writing_pipe0();

		//Call Macro
		//Call Macro: open_writing_pipe_address()
		FCM_open_writing_pipe_address();

		//Call Macro
		//Call Macro: rf_setpa()
		FCM_rf_setpa();

		//Call Macro
		//Call Macro: activate()
		FCM_activate();


	}

	//Delay
	//Delay: 1 ms
	delay_ms(1);

	//Loop
	//Loop: While 1
	while (1)
	{

		//Call Macro
		//Call Macro: radio_writepayload()
		FCM_radio_writepayload();

		//Call Macro
		//Call Macro: tx_flush()
		FCM_tx_flush();

		//Delay
		//Delay: 1 ms
		delay_ms(1);


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



