# MPLAB IDE generated this makefile for use with GNU make.
# Project: 2x4 P10 SB.mcp
# Date: Mon Apr 20 11:49:40 2020

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

2X4_P10_SB.cof : 2X4_P10_SB.o
	$(CC) /p18F4620 "2X4_P10_SB.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"2X4_P10_SB.cof" /M"2X4_P10_SB.map" /W /x

2X4_P10_SB.o : 2X4_P10_SB.ASM ../../../../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P18F4620.INC P10_FONT2.INC CLRRAMS&DELAY.INC
	$(AS) /q /p18F4620 "2X4_P10_SB.ASM" /l"2X4_P10_SB.lst" /e"2X4_P10_SB.err" /d__DEBUG=1

clean : 
	$(CC) "2X4_P10_SB.o" "2X4_P10_SB.hex" "2X4_P10_SB.err" "2X4_P10_SB.lst" "2X4_P10_SB.cof"

