//************************************************************************************
//**  
//**  File name:     C:\Users\gerpe\OneDrive\GER-PER 2016\Documents\KennyNeutron\2020\RF\NRF_test2\NRF_Lib.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Friday, August 07, 2020 20:49:14
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 2
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F873A
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_1
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 128
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 20000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f32
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f32);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_spi_nrf_reg_read();
void FCM_cmd_read_reg();
void FCM_lcd_line0();
void FCM_lcd_line1();
void FCM_lcd_line2();
void FCM_cmd_read_rx_addr();
void FCM_cmd_read_tx_addr();
void FCM_lcd_line3();
void FCM_nrf_tx_init();
void FCM_cmd_write_reg();
void FCM_set_tx_addr();
void FCM_set_rx_addr();
void FCM_radio_send_data();
void FCM_flush_fifo_txrx();
void FCM_nrf_rx_init();
void FCM_show_status();
void FCM_radio_recieve_data();
void FCM_tx_addr_to_string();
void FCM_rx_addr_to_string();
void FCM_disp_datarx();
void FCM_check_status();
void FCM_print_display();
void FCM_read_recieved_data();
void FCM_disp_datatx();


//Variable declarations
#define FCSZ_PAYLOAD_RECIEVE 16
#define FCSZ_PAYLOAD_TRANSMIT 16
#define FCSZ_RX_ADDR 16
#define FCSZ_TX_ADDR 16
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_UINT8 FCV_DATA_TO_WRITE = (0xff);
MX_UINT8 FCV_REG10_TX_ADDR_BYTE1 = (0x0);
MX_UINT8 FCV_REG00_CONFIG = (0x0);
MX_UINT8 FCV_REG12_RX_PW_P1 = (0x0);
MX_UINT8 FCV_REG10_TX_ADDR_BYTE2 = (0x0);
MX_UINT8 FCV_REG09_CD = (0x0);
MX_UINT8 FCV_REG15_RX_PW_P4 = (0x0);
MX_UINT8 FCV_REG10_TX_ADDR_BYTE3 = (0x0);
MX_CHAR FCV_PAYLOAD_RECIEVE[FCSZ_PAYLOAD_RECIEVE];
MX_UINT8 FCV_REG10_TX_ADDR_BYTE4 = (0x0);
MX_UINT8 FCV_REG0C_RX_ADDR_P2 = (0x0);
MX_UINT8 FCV_REG0F_RX_ADDR_P5 = (0x0);
MX_UINT8 FCV_STATUS_MAX_RT = (0x0);
MX_UINT8 FCV_REG17_FIFO_STATUS = (0x0);
MX_UINT8 FCV_SPI_DATA0 = (0xff);
MX_UINT8 FCV_SPI_DATA1 = (0xff);
MX_UINT8 FCV_DATA_TO_READ = (0x0);
MX_UINT8 FCV_REG1D_FEATURE = (0x0);
MX_UINT8 FCV_REG13_RX_PW_P2 = (0x0);
MX_CHAR FCV_PAYLOAD_TRANSMIT[FCSZ_PAYLOAD_TRANSMIT];
MX_UINT8 FCV_REG0A_RX_ADDR_P0_BYTE0 = (0x0);
MX_UINT8 FCV_REG16_RX_PW_P5 = (0x0);
MX_UINT8 FCV_STATUS_RX_DR;
MX_UINT8 FCV_REG1C_DYNPD = (0x0);
MX_UINT8 FCV_REG0A_RX_ADDR_P0_BYTE1 = (0x0);
MX_UINT8 FCV_REG05_RF_CH = (0x0);
MX_UINT8 FCV_REG07_STATUS = (0x0);
MX_UINT8 FCV_REG0A_RX_ADDR_P0_BYTE2 = (0x0);
MX_UINT8 FCV_REG02_EN_RXADDR = (0x0);
MX_UINT8 FCV_REG0D_RX_ADDR_P3 = (0x0);
MX_UINT8 FCV_STATUS_TX_DS = (0x0);
MX_BOOL FCV_SW0 = (1);
MX_UINT8 FCV_REG0A_RX_ADDR_P0_BYTE3 = (0x0);
MX_UINT8 FCV_REG01_ENAA = (0x0);
MX_UINT8 FCV_REG08_OBSERVE = (0x0);
MX_UINT8 FCV_REG_TO_WRITE = (0x0);
MX_UINT8 FCV_REG0A_RX_ADDR_P0_BYTE4 = (0x0);
MX_UINT8 FCV_REG03_SETUP_AW = (0x0);
MX_UINT8 FCV_REG11_RX_PW_P0 = (0x0);
MX_UINT8 FCV_REG14_RX_PW_P3 = (0x0);
MX_UINT8 FCV_CURSORX = (0x0);
MX_UINT8 FCV_PAYLOADSIZE = (0x20);
MX_UINT8 FCV_DIP_SWITCH = (0x0);
MX_CHAR FCV_RX_ADDR[FCSZ_RX_ADDR] = ("KENNY");
MX_UINT8 FCV_LOOP_COUNT = (0x0);
MX_UINT8 FCV_REG0B_RX_ADDR_P1 = (0x0);
MX_UINT8 FCV_REG0E_RX_ADDR_P4 = (0x0);
MX_CHAR FCV_TX_ADDR[FCSZ_TX_ADDR] = ("");
MX_UINT8 FCV_REG06_RF_SETUP = (0x0);
MX_UINT8 FCV_T_OUT = (0xa);
MX_UINT8 FCV_REG10_TX_ADDR_BYTE0 = (0x0);
MX_UINT8 FCV_REG04_SETUP_RETR = (0x0);




//LCDDisplay(0): //Defines:

/**** Macro Substitutions ****
a = Unique Component Reference Number
b = D1 Port Letter
c = D2 Port Letter
d = D3 Port Letter
e = D4 Port Letter
f = RS Port Letter
g = E Port Letter
h = Data 1_Pin
i = Data 2 Pin
j = Data 3 Pin
k = Data 4 Pin
l = RS Pin
m = Enable Pin
n = Row Count
o = Column Count
******************************/

	//component connections
	#define LCD_1__PORT0    portb
	#define LCD_1__PORT1    portb
	#define LCD_1__PORT2    portb
	#define LCD_1__PORT3    portb
	#define LCD_1__PORT4    portb
	#define LCD_1__PORT5    portb
	#define LCD_1__TRIS0    trisb
	#define LCD_1__TRIS1    trisb
	#define LCD_1__TRIS2    trisb
	#define LCD_1__TRIS3    trisb
	#define LCD_1__TRIS4    trisb
	#define LCD_1__TRIS5    trisb
	#define LCD_1__BIT0    	2
	#define LCD_1__BIT1    	3
	#define LCD_1__BIT2    	4
	#define LCD_1__BIT3    	5
	#define LCD_1__RS      	0
	#define LCD_1__E       	1
	#define LCD_1__ROWCNT	4
	#define LCD_1__COLCNT	16

	#ifdef _BOOSTC
	  #define LCD_1__DELAY   delay_10us(10)
	#endif
	#ifdef _C2C_
	  #define LCD_1__DELAY   delay_us(100)
	#endif
	#ifdef HI_TECH_C
	  #define LCD_1__DELAY   __delay_us(120)
	#endif
	#ifndef LCD_1__DELAY
	  #define LCD_1__DELAY   delay_us(100)
	#endif




//LCDDisplay(0): //Macro function declarations

void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask);
void FCD_LCDDisplay0_Start();
void FCD_LCDDisplay0_Clear();
void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character);
void FCD_LCDDisplay0_Command(MX_UINT8 in);
void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y);
void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number);
void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String);
void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions);
void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line);
void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7);


//SPI_Legacy(0): //Defines:

/**** Macro Substitutions ****
a = Unique Ref
b = SPI Channel
c = MOSI Pin
d = MOSI Port
e = MISO Pin
f = MISO Port
g = SCK Pin
h = SCK Port
i = Clock Polarity + Clock Phase + Data Sample Phase
j = SPI Prescaler
k = SPI Postscaler
l = DAC Enable Pin
m = DAC Enable Port
n = FRAM Enable Pin
o = FRAM Enable Port
******************************/

//MX_SPI_BMODE - Bus Mode - Bit0=CPOL, Bit1=CPHA, Bit2=CSMP
//CPOL - Clock Polarity - Idle State of the clock 0=0, 1=1
//CPHA - Clock Phase - Clock Edge 0=leading edge, 1=trailing edge
//CSMP - Input Data Bit Sample Phase


//Definitions for CS control lines
#define SPI_2_MX_SPI_LEGACY_DAC_PIN		0
#define SPI_2_MX_SPI_LEGACY_DAC_PORT		porta
#define SPI_2_MX_SPI_LEGACY_DAC_TRIS		trisa
#define SPI_2_MX_SPI_LEGACY_FRAM_PIN		0
#define SPI_2_MX_SPI_LEGACY_FRAM_PORT		porta
#define SPI_2_MX_SPI_LEGACY_FRAM_TRIS		trisa


//Definitions for SPI slot allocation
#ifndef	MX_SPI_REF1
	#define MX_SPI_REF1
	#define SPI_2_MX_SPI_UREF			1
	#define MX_SPI_CHANNEL_1		1
	#define MX_SPI_MOSI_PIN_1		-1
	#define MX_SPI_MOSI_PORT_1		port0
	#define MX_SPI_MOSI_TRIS_1		tris0
	#define MX_SPI_MISO_PIN_1		-1
	#define MX_SPI_MISO_PORT_1		port0
	#define MX_SPI_MISO_TRIS_1		tris0
	#define MX_SPI_SCK_PIN_1		-1
	#define MX_SPI_SCK_PORT_1		port0
	#define MX_SPI_SCK_TRIS_1		tris0
	#define MX_SPI_CS_PIN_1			0
	#define MX_SPI_CS_PORT_1		0
	#define MX_SPI_BMODE_1			6
	#define MX_SPI_PR_SCALE_1		64
	#define MX_SPI_PO_SCALE_1		0
	#define MX_SPI_INT_1			0
#else
 #ifndef	MX_SPI_REF2
	#define MX_SPI_REF2
	#define SPI_2_MX_SPI_UREF			2
	#define MX_SPI_CHANNEL_2		1
	#define MX_SPI_MOSI_PIN_2		-1
	#define MX_SPI_MOSI_PORT_2		port0
	#define MX_SPI_MOSI_TRIS_2		tris0
	#define MX_SPI_MISO_PIN_2		-1
	#define MX_SPI_MISO_PORT_2		port0
	#define MX_SPI_MISO_TRIS_2		tris0
	#define MX_SPI_SCK_PIN_2		-1
	#define MX_SPI_SCK_PORT_2		port0
	#define MX_SPI_SCK_TRIS_2		tris0
	#define MX_SPI_CS_PIN_2			0
	#define MX_SPI_CS_PORT_2		0
	#define MX_SPI_BMODE_2			6
	#define MX_SPI_PR_SCALE_2		64
	#define MX_SPI_PO_SCALE_2		0
	#define MX_SPI_INT_2			0
 #else
  #ifndef	MX_SPI_REF3
	#define MX_SPI_REF3
	#define SPI_2_MX_SPI_UREF			3
	#define MX_SPI_CHANNEL_3		1
	#define MX_SPI_MOSI_PIN_3		-1
	#define MX_SPI_MOSI_PORT_3		port0
	#define MX_SPI_MOSI_TRIS_3		tris0
	#define MX_SPI_MISO_PIN_3		-1
	#define MX_SPI_MISO_PORT_3		port0
	#define MX_SPI_MISO_TRIS_3		tris0
	#define MX_SPI_SCK_PIN_3		-1
	#define MX_SPI_SCK_PORT_3		port0
	#define MX_SPI_SCK_TRIS_3		tris0
	#define MX_SPI_CS_PIN_3			0
	#define MX_SPI_CS_PORT_3		0
	#define MX_SPI_BMODE_3			6
	#define MX_SPI_PR_SCALE_3		64
	#define MX_SPI_PO_SCALE_3		0
	#define MX_SPI_INT_3			0
  #else
   #ifndef	MX_SPI_REF4
	#define MX_SPI_REF4
	#define SPI_2_MX_SPI_UREF			4
	#define MX_SPI_CHANNEL_4		1
	#define MX_SPI_MOSI_PIN_4		-1
	#define MX_SPI_MOSI_PORT_4		port0
	#define MX_SPI_MOSI_TRIS_4		tris0
	#define MX_SPI_MISO_PIN_4		-1
	#define MX_SPI_MISO_PORT_4		port0
	#define MX_SPI_MISO_TRIS_4		tris0
	#define MX_SPI_SCK_PIN_4		-1
	#define MX_SPI_SCK_PORT_4		port0
	#define MX_SPI_SCK_TRIS_4		tris0
	#define MX_SPI_CS_PIN_4			0
	#define MX_SPI_CS_PORT_4		0
	#define MX_SPI_BMODE_4			6
	#define MX_SPI_PR_SCALE_4		64
	#define MX_SPI_PO_SCALE_4		0
	#define MX_SPI_INT_4			0
   #endif
  #endif
 #endif
#endif

#define SPI_2_SPI_Master_Init		CAL_APPEND(FC_CAL_SPI_Master_Init_, SPI_2_MX_SPI_UREF)
#define SPI_2_SPI_Master_Uninit	CAL_APPEND(FC_CAL_SPI_Master_Uninit_, SPI_2_MX_SPI_UREF)
#define SPI_2_SPI_Master_Byte		CAL_APPEND(FC_CAL_SPI_Master_Byte_, SPI_2_MX_SPI_UREF)

extern void SPI_2_SPI_Master_Init ();
extern void SPI_2_SPI_Master_Uninit ();
extern MX_UINT8 SPI_2_SPI_Master_Byte (MX_UINT8 DataOut);

//FRAM commands
#define FRAM_WREN  	6
#define FRAM_WRDI  	4
#define FRAM_RDSR  	5
#define FRAM_WRSR  	1
#define FRAM_READ  	3
#define FRAM_WRITE 	2




//SPI_Legacy(0): //Macro function declarations

void FCD_SPI_Legacy0_SPI_Init();
void FCD_SPI_Legacy0_SPI_Uninit();
void FCD_SPI_Legacy0_SPI_Send_Char(MX_UINT8 Char);
void FCD_SPI_Legacy0_SPI_Send_String(MX_STRING String, MX_UINT8 MSZ_String);
MX_UINT8 FCD_SPI_Legacy0_SPI_Get_Char();
void FCD_SPI_Legacy0_SPI_Get_String(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE, MX_UINT8 NumBytes);
void FCD_SPI_Legacy0_DAC_Send_Char(MX_UINT8 Char);
void FCD_SPI_Legacy0_NVM_Send_Char(MX_UINT8 hi_addr, MX_UINT8 lo_addr, MX_UINT8 Char);
MX_UINT8 FCD_SPI_Legacy0_NVM_Get_Char(MX_UINT8 hi_addr, MX_UINT8 lo_addr);
MX_UINT8 FCD_SPI_Legacy0_FramOutput(MX_UINT8 Char);
void FCD_SPI_Legacy0_EnableFRAM();
void FCD_SPI_Legacy0_DisableFRAM();


//RS232(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Uart Channel		(0-software / 1-4 hardware)
c = tx pin
d = tx port
e = rx pin
f = rx port
g = flow control		(0-Off / 1-On)
h = cts pin
i = cts port
j = rts pin
k = rts port
l = baud rate
m = data bits			(7/8/9) (7 only supported in software modes)
n = return type		(0-byte / 1-MX_UINT16)
o = echo enable		(0-Off / 1-On)
******************************/

//Definitions for RS232 UART slot allocation
#ifndef	MX_UART_REF1
	#define MX_UART_REF1
	#define RS232_3_MX_UART_UREF			1
	#define MX_UART_CHANNEL_1		1
	#define MX_UART_TX_PIN_1		0
	#define MX_UART_TX_PORT_1		porta
	#define MX_UART_TX_TRIS_1		trisa
	#define MX_UART_RX_PIN_1		0
	#define MX_UART_RX_PORT_1		porta
	#define MX_UART_RX_TRIS_1		trisa
	#define MX_UART_FLOWEN_1		0
	#define MX_UART_CTS_PIN_1		4
	#define MX_UART_CTS_PORT_1		portc
	#define MX_UART_CTS_TRIS_1		trisc
	#define MX_UART_RTS_PIN_1		0
	#define MX_UART_RTS_PORT_1		portc
	#define MX_UART_RTS_TRIS_1		trisc
	#define MX_UART_BAUD_1			9600
	#define MX_UART_DBITS_1			8
	#define MX_UART_RETURN_1		0
	#define MX_UART_ECHO_1			0
	#define MX_UART_INT_1			0
#else
 #ifndef	MX_UART_REF2
	#define MX_UART_REF2
	#define RS232_3_MX_UART_UREF			2
	#define MX_UART_CHANNEL_2		1
	#define MX_UART_TX_PIN_2		0
	#define MX_UART_TX_PORT_2		porta
	#define MX_UART_TX_TRIS_2		trisa
	#define MX_UART_RX_PIN_2		0
	#define MX_UART_RX_PORT_2		porta
	#define MX_UART_RX_TRIS_2		trisa
	#define MX_UART_FLOWEN_2		0
	#define MX_UART_CTS_PIN_2		4
	#define MX_UART_CTS_PORT_2		portc
	#define MX_UART_CTS_TRIS_2		trisc
	#define MX_UART_RTS_PIN_2		0
	#define MX_UART_RTS_PORT_2		portc
	#define MX_UART_RTS_TRIS_2		trisc
	#define MX_UART_BAUD_2			9600
	#define MX_UART_DBITS_2			8
	#define MX_UART_RETURN_2		0
	#define MX_UART_ECHO_2			0
	#define MX_UART_INT_2			0
 #else
  #ifndef	MX_UART_REF3
	#define MX_UART_REF3
	#define RS232_3_MX_UART_UREF			3
	#define MX_UART_CHANNEL_3		1
	#define MX_UART_TX_PIN_3		0
	#define MX_UART_TX_PORT_3		porta
	#define MX_UART_TX_TRIS_3		trisa
	#define MX_UART_RX_PIN_3		0
	#define MX_UART_RX_PORT_3		porta
	#define MX_UART_RX_TRIS_3		trisa
	#define MX_UART_FLOWEN_3		0
	#define MX_UART_CTS_PIN_3		4
	#define MX_UART_CTS_PORT_3		portc
	#define MX_UART_CTS_TRIS_3		trisc
	#define MX_UART_RTS_PIN_3		0
	#define MX_UART_RTS_PORT_3		portc
	#define MX_UART_RTS_TRIS_3		trisc
	#define MX_UART_BAUD_3			9600
	#define MX_UART_DBITS_3			8
	#define MX_UART_RETURN_3		0
	#define MX_UART_ECHO_3			0
	#define MX_UART_INT_3			0
  #else
   #ifndef	MX_UART_REF4
	#define MX_UART_REF4
	#define RS232_3_MX_UART_UREF			4
	#define MX_UART_CHANNEL_4		1
	#define MX_UART_TX_PIN_4		0
	#define MX_UART_TX_PORT_4		porta
	#define MX_UART_TX_TRIS_4		trisa
	#define MX_UART_RX_PIN_4		0
	#define MX_UART_RX_PORT_4		porta
	#define MX_UART_RX_TRIS_4		trisa
	#define MX_UART_FLOWEN_4		0
	#define MX_UART_CTS_PIN_4		4
	#define MX_UART_CTS_PORT_4		portc
	#define MX_UART_CTS_TRIS_4		trisc
	#define MX_UART_RTS_PIN_4		0
	#define MX_UART_RTS_PORT_4		portc
	#define MX_UART_RTS_TRIS_4		trisc
	#define MX_UART_BAUD_4			9600
	#define MX_UART_DBITS_4			8
	#define MX_UART_RETURN_4		0
	#define MX_UART_ECHO_4			0
	#define MX_UART_INT_4			0
   #endif
  #endif
 #endif
#endif

#define RS232_3_UART_Init		CAL_APPEND(FC_CAL_UART_Init_, RS232_3_MX_UART_UREF)
#define RS232_3_UART_Send		CAL_APPEND(FC_CAL_UART_Send_, RS232_3_MX_UART_UREF)
#define RS232_3_UART_Receive		CAL_APPEND(FC_CAL_UART_Receive_, RS232_3_MX_UART_UREF)
#define RS232_3_UART_Update_Baud CAL_APPEND(FC_CAL_UART_Update_Baud_, RS232_3_MX_UART_UREF)

extern void RS232_3_UART_Init();
extern void RS232_3_UART_Send(MX_UINT16 nChar);
extern MX_SINT16 RS232_3_UART_Receive(MX_UINT8 nTimeout);
extern void RS232_3_UART_Update_Baud(MX_UINT8 newbaud);




//RS232(0): //Macro function declarations

void FCD_RS2320_SendRS232Char(MX_SINT16 nChar);
void FCD_RS2320_SendRS232String(MX_STRING String, MX_UINT8 MSZ_String);
MX_SINT16 FCD_RS2320_ReceiveRS232Char(MX_UINT8 nTimeout);
void FCD_RS2320_ReceiveRS232String(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE, MX_UINT8 nTimeout, MX_UINT8 NumBytes);
void FCD_RS2320_ChangeHWBaud(MX_UINT8 newbaud);



//LCDDisplay(0): //Macro implementations


void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask)
{
	
		MX_UINT8 pt;

		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		pt = ((in >> 4) & 0x0f);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		pt = (in & 0x0f);
		LCD_1__DELAY;
		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;

}

void FCD_LCDDisplay0_Start()
{
	
		FC_CAL_Bit_Low_DDR(LCD_1__PORT0, LCD_1__TRIS0, LCD_1__BIT0);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT1, LCD_1__TRIS1, LCD_1__BIT1);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT2, LCD_1__TRIS2, LCD_1__BIT2);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT3, LCD_1__TRIS3, LCD_1__BIT3);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT4, LCD_1__TRIS4, LCD_1__RS);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT5, LCD_1__TRIS5, LCD_1__E);

		Wdt_Delay_Ms(12);

		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x32, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x2c, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x06, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x0c, 0);
		Wdt_Delay_Ms(2);

		//clear the display
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Clear()
{
	
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character)
{
	
		FCD_LCDDisplay0_RawSend(Character, 0x10);

}

void FCD_LCDDisplay0_Command(MX_UINT8 in)
{
	
		FCD_LCDDisplay0_RawSend(in, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y)
{
	
	  #if (LCD_1__ROWCNT == 1)
	    y=0x80;
	  #endif

	  #if (LCD_1__ROWCNT == 2)
		if (y==0)
			y=0x80;
		else
			y=0xc0;
	  #endif

	  #if (LCD_1__ROWCNT == 4)
		if (y==0)
			y=0x80;
		else if (y==1)
			y=0xc0;

		#if (LCD_1__COLCNT == 16)
			else if (y==2)
				y=0x90;
			else
				y=0xd0;
		#endif

		#if (LCD_1__COLCNT == 20)
			else if (y==2)
				y=0x94;
			else
				y=0xd4;
		#endif
	  #endif

		FCD_LCDDisplay0_RawSend(y+x, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number)
{
	
		MX_SINT16 tmp_int;
		MX_UINT8 tmp_byte;

		if (Number < 0)
		{
			FCD_LCDDisplay0_RawSend('-', 0x10);
			Number = 0 - Number;
		}

		tmp_int = Number;
		if (Number >= 10000)
		{
			tmp_byte = tmp_int / 10000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10000;
				tmp_byte--;
			}
		}
		if (Number >= 1000)
		{
			tmp_byte = tmp_int / 1000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 1000;
				tmp_byte--;
			}
		}
		if (Number >= 100)
		{
			tmp_byte = tmp_int / 100;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 100;
				tmp_byte--;
			}
		}
		if (Number >= 10)
		{
			tmp_byte = tmp_int / 10;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10;
				tmp_byte--;
			}
		}
		FCD_LCDDisplay0_RawSend('0' + tmp_int, 0x10);

}

void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx = 0;

		for (idx=0; idx<MSZ_String; idx++)
		{
			if (String[idx] == 0)
			{
				break;
			}
			FCD_LCDDisplay0_RawSend(String[idx], 0x10);
		}

}

void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions)
{
	
		MX_UINT8 cmd = 0;
		MX_UINT8 count;

		//Choose the direction
		switch (Direction)
		{
			case 0:
			case 'l':
			case 'L':

				cmd = 0x18;
				break;

			case 1:
			case 'r':
			case 'R':

				cmd = 0x1C;
				break;

			default:
				break;
		}

		//If direction accepted then scroll the specified amount
		if (cmd)
		{
			for (count = 0; count < Num_Positions; count++)
				FCD_LCDDisplay0_Command(cmd);
		}

}

void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line)
{
	
		MX_UINT8 count;
		MX_UINT8 rowcount;

		//Define number of columns per line
		#if (LCD_1__ROWCNT == 1)
			rowcount=80;
		#endif

		#if (LCD_1__ROWCNT == 2)
			rowcount=40;
		#endif

		#if (LCD_1__ROWCNT == 4)
			#if (LCD_1__COLCNT == 16)
				rowcount=16;
			#endif
			#if (LCD_1__COLCNT == 20)
				rowcount=20;
			#endif
		#endif

		//Start at beginning of the line
		FCD_LCDDisplay0_Cursor (0, Line);

		//Send out spaces to clear line
		for (count = 0; count < rowcount; count++)
			FCD_LCDDisplay0_RawSend(' ', 0x10);

		//Move back to the beginning of the line.
		FCD_LCDDisplay0_Cursor (0, Line);

}

void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7)
{
	   //set CGRAM address

	   FCD_LCDDisplay0_RawSend(64 + (nIdx << 3), 0);
	   delay_ms(2);

	   //write CGRAM data
	   FCD_LCDDisplay0_RawSend(d0, 0x10);
	   FCD_LCDDisplay0_RawSend(d1, 0x10);
	   FCD_LCDDisplay0_RawSend(d2, 0x10);
	   FCD_LCDDisplay0_RawSend(d3, 0x10);
	   FCD_LCDDisplay0_RawSend(d4, 0x10);
	   FCD_LCDDisplay0_RawSend(d5, 0x10);
	   FCD_LCDDisplay0_RawSend(d6, 0x10);
	   FCD_LCDDisplay0_RawSend(d7, 0x10);

	   //Clear the display
	   FCD_LCDDisplay0_RawSend(0x01, 0);
	   delay_ms(2);
	   FCD_LCDDisplay0_RawSend(0x02, 0);
	   delay_ms(2);

}



//SPI_Legacy(0): //Macro implementations


void FCD_SPI_Legacy0_SPI_Init()
{
	
		//Disable SPI Devices
		FC_CAL_Bit_High_DDR(SPI_2_MX_SPI_LEGACY_DAC_PORT, SPI_2_MX_SPI_LEGACY_DAC_TRIS, SPI_2_MX_SPI_LEGACY_DAC_PIN);
		FC_CAL_Bit_High_DDR(SPI_2_MX_SPI_LEGACY_FRAM_PORT, SPI_2_MX_SPI_LEGACY_FRAM_TRIS, SPI_2_MX_SPI_LEGACY_FRAM_PIN);

		//Init SPI
		SPI_2_SPI_Master_Init();		//Call initialise function

}

void FCD_SPI_Legacy0_SPI_Uninit()
{
	
		//Convert SPI Device Control Lines To Inputs
		FC_CAL_Bit_In_DDR(SPI_2_MX_SPI_LEGACY_DAC_PORT, SPI_2_MX_SPI_LEGACY_DAC_TRIS, SPI_2_MX_SPI_LEGACY_DAC_PIN);
		FC_CAL_Bit_In_DDR(SPI_2_MX_SPI_LEGACY_FRAM_PORT, SPI_2_MX_SPI_LEGACY_FRAM_TRIS, SPI_2_MX_SPI_LEGACY_FRAM_PIN);

		//Uninit SPI
		SPI_2_SPI_Master_Uninit();		//Call uninitialise function

}

void FCD_SPI_Legacy0_SPI_Send_Char(MX_UINT8 Char)
{
	
		SPI_2_SPI_Master_Byte(Char);

}

void FCD_SPI_Legacy0_SPI_Send_String(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx;
		for(idx = 0; idx < MSZ_String; idx++)
		{
			if (String[idx] == 0)				//End of string data?
				break;

			SPI_2_SPI_Master_Byte(String[idx]);
		}

}

MX_UINT8 FCD_SPI_Legacy0_SPI_Get_Char()
{
	
		MX_UINT8 retVal = 0;

		retVal = SPI_2_SPI_Master_Byte(0xFF);

		return (retVal);

}

void FCD_SPI_Legacy0_SPI_Get_String(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE, MX_UINT8 NumBytes)
{
		MX_UINT8 idx;

		if (NumBytes > FCR_RETVAL_SIZE)
			NumBytes = FCR_RETVAL_SIZE;

		for (idx = 0; idx < NumBytes; idx++)
		{
			FCR_RETVAL[idx] = SPI_2_SPI_Master_Byte(0xFF);		//Collect incoming data byte
		}

		if (idx < FCR_RETVAL_SIZE)
			FCR_RETVAL[idx] = 0;					//Terminate string if string variable is longer then expected data

}

void FCD_SPI_Legacy0_DAC_Send_Char(MX_UINT8 Char)
{
	
		MX_UINT8 dac_val;

		FC_CAL_Bit_Low(SPI_2_MX_SPI_LEGACY_DAC_PORT, SPI_2_MX_SPI_LEGACY_DAC_PIN);		//enable dac

		dac_val = (Char & 0xF0) >> 4;
		SPI_2_SPI_Master_Byte(dac_val);

		dac_val = (Char & 0x0F) << 4;
		SPI_2_SPI_Master_Byte(dac_val);

		FC_CAL_Bit_High(SPI_2_MX_SPI_LEGACY_DAC_PORT, SPI_2_MX_SPI_LEGACY_DAC_PIN);		//disable dac

}

void FCD_SPI_Legacy0_NVM_Send_Char(MX_UINT8 hi_addr, MX_UINT8 lo_addr, MX_UINT8 Char)
{
	
		//enable writes
		FCD_SPI_Legacy0_EnableFRAM();
		FCD_SPI_Legacy0_FramOutput(FRAM_WREN);
		FCD_SPI_Legacy0_DisableFRAM();

		//send write-fram command, address and data
		FCD_SPI_Legacy0_EnableFRAM();
		FCD_SPI_Legacy0_FramOutput(FRAM_WRITE);
		FCD_SPI_Legacy0_FramOutput(hi_addr);
		FCD_SPI_Legacy0_FramOutput(lo_addr);
		FCD_SPI_Legacy0_FramOutput(Char);
		FCD_SPI_Legacy0_DisableFRAM();

}

MX_UINT8 FCD_SPI_Legacy0_NVM_Get_Char(MX_UINT8 hi_addr, MX_UINT8 lo_addr)
{
	
		MX_UINT8 retVal;

		FCD_SPI_Legacy0_EnableFRAM();

		//send read-fram command and address
		FCD_SPI_Legacy0_FramOutput(FRAM_READ);
		FCD_SPI_Legacy0_FramOutput(hi_addr);
		FCD_SPI_Legacy0_FramOutput(lo_addr);

		//read the data
		retVal = FCD_SPI_Legacy0_FramOutput(0x5A);  	//don't care byte of 0x5A

		FCD_SPI_Legacy0_DisableFRAM();

		return(retVal);

}

MX_UINT8 FCD_SPI_Legacy0_FramOutput(MX_UINT8 Char)
{
	
		MX_UINT8 retVal = 0;
		retVal = SPI_2_SPI_Master_Byte(Char);
		return (retVal);

}

void FCD_SPI_Legacy0_EnableFRAM()
{
	
		FC_CAL_Bit_Low(SPI_2_MX_SPI_LEGACY_FRAM_PORT, SPI_2_MX_SPI_LEGACY_FRAM_PIN);

}

void FCD_SPI_Legacy0_DisableFRAM()
{
	
		FC_CAL_Bit_High(SPI_2_MX_SPI_LEGACY_FRAM_PORT, SPI_2_MX_SPI_LEGACY_FRAM_PIN);

}



//RS232(0): //Macro implementations


void FCD_RS2320_SendRS232Char(MX_SINT16 nChar)
{
	
		RS232_3_UART_Send ( nChar);

}

void FCD_RS2320_SendRS232String(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx;
		for(idx = 0; idx < MSZ_String; idx++)
		{
			if (String[idx] == 0)
				break;
			else RS232_3_UART_Send ( String[idx] );
		}

}

MX_SINT16 FCD_RS2320_ReceiveRS232Char(MX_UINT8 nTimeout)
{
	
		return ( RS232_3_UART_Receive ( nTimeout) );

}

void FCD_RS2320_ReceiveRS232String(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE, MX_UINT8 nTimeout, MX_UINT8 NumBytes)
{
	
		MX_UINT8 idx;
		MX_SINT16 RS232_TO = 255;
		MX_SINT16 in;

		if ( 0 != 0 )
			RS232_TO = 256;

		if (NumBytes > FCR_RETVAL_SIZE)
			NumBytes = FCR_RETVAL_SIZE;

		for (idx = 0; idx < NumBytes; idx++)
		{
			in = RS232_3_UART_Receive ( nTimeout);
			if(in < RS232_TO)
				FCR_RETVAL[idx] = in & 0xFF;
			else
				break;
		}

		if (idx < FCR_RETVAL_SIZE)
			FCR_RETVAL[idx] = 0;

}

void FCD_RS2320_ChangeHWBaud(MX_UINT8 newbaud)
{
	
		RS232_3_UART_Update_Baud (newbaud);

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_spi_nrf_reg_read()
{

	//Comment:
	//read reg00

	//Calculation
	//Calculation:
	//  spi_data0 = 0x00
	FCV_SPI_DATA0 = 0x00;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg00_config = spi_data1
	FCV_REG00_CONFIG = FCV_SPI_DATA1;

	//Comment:
	//read reg01

	//Calculation
	//Calculation:
	//  spi_data0 = 0x01
	FCV_SPI_DATA0 = 0x01;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg01_enaa = spi_data1
	FCV_REG01_ENAA = FCV_SPI_DATA1;

	//Comment:
	//read reg02

	//Calculation
	//Calculation:
	//  spi_data0 = 0x02
	FCV_SPI_DATA0 = 0x02;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg02_en_rxaddr = spi_data1
	FCV_REG02_EN_RXADDR = FCV_SPI_DATA1;

	//Comment:
	//read reg03

	//Calculation
	//Calculation:
	//  spi_data0 = 0x03
	FCV_SPI_DATA0 = 0x03;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg03_setup_aw = spi_data1
	FCV_REG03_SETUP_AW = FCV_SPI_DATA1;

	//Comment:
	//read reg04

	//Calculation
	//Calculation:
	//  spi_data0 = 0x04
	FCV_SPI_DATA0 = 0x04;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg04_setup_retr = spi_data1
	FCV_REG04_SETUP_RETR = FCV_SPI_DATA1;

	//Comment:
	//read reg05

	//Calculation
	//Calculation:
	//  spi_data0 = 0x05
	FCV_SPI_DATA0 = 0x05;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg05_rf_ch = spi_data1
	FCV_REG05_RF_CH = FCV_SPI_DATA1;

	//Comment:
	//read reg06

	//Calculation
	//Calculation:
	//  spi_data0 = 0x06
	FCV_SPI_DATA0 = 0x06;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg06_rf_setup = spi_data1
	FCV_REG06_RF_SETUP = FCV_SPI_DATA1;

	//Comment:
	//read reg07

	//Calculation
	//Calculation:
	//  spi_data0 = 0x07
	FCV_SPI_DATA0 = 0x07;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg07_status = spi_data1
	FCV_REG07_STATUS = FCV_SPI_DATA1;

	//Comment:
	//read reg11

	//Calculation
	//Calculation:
	//  spi_data0 = 0x11
	FCV_SPI_DATA0 = 0x11;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg11_rx_pw_p0 = spi_data1
	FCV_REG11_RX_PW_P0 = FCV_SPI_DATA1;

	//Comment:
	//read reg17

	//Calculation
	//Calculation:
	//  spi_data0 = 0x17
	FCV_SPI_DATA0 = 0x17;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg17_fifo_status = spi_data1
	FCV_REG17_FIFO_STATUS = FCV_SPI_DATA1;

	//Comment:
	//read reg1C

	//Calculation
	//Calculation:
	//  spi_data0 = 0x1C
	FCV_SPI_DATA0 = 0x1C;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg1C_dynpd = spi_data1
	FCV_REG1C_DYNPD = FCV_SPI_DATA1;

	//Comment:
	//read reg1D

	//Calculation
	//Calculation:
	//  spi_data0 = 0x1D
	FCV_SPI_DATA0 = 0x1D;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg1D_feature = spi_data1
	FCV_REG1D_FEATURE = FCV_SPI_DATA1;

}


void FCM_cmd_read_reg()
{

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

}


void FCM_lcd_line0()
{

	//Calculation
	//Calculation:
	//  cursorx = 0
	FCV_CURSORX = 0;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 0)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 0);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg00_config)
	FCD_LCDDisplay0_PrintNumber(FCV_REG00_CONFIG);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 4
	FCV_CURSORX = FCV_CURSORX + 4;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 0)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 0);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg01_enaa)
	FCD_LCDDisplay0_PrintNumber(FCV_REG01_ENAA);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 4
	FCV_CURSORX = FCV_CURSORX + 4;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 0)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 0);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg02_en_rxaddr)
	FCD_LCDDisplay0_PrintNumber(FCV_REG02_EN_RXADDR);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 4
	FCV_CURSORX = FCV_CURSORX + 4;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 0)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 0);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg03_setup_aw)
	FCD_LCDDisplay0_PrintNumber(FCV_REG03_SETUP_AW);

}


void FCM_lcd_line1()
{

	//Calculation
	//Calculation:
	//  cursorx = 0
	FCV_CURSORX = 0;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 1)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 1);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg04_setup_retr)
	FCD_LCDDisplay0_PrintNumber(FCV_REG04_SETUP_RETR);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 4
	FCV_CURSORX = FCV_CURSORX + 4;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 1)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 1);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg05_rf_ch)
	FCD_LCDDisplay0_PrintNumber(FCV_REG05_RF_CH);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 4
	FCV_CURSORX = FCV_CURSORX + 4;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 1)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 1);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg11_rx_pw_p0)
	FCD_LCDDisplay0_PrintNumber(FCV_REG11_RX_PW_P0);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 4
	FCV_CURSORX = FCV_CURSORX + 4;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 1)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 1);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg1D_feature)
	FCD_LCDDisplay0_PrintNumber(FCV_REG1D_FEATURE);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 4
	FCV_CURSORX = FCV_CURSORX + 4;

}


void FCM_lcd_line2()
{

	//Call Macro
	//Call Macro: cmd_read_tx_addr()
	FCM_cmd_read_tx_addr();

	//Call Macro
	//Call Macro: cmd_read_rx_addr()
	FCM_cmd_read_rx_addr();

	//Call Component Macro
	//Call Component Macro: Cursor(0, 2)
	FCD_LCDDisplay0_Cursor(0, 2);

	//Call Component Macro
	//Call Component Macro: PrintString("t:")
	FCD_LCDDisplay0_PrintString("t:", 2);

	//Call Component Macro
	//Call Component Macro: Cursor(2, 2)
	FCD_LCDDisplay0_Cursor(2, 2);

	//Call Component Macro
	//Call Component Macro: PrintString(tx_addr)
	FCD_LCDDisplay0_PrintString(FCV_TX_ADDR, FCSZ_TX_ADDR);

	//Call Component Macro
	//Call Component Macro: Cursor(7, 2)
	FCD_LCDDisplay0_Cursor(7, 2);

	//Call Component Macro
	//Call Component Macro: PrintString(" r:")
	FCD_LCDDisplay0_PrintString(" r:", 3);

	//Call Component Macro
	//Call Component Macro: Cursor(10, 2)
	FCD_LCDDisplay0_Cursor(10, 2);

	//Call Component Macro
	//Call Component Macro: PrintString(rx_addr)
	FCD_LCDDisplay0_PrintString(FCV_RX_ADDR, FCSZ_RX_ADDR);

}


void FCM_cmd_read_rx_addr()
{

	//Comment:
	//read rx addr

	//Calculation
	//Calculation:
	//  spi_data0 = 0x0A
	FCV_SPI_DATA0 = 0x0A;

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg0A_rx_addr_p0_byte0 = spi_data1
	FCV_REG0A_RX_ADDR_P0_BYTE0 = FCV_SPI_DATA1;

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg0A_rx_addr_p0_byte1 = spi_data1
	FCV_REG0A_RX_ADDR_P0_BYTE1 = FCV_SPI_DATA1;

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg0A_rx_addr_p0_byte2 = spi_data1
	FCV_REG0A_RX_ADDR_P0_BYTE2 = FCV_SPI_DATA1;

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg0A_rx_addr_p0_byte3 = spi_data1
	FCV_REG0A_RX_ADDR_P0_BYTE3 = FCV_SPI_DATA1;

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg0A_rx_addr_p0_byte4 = spi_data1
	FCV_REG0A_RX_ADDR_P0_BYTE4 = FCV_SPI_DATA1;

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

}


void FCM_cmd_read_tx_addr()
{

	//Comment:
	//read rx addr

	//Calculation
	//Calculation:
	//  spi_data0 = 0x10
	FCV_SPI_DATA0 = 0x10;

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg10_tx_addr_byte0 = spi_data1
	FCV_REG10_TX_ADDR_BYTE0 = FCV_SPI_DATA1;

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg10_tx_addr_byte1 = spi_data1
	FCV_REG10_TX_ADDR_BYTE1 = FCV_SPI_DATA1;

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg10_tx_addr_byte2 = spi_data1
	FCV_REG10_TX_ADDR_BYTE2 = FCV_SPI_DATA1;

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg10_tx_addr_byte3 = spi_data1
	FCV_REG10_TX_ADDR_BYTE3 = FCV_SPI_DATA1;

	//Call Component Macro
	//Call Component Macro: spi_data1=SPI_Get_Char()
	FCV_SPI_DATA1 = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  reg10_tx_addr_byte4 = spi_data1
	FCV_REG10_TX_ADDR_BYTE4 = FCV_SPI_DATA1;

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

}


void FCM_lcd_line3()
{

	//Call Macro
	//Call Macro: cmd_read_tx_addr()
	FCM_cmd_read_tx_addr();

	//Calculation
	//Calculation:
	//  cursorx = 0
	FCV_CURSORX = 0;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 3)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 3);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg10_tx_addr_byte0)
	FCD_LCDDisplay0_PrintNumber(FCV_REG10_TX_ADDR_BYTE0);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 3
	FCV_CURSORX = FCV_CURSORX + 3;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 3)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 3);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg10_tx_addr_byte1)
	FCD_LCDDisplay0_PrintNumber(FCV_REG10_TX_ADDR_BYTE1);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 3
	FCV_CURSORX = FCV_CURSORX + 3;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 3)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 3);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg10_tx_addr_byte2)
	FCD_LCDDisplay0_PrintNumber(FCV_REG10_TX_ADDR_BYTE2);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 3
	FCV_CURSORX = FCV_CURSORX + 3;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 3)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 3);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg10_tx_addr_byte3)
	FCD_LCDDisplay0_PrintNumber(FCV_REG10_TX_ADDR_BYTE3);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 3
	FCV_CURSORX = FCV_CURSORX + 3;

	//Call Component Macro
	//Call Component Macro: Cursor(cursorx, 3)
	FCD_LCDDisplay0_Cursor(FCV_CURSORX, 3);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg10_tx_addr_byte4)
	FCD_LCDDisplay0_PrintNumber(FCV_REG10_TX_ADDR_BYTE4);

	//Calculation
	//Calculation:
	//  cursorx = cursorx + 3
	FCV_CURSORX = FCV_CURSORX + 3;

}


void FCM_nrf_tx_init()
{

	//Calculation
	//Calculation:
	//  reg_to_write = 0x00
	//  data_to_write = 0x0E
	FCV_REG_TO_WRITE = 0x00;
	FCV_DATA_TO_WRITE = 0x0E;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 01
	//  data_to_write = 0x3F
	FCV_REG_TO_WRITE = 01;
	FCV_DATA_TO_WRITE = 0x3F;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 02
	//  data_to_write = 0x03
	FCV_REG_TO_WRITE = 02;
	FCV_DATA_TO_WRITE = 0x03;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 03
	//  data_to_write = 0x03
	FCV_REG_TO_WRITE = 03;
	FCV_DATA_TO_WRITE = 0x03;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 0x04
	//  data_to_write = 0x5F
	FCV_REG_TO_WRITE = 0x04;
	FCV_DATA_TO_WRITE = 0x5F;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 0x05
	//  data_to_write = 0x4C
	FCV_REG_TO_WRITE = 0x05;
	FCV_DATA_TO_WRITE = 0x4C;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 0x06
	//  data_to_write = 0x27
	FCV_REG_TO_WRITE = 0x06;
	FCV_DATA_TO_WRITE = 0x27;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 0x11
	//  data_to_write = payloadsize
	FCV_REG_TO_WRITE = 0x11;
	FCV_DATA_TO_WRITE = FCV_PAYLOADSIZE;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Call Macro
	//Call Macro: set_tx_addr()
	FCM_set_tx_addr();

	//Call Macro
	//Call Macro: set_rx_addr()
	FCM_set_rx_addr();

	//Call Macro
	//Call Macro: flush_fifo_txrx()
	FCM_flush_fifo_txrx();

}


void FCM_cmd_write_reg()
{

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Calculation
	//Calculation:
	//  spi_data0 = reg_to_write + 0x20
	FCV_SPI_DATA0 = FCV_REG_TO_WRITE + 0x20;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = data_to_write
	FCV_SPI_DATA0 = FCV_DATA_TO_WRITE;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

}


void FCM_set_tx_addr()
{

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Calculation
	//Calculation:
	//  spi_data0 = 0b00110000
	FCV_SPI_DATA0 = 48;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg10_tx_addr_byte0
	FCV_SPI_DATA0 = FCV_REG10_TX_ADDR_BYTE0;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg10_tx_addr_byte1
	FCV_SPI_DATA0 = FCV_REG10_TX_ADDR_BYTE1;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg10_tx_addr_byte2
	FCV_SPI_DATA0 = FCV_REG10_TX_ADDR_BYTE2;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg10_tx_addr_byte3
	FCV_SPI_DATA0 = FCV_REG10_TX_ADDR_BYTE3;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg10_tx_addr_byte4
	FCV_SPI_DATA0 = FCV_REG10_TX_ADDR_BYTE4;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

}


void FCM_set_rx_addr()
{

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Calculation
	//Calculation:
	//  spi_data0 = 0b00101010
	FCV_SPI_DATA0 = 42;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg0A_rx_addr_p0_byte0
	FCV_SPI_DATA0 = FCV_REG0A_RX_ADDR_P0_BYTE0;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg0A_rx_addr_p0_byte1
	FCV_SPI_DATA0 = FCV_REG0A_RX_ADDR_P0_BYTE1;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg0A_rx_addr_p0_byte2
	FCV_SPI_DATA0 = FCV_REG0A_RX_ADDR_P0_BYTE2;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg0A_rx_addr_p0_byte3
	FCV_SPI_DATA0 = FCV_REG0A_RX_ADDR_P0_BYTE3;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = reg0A_rx_addr_p0_byte4
	FCV_SPI_DATA0 = FCV_REG0A_RX_ADDR_P0_BYTE4;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

}


void FCM_radio_send_data()
{

	//Call Macro
	//Call Macro: flush_fifo_txrx()
	FCM_flush_fifo_txrx();

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Calculation
	//Calculation:
	//  spi_data0 = 0xA0
	FCV_SPI_DATA0 = 0xA0;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  loop_count = 0
	FCV_LOOP_COUNT = 0;

	//Connection Point
	//Connection Point: [A]: A
FCC_radio_send_data_A:
;

	//Calculation
	//Calculation:
	//  spi_data0 = payload_transmit[loop_count]
	FCV_SPI_DATA0 = FCV_PAYLOAD_TRANSMIT[FCV_LOOP_COUNT];

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  loop_count = loop_count + 1
	FCV_LOOP_COUNT = FCV_LOOP_COUNT + 1;

	//Decision
	//Decision: loop_count = payloadsize?
	if (FCV_LOOP_COUNT == FCV_PAYLOADSIZE)
	{

	} else {

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_radio_send_data_A;

	}

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//CE
	//Output: 1 -> C1
	trisc = trisc & 0xFD;
	if ((1))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

	//Delay
	//Delay: 6 ms
	delay_ms(6);

	//CE
	//Output: 0 -> C1
	trisc = trisc & 0xFD;
	if ((0))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

	//Call Macro
	//Call Macro: check_status()
	FCM_check_status();

	//Call Macro
	//Call Macro: show_status()
	FCM_show_status();

	//Calculation
	//Calculation:
	//  status_tx_ds = reg07_status AND 0b00100000
	FCV_STATUS_TX_DS = FCV_REG07_STATUS & 32;

	//Decision
	//Decision: status_tx_ds = 0x20?
	if (FCV_STATUS_TX_DS == 0x20)
	{

		//tx_ack
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Call Component Macro
		//Call Component Macro: Cursor(0, 0)
		FCD_LCDDisplay0_Cursor(0, 0);

		//Call Component Macro
		//Call Component Macro: PrintString("TX SUCCESS!")
		FCD_LCDDisplay0_PrintString("TX SUCCESS!", 11);

		//Calculation
		//Calculation:
		//  reg_to_write = 0x07
		//  data_to_write = 0x2E
		FCV_REG_TO_WRITE = 0x07;
		FCV_DATA_TO_WRITE = 0x2E;

		//Call Macro
		//Call Macro: cmd_write_reg()
		FCM_cmd_write_reg();

	// } else {

	}

	//Calculation
	//Calculation:
	//  status_max_rt = reg07_status AND 0b00010000
	FCV_STATUS_MAX_RT = FCV_REG07_STATUS & 16;

	//Decision
	//Decision: status_max_rt = 0x10?
	if (FCV_STATUS_MAX_RT == 0x10)
	{

		//Call Component Macro
		//Call Component Macro: Cursor(0, 0)
		FCD_LCDDisplay0_Cursor(0, 0);

		//Call Component Macro
		//Call Component Macro: PrintString("TX FAIL")
		FCD_LCDDisplay0_PrintString("TX FAIL", 7);

		//Calculation
		//Calculation:
		//  reg_to_write = 0x07
		//  data_to_write = 0x3E
		FCV_REG_TO_WRITE = 0x07;
		FCV_DATA_TO_WRITE = 0x3E;

		//Call Macro
		//Call Macro: cmd_write_reg()
		FCM_cmd_write_reg();

	// } else {

	}

	//Call Macro
	//Call Macro: disp_datatx()
	FCM_disp_datatx();

}


void FCM_flush_fifo_txrx()
{

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Calculation
	//Calculation:
	//  spi_data0 = 0xE1
	FCV_SPI_DATA0 = 0xE1;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Calculation
	//Calculation:
	//  spi_data0 = 0xE2
	FCV_SPI_DATA0 = 0xE2;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

}


void FCM_nrf_rx_init()
{

	//Input
	//Input: PORTA -> reg0A_rx_addr_p0_byte4
	trisa = trisa | 0x0F;
	FCV_REG0A_RX_ADDR_P0_BYTE4 = porta & 0x0F;

	//Calculation
	//Calculation:
	//  reg0A_rx_addr_p0_byte4 = reg0A_rx_addr_p0_byte4 + 48
	FCV_REG0A_RX_ADDR_P0_BYTE4 = FCV_REG0A_RX_ADDR_P0_BYTE4 + 48;

	//Calculation
	//Calculation:
	//  reg10_tx_addr_byte4 = reg0A_rx_addr_p0_byte4
	FCV_REG10_TX_ADDR_BYTE4 = FCV_REG0A_RX_ADDR_P0_BYTE4;

	//declare tx addr
	//Calculation:
	//  reg10_tx_addr_byte0 = '0'
	//  reg10_tx_addr_byte1 = '0'
	//  reg10_tx_addr_byte2 = '0'
	//  reg10_tx_addr_byte3 = '0'
	FCV_REG10_TX_ADDR_BYTE0 = '0';
	FCV_REG10_TX_ADDR_BYTE1 = '0';
	FCV_REG10_TX_ADDR_BYTE2 = '0';
	FCV_REG10_TX_ADDR_BYTE3 = '0';

	//declare rx addr
	//Calculation:
	//  reg0A_rx_addr_p0_byte0 = '0'
	//  reg0A_rx_addr_p0_byte1 = '0'
	//  reg0A_rx_addr_p0_byte2 = '0'
	//  reg0A_rx_addr_p0_byte3 = '0'
	FCV_REG0A_RX_ADDR_P0_BYTE0 = '0';
	FCV_REG0A_RX_ADDR_P0_BYTE1 = '0';
	FCV_REG0A_RX_ADDR_P0_BYTE2 = '0';
	FCV_REG0A_RX_ADDR_P0_BYTE3 = '0';

	//Calculation
	//Calculation:
	//  reg_to_write = 0x00
	//  data_to_write = 0x0F
	FCV_REG_TO_WRITE = 0x00;
	FCV_DATA_TO_WRITE = 0x0F;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 01
	//  data_to_write = 0x3F
	FCV_REG_TO_WRITE = 01;
	FCV_DATA_TO_WRITE = 0x3F;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 02
	//  data_to_write = 0x03
	FCV_REG_TO_WRITE = 02;
	FCV_DATA_TO_WRITE = 0x03;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 03
	//  data_to_write = 0x03
	FCV_REG_TO_WRITE = 03;
	FCV_DATA_TO_WRITE = 0x03;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 0x04
	//  data_to_write = 0x5F
	FCV_REG_TO_WRITE = 0x04;
	FCV_DATA_TO_WRITE = 0x5F;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 0x05
	//  data_to_write = 0x4C
	FCV_REG_TO_WRITE = 0x05;
	FCV_DATA_TO_WRITE = 0x4C;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 0x06
	//  data_to_write = 0x27
	FCV_REG_TO_WRITE = 0x06;
	FCV_DATA_TO_WRITE = 0x27;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Calculation
	//Calculation:
	//  reg_to_write = 0x11
	//  data_to_write = payloadsize
	FCV_REG_TO_WRITE = 0x11;
	FCV_DATA_TO_WRITE = FCV_PAYLOADSIZE;

	//Call Macro
	//Call Macro: cmd_write_reg()
	FCM_cmd_write_reg();

	//Call Macro
	//Call Macro: set_tx_addr()
	FCM_set_tx_addr();

	//Call Macro
	//Call Macro: set_rx_addr()
	FCM_set_rx_addr();

	//Call Macro
	//Call Macro: flush_fifo_txrx()
	FCM_flush_fifo_txrx();

}


void FCM_show_status()
{

	//Call Component Macro
	//Call Component Macro: Cursor(0, 3)
	FCD_LCDDisplay0_Cursor(0, 3);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg07_status)
	FCD_LCDDisplay0_PrintNumber(FCV_REG07_STATUS);

	//Call Component Macro
	//Call Component Macro: Cursor(3, 3)
	FCD_LCDDisplay0_Cursor(3, 3);

	//Call Component Macro
	//Call Component Macro: PrintNumber(reg17_fifo_status)
	FCD_LCDDisplay0_PrintNumber(FCV_REG17_FIFO_STATUS);

}


void FCM_radio_recieve_data()
{

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Call Macro
	//Call Macro: check_status()
	FCM_check_status();

	//Call Macro
	//Call Macro: show_status()
	FCM_show_status();

	//Decision
	//Decision: reg07_status = 64?
	if (FCV_REG07_STATUS == 64)
	{

		//rx_ack
		//Output: 1 -> A5
		trisa = trisa & 0xDF;
		if ((1))
			porta = (porta & 0xDF) | 0x20;
		else
			porta = porta & 0xDF;

		//Call Component Macro
		//Call Component Macro: Cursor(0, 0)
		FCD_LCDDisplay0_Cursor(0, 0);

		//Call Component Macro
		//Call Component Macro: PrintString("DATA RECIEVED!")
		FCD_LCDDisplay0_PrintString("DATA RECIEVED!", 14);

		//Call Macro
		//Call Macro: read_recieved_data()
		FCM_read_recieved_data();

		//Calculation
		//Calculation:
		//  reg_to_write = 0x07
		//  data_to_write = 0x4E
		FCV_REG_TO_WRITE = 0x07;
		FCV_DATA_TO_WRITE = 0x4E;

		//Call Macro
		//Call Macro: cmd_write_reg()
		FCM_cmd_write_reg();

	} else {

		//rx_ack
		//Output: 0 -> A5
		trisa = trisa & 0xDF;
		if ((0))
			porta = (porta & 0xDF) | 0x20;
		else
			porta = porta & 0xDF;

		//Call Component Macro
		//Call Component Macro: Cursor(0, 0)
		FCD_LCDDisplay0_Cursor(0, 0);

		//Call Component Macro
		//Call Component Macro: PrintString("NO TX DETECTED!")
		FCD_LCDDisplay0_PrintString("NO TX DETECTED!", 15);

		//Calculation
		//Calculation:
		//  payload_recieve = ""
		FCI_SCOPY("",0, FCV_PAYLOAD_RECIEVE,FCSZ_PAYLOAD_RECIEVE);

	}

	//Call Macro
	//Call Macro: flush_fifo_txrx()
	FCM_flush_fifo_txrx();

}


void FCM_tx_addr_to_string()
{

	//Calculation
	//Calculation:
	//  tx_addr = tx_addr + reg10_tx_addr_byte0
	FCI_SHEAD(FCV_TX_ADDR,FCSZ_TX_ADDR, &FCV_REG10_TX_ADDR_BYTE0,1, FCV_TX_ADDR,FCSZ_TX_ADDR);

	//Calculation
	//Calculation:
	//  tx_addr = tx_addr + reg10_tx_addr_byte1
	FCI_SHEAD(FCV_TX_ADDR,FCSZ_TX_ADDR, &FCV_REG10_TX_ADDR_BYTE1,1, FCV_TX_ADDR,FCSZ_TX_ADDR);

	//Calculation
	//Calculation:
	//  tx_addr = tx_addr + reg10_tx_addr_byte2
	FCI_SHEAD(FCV_TX_ADDR,FCSZ_TX_ADDR, &FCV_REG10_TX_ADDR_BYTE2,1, FCV_TX_ADDR,FCSZ_TX_ADDR);

	//Calculation
	//Calculation:
	//  tx_addr = tx_addr + reg10_tx_addr_byte3
	FCI_SHEAD(FCV_TX_ADDR,FCSZ_TX_ADDR, &FCV_REG10_TX_ADDR_BYTE3,1, FCV_TX_ADDR,FCSZ_TX_ADDR);

	//Calculation
	//Calculation:
	//  tx_addr = tx_addr + reg10_tx_addr_byte4
	FCI_SHEAD(FCV_TX_ADDR,FCSZ_TX_ADDR, &FCV_REG10_TX_ADDR_BYTE4,1, FCV_TX_ADDR,FCSZ_TX_ADDR);

}


void FCM_rx_addr_to_string()
{

	//Calculation
	//Calculation:
	//  rx_addr = rx_addr + reg0A_rx_addr_p0_byte0
	FCI_SHEAD(FCV_RX_ADDR,FCSZ_RX_ADDR, &FCV_REG0A_RX_ADDR_P0_BYTE0,1, FCV_RX_ADDR,FCSZ_RX_ADDR);

	//Calculation
	//Calculation:
	//  rx_addr = rx_addr + reg0A_rx_addr_p0_byte1
	FCI_SHEAD(FCV_RX_ADDR,FCSZ_RX_ADDR, &FCV_REG0A_RX_ADDR_P0_BYTE1,1, FCV_RX_ADDR,FCSZ_RX_ADDR);

	//Calculation
	//Calculation:
	//  rx_addr = rx_addr + reg0A_rx_addr_p0_byte2
	FCI_SHEAD(FCV_RX_ADDR,FCSZ_RX_ADDR, &FCV_REG0A_RX_ADDR_P0_BYTE2,1, FCV_RX_ADDR,FCSZ_RX_ADDR);

	//Calculation
	//Calculation:
	//  rx_addr = rx_addr + reg0A_rx_addr_p0_byte3
	FCI_SHEAD(FCV_RX_ADDR,FCSZ_RX_ADDR, &FCV_REG0A_RX_ADDR_P0_BYTE3,1, FCV_RX_ADDR,FCSZ_RX_ADDR);

	//Calculation
	//Calculation:
	//  rx_addr = rx_addr + reg0A_rx_addr_p0_byte4
	FCI_SHEAD(FCV_RX_ADDR,FCSZ_RX_ADDR, &FCV_REG0A_RX_ADDR_P0_BYTE4,1, FCV_RX_ADDR,FCSZ_RX_ADDR);

}


void FCM_disp_datarx()
{

	//Call Component Macro
	//Call Component Macro: Cursor(0, 2)
	FCD_LCDDisplay0_Cursor(0, 2);

	//Call Component Macro
	//Call Component Macro: PrintString(payload_recieve)
	FCD_LCDDisplay0_PrintString(FCV_PAYLOAD_RECIEVE, FCSZ_PAYLOAD_RECIEVE);

}


void FCM_check_status()
{

	//Comment:
	//read reg07

	//Calculation
	//Calculation:
	//  spi_data0 = 0x07
	FCV_SPI_DATA0 = 0x07;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg07_status = spi_data1
	FCV_REG07_STATUS = FCV_SPI_DATA1;

	//Comment:
	//read reg17

	//Calculation
	//Calculation:
	//  spi_data0 = 0x17
	FCV_SPI_DATA0 = 0x17;

	//Call Macro
	//Call Macro: cmd_read_reg()
	FCM_cmd_read_reg();

	//Calculation
	//Calculation:
	//  reg17_fifo_status = spi_data1
	FCV_REG17_FIFO_STATUS = FCV_SPI_DATA1;

}


void FCM_print_display()
{

	//Call Macro
	//Call Macro: check_status()
	FCM_check_status();

	//Calculation
	//Calculation:
	//  status_tx_ds = reg07_status AND 0b00100000
	FCV_STATUS_TX_DS = FCV_REG07_STATUS & 32;

	//Decision
	//Decision: status_tx_ds = 32?
	if (FCV_STATUS_TX_DS == 32)
	{

		//Call Component Macro
		//Call Component Macro: Cursor(0, 0)
		FCD_LCDDisplay0_Cursor(0, 0);

		//Call Component Macro
		//Call Component Macro: PrintString("TX SUCCESS!")
		FCD_LCDDisplay0_PrintString("TX SUCCESS!", 11);

		//Calculation
		//Calculation:
		//  reg_to_write = 0x07
		//  data_to_write = 0x00
		FCV_REG_TO_WRITE = 0x07;
		FCV_DATA_TO_WRITE = 0x00;

		//Call Macro
		//Call Macro: cmd_write_reg()
		FCM_cmd_write_reg();

	} else {

		//Decision
		//Decision: status_tx_ds = 0?
		if (FCV_STATUS_TX_DS == 0)
		{

			//Call Component Macro
			//Call Component Macro: Cursor(0, 0)
			FCD_LCDDisplay0_Cursor(0, 0);

			//Call Component Macro
			//Call Component Macro: PrintString("TX FAIL")
			FCD_LCDDisplay0_PrintString("TX FAIL", 7);

		// } else {

		}

	}

}


void FCM_read_recieved_data()
{

	//Calculation
	//Calculation:
	//  loop_count = 0
	//  payload_recieve = ""
	FCV_LOOP_COUNT = 0;
	FCI_SCOPY("",0, FCV_PAYLOAD_RECIEVE,FCSZ_PAYLOAD_RECIEVE);

	//CSN
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

	//Calculation
	//Calculation:
	//  spi_data0 = 0x61
	FCV_SPI_DATA0 = 0x61;

	//Call Component Macro
	//Call Component Macro: SPI_Send_Char(spi_data0)
	FCD_SPI_Legacy0_SPI_Send_Char(FCV_SPI_DATA0);

	//Connection Point
	//Connection Point: [A]: A
FCC_read_recieved_data_A:
;

	//Call Component Macro
	//Call Component Macro: data_to_read=SPI_Get_Char()
	FCV_DATA_TO_READ = FCD_SPI_Legacy0_SPI_Get_Char();

	//Calculation
	//Calculation:
	//  payload_recieve = payload_recieve + data_to_read
	FCI_SHEAD(FCV_PAYLOAD_RECIEVE,FCSZ_PAYLOAD_RECIEVE, &FCV_DATA_TO_READ,1, FCV_PAYLOAD_RECIEVE,FCSZ_PAYLOAD_RECIEVE);

	//Calculation
	//Calculation:
	//  loop_count = loop_count + 1
	FCV_LOOP_COUNT = FCV_LOOP_COUNT + 1;

	//Decision
	//Decision: loop_count = payloadsize?
	if (FCV_LOOP_COUNT == FCV_PAYLOADSIZE)
	{

	} else {

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_read_recieved_data_A;

	}

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Delay
	//Delay: 5 us
	delay_us(5);

}


void FCM_disp_datatx()
{

	//Call Component Macro
	//Call Component Macro: Cursor(0, 1)
	FCD_LCDDisplay0_Cursor(0, 1);

	//Call Component Macro
	//Call Component Macro: PrintString(payload_transmit)
	FCD_LCDDisplay0_PrintString(FCV_PAYLOAD_TRANSMIT, FCSZ_PAYLOAD_TRANSMIT);

}



void main()
{
	//Initialization
	adcon1 = 0x07;

	
		RS232_3_UART_Init( );		//Call initialise function


	//Interrupt initialization code
	option_reg = 0xC0;


	//Call Component Macro
	//Call Component Macro: Start()
	FCD_LCDDisplay0_Start();

	//Call Component Macro
	//Call Component Macro: Clear()
	FCD_LCDDisplay0_Clear();

	//Call Component Macro
	//Call Component Macro: SPI_Init()
	FCD_SPI_Legacy0_SPI_Init();

	//Delay
	//Delay: 1 ms
	delay_ms(1);

	//CE
	//Output: 1 -> C1
	trisc = trisc & 0xFD;
	if ((1))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

	//CSN
	//Output: 1 -> C2
	trisc = trisc & 0xFB;
	if ((1))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Input
	//Input: PORTA -> reg0A_rx_addr_p0_byte4
	trisa = trisa | 0x0F;
	FCV_REG0A_RX_ADDR_P0_BYTE4 = porta & 0x0F;

	//Calculation
	//Calculation:
	//  reg0A_rx_addr_p0_byte4 = reg0A_rx_addr_p0_byte4 + 48
	FCV_REG0A_RX_ADDR_P0_BYTE4 = FCV_REG0A_RX_ADDR_P0_BYTE4 + 48;

	//Calculation
	//Calculation:
	//  reg10_tx_addr_byte4 = reg0A_rx_addr_p0_byte4
	FCV_REG10_TX_ADDR_BYTE4 = FCV_REG0A_RX_ADDR_P0_BYTE4;

	//declare tx addr
	//Calculation:
	//  reg10_tx_addr_byte0 = '0'
	//  reg10_tx_addr_byte1 = '0'
	//  reg10_tx_addr_byte2 = '0'
	//  reg10_tx_addr_byte3 = '0'
	FCV_REG10_TX_ADDR_BYTE0 = '0';
	FCV_REG10_TX_ADDR_BYTE1 = '0';
	FCV_REG10_TX_ADDR_BYTE2 = '0';
	FCV_REG10_TX_ADDR_BYTE3 = '0';

	//declare rx addr
	//Calculation:
	//  reg0A_rx_addr_p0_byte0 = '0'
	//  reg0A_rx_addr_p0_byte1 = '0'
	//  reg0A_rx_addr_p0_byte2 = '0'
	//  reg0A_rx_addr_p0_byte3 = '0'
	FCV_REG0A_RX_ADDR_P0_BYTE0 = '0';
	FCV_REG0A_RX_ADDR_P0_BYTE1 = '0';
	FCV_REG0A_RX_ADDR_P0_BYTE2 = '0';
	FCV_REG0A_RX_ADDR_P0_BYTE3 = '0';

	//Calculation
	//Calculation:
	//  payloadsize = 16
	FCV_PAYLOADSIZE = 16;

	//Call Macro
	//Call Macro: nrf_rx_init()
	FCM_nrf_rx_init();

	//Calculation
	//Calculation:
	//  payload_transmit = "TESTING MESSAGE!"
	FCI_SCOPY("TESTING MESSAGE!",16, FCV_PAYLOAD_TRANSMIT,FCSZ_PAYLOAD_TRANSMIT);

	//tx_ack
	//Output: 0 -> A4
	trisa = trisa & 0xEF;
	if ((0))
		porta = (porta & 0xEF) | 0x10;
	else
		porta = porta & 0xEF;

	//rx_ack
	//Output: 0 -> A5
	trisa = trisa & 0xDF;
	if ((0))
		porta = (porta & 0xDF) | 0x20;
	else
		porta = porta & 0xDF;

	//Call Macro
	//Call Macro: cmd_read_rx_addr()
	FCM_cmd_read_rx_addr();

	//Call Macro
	//Call Macro: cmd_read_tx_addr()
	FCM_cmd_read_tx_addr();

	//Call Macro
	//Call Macro: rx_addr_to_string()
	FCM_rx_addr_to_string();

	//Call Macro
	//Call Macro: tx_addr_to_string()
	FCM_tx_addr_to_string();

	//Loop
	//Loop: While 1
	while (1)
	{

		//CE
		//Output: 1 -> C1
		trisc = trisc & 0xFD;
		if ((1))
			portc = (portc & 0xFD) | 0x02;
		else
			portc = portc & 0xFD;

		//rx_ack
		//Output: 0 -> A5
		trisa = trisa & 0xDF;
		if ((0))
			porta = (porta & 0xDF) | 0x20;
		else
			porta = porta & 0xDF;

		//tx_ack
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Call Component Macro
		//Call Component Macro: Clear()
		FCD_LCDDisplay0_Clear();

		//Call Macro
		//Call Macro: radio_recieve_data()
		FCM_radio_recieve_data();

		//Call Macro
		//Call Macro: disp_datarx()
		FCM_disp_datarx();

		//Call Component Macro
		//Call Component Macro: Cursor(0, 1)
		FCD_LCDDisplay0_Cursor(0, 1);

		//Call Component Macro
		//Call Component Macro: PrintString("t:")
		FCD_LCDDisplay0_PrintString("t:", 2);

		//Call Component Macro
		//Call Component Macro: PrintString(tx_addr)
		FCD_LCDDisplay0_PrintString(FCV_TX_ADDR, FCSZ_TX_ADDR);

		//Call Component Macro
		//Call Component Macro: PrintString(" r:")
		FCD_LCDDisplay0_PrintString(" r:", 3);

		//Call Component Macro
		//Call Component Macro: PrintString(rx_addr)
		FCD_LCDDisplay0_PrintString(FCV_RX_ADDR, FCSZ_RX_ADDR);

		//Delay
		//Delay: 500 ms
		delay_ms(255);
		delay_ms(245);


	}

	//Loop
	//Loop: While 1
	while (1)
	{

		//Call Component Macro
		//Call Component Macro: Clear()
		FCD_LCDDisplay0_Clear();

		//Call Component Macro
		//Call Component Macro: data_to_read=ReceiveRS232Char(10)
		FCV_DATA_TO_READ = FCD_RS2320_ReceiveRS232Char(10);

		//Decision
		//Decision: data_to_read = 255?
		if (FCV_DATA_TO_READ == 255)
		{

		} else {

			//Call Component Macro
			//Call Component Macro: PrintNumber(data_to_read)
			FCD_LCDDisplay0_PrintNumber(FCV_DATA_TO_READ);

		}

		//Call Component Macro
		//Call Component Macro: SendRS232Char(0x55)
		FCD_RS2320_SendRS232Char(0x55);

		//CE
		//Output: 1 -> C1
		trisc = trisc & 0xFD;
		if ((1))
			portc = (portc & 0xFD) | 0x02;
		else
			portc = portc & 0xFD;

		//rx_ack
		//Output: 0 -> A5
		trisa = trisa & 0xDF;
		if ((0))
			porta = (porta & 0xDF) | 0x20;
		else
			porta = porta & 0xDF;

		//tx_ack
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;


	}

	//Comment:
	//Comment

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



