# MPLAB IDE generated this makefile for use with GNU make.
# Project: hub12test.mcp
# Date: Mon Apr 22 14:01:17 2019

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

hub12test.cof : hub12test.o
	$(CC) /p16F690 "hub12test.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"hub12test.cof" /M"hub12test.map" /W /x

hub12test.o : hub12test.asm C:/Program\ Files/Microchip/MPASM\ Suite/P16F690.INC
	$(AS) /q /p16F690 "hub12test.asm" /l"hub12test.lst" /e"hub12test.err" /d__DEBUG=1 /c-

clean : 
	$(CC) "hub12test.o" "hub12test.hex" "hub12test.err" "hub12test.lst" "hub12test.cof"

