# MPLAB IDE generated this makefile for use with GNU make.
# Project: HUB12_SPI.mcp
# Date: Mon Jun 03 14:40:15 2019

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

HUB12_SPI.cof : HUB12_SPI.o
	$(CC) /p16F690 "HUB12_SPI.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"HUB12_SPI.cof" /M"HUB12_SPI.map" /W /x

HUB12_SPI.o : HUB12_SPI.ASM C:/Program\ Files/Microchip/MPASM\ Suite/P16F690.inc
	$(AS) /q /p16F690 "HUB12_SPI.ASM" /l"HUB12_SPI.lst" /e"HUB12_SPI.err" /d__DEBUG=1

clean : 
	$(CC) "HUB12_SPI.o" "HUB12_SPI.hex" "HUB12_SPI.err" "HUB12_SPI.lst" "HUB12_SPI.cof"

