//************************************************************************************
//**  
//**  File name:     C:\Users\BlueFlame17\Desktop\NICE2018\Program\EMRA.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Saturday, July 21, 2018 23:25:53
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 1
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F690
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_3
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portb
#define MX_SPI_1_MISO_TRIS trisb
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 7
#define MX_SPI_1_CLK_PORT portb
#define MX_SPI_1_CLK_TRIS trisb
#define MX_SPI_1_CLK_PIN 6
#define MX_SPI_1_SS_PORT portb
#define MX_SPI_1_SS_TRIS trisb
#define MX_UART_1
#define MX_UART_1_TX_PORT portb
#define MX_UART_1_TX_TRIS trisb
#define MX_UART_1_TX_PIN 7
#define MX_UART_1_RX_PORT portb
#define MX_UART_1_RX_TRIS trisb
#define MX_UART_1_RX_PIN 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portb
#define MX_I2C_1_SDA_TRIS trisb
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portb
#define MX_I2C_1_SCL_TRIS trisb
#define MX_I2C_1_SCL_PIN 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 5

//Functions
#define MX_CLK_SPEED 4000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x30f4
#endif
#ifdef HI_TECH_C
__CONFIG(0x30f4);
#endif

//Internal functions
#include "C:\Program Files\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_stored_values();
void FCM_display();
void FCM_clear();
void FCM_Value_OUT();
void FCM_lowbat_detect();
void FCM_int0();


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_UINT16 FCV_VOLTAGE = (0x0);
MX_BOOL FCV_DAT;
MX_BOOL FCV_SWITCH = (0);
MX_UINT8 FCV_EEPROM_VAL;
MX_UINT8 FCV_EEPROMREAD_ANALOG = (0x0);
MX_UINT8 FCV_TENS;
MX_UINT8 FCV_DIGIT;
MX_UINT8 FCV_COUNT = (0x0);
MX_BOOL FCV_FLAG = (0);
MX_UINT8 FCV_HUNDREDS;
MX_UINT8 FCV_ONES;
MX_UINT8 FCV_VALUE;
MX_UINT8 FCV_ANALOG2 = (0x0);
MX_UINT8 FCV_INIT = (0x0);
MX_UINT8 FCV_ANALOG = (0x0);

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;



//LED(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_1__LED_PORT		porta
#define LED_1__LED_TRIS		trisa
#define LED_1__LED_PIN		0
#define LED_1__LED_POLE		1




//LED(0): //Macro function declarations

void FCD_LED0_LEDOn();
void FCD_LED0_LEDOff();


//LED(1): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_2__LED_PORT		portc
#define LED_2__LED_TRIS		trisc
#define LED_2__LED_PIN		1
#define LED_2__LED_POLE		1




//LED(1): //Macro function declarations

void FCD_LED1_LEDOn();
void FCD_LED1_LEDOff();


//ADC(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Which ADC Channel
c = Acquisition time
d = Conversion Speed
e = VRef+ Option
f = VRef Voltage x 0.01V
******************************/

//Common Defines

#define ADC_3_MX_ADC_CHANNEL	4
#define ADC_3_MX_ADC_ACTIME	40
#define ADC_3_MX_ADC_CONVSP	3
#define ADC_3_MX_ADC_VREFOP	0
#define ADC_3_MX_ADC_VREFVOL	500

#ifndef MX_ADC_CHANNEL_4
 #define MX_ADC_CHANNEL_4			//Inform CAL ADC channel 4 is now in use.
#endif

#ifndef MX_ADC_REF					//Inform CAL ADC peripheral is now in use
 #define MX_ADC_REF
#endif

extern void FC_CAL_Enable_ADC (MX_UINT8 Channel, MX_UINT8 Conv_Speed, MX_UINT8 Vref, MX_UINT8 T_Charge);
extern MX_UINT16 FC_CAL_Sample_ADC (MX_UINT8 Sample_Mode);
extern void FC_CAL_Disable_ADC (void);




//ADC(0): //Macro function declarations

void FCD_ADC0_SampleADC();
MX_UINT8 FCD_ADC0_ReadAsByte();
MX_UINT16 FCD_ADC0_ReadAsInt();
MX_FLOAT FCD_ADC0_ReadAsVoltage();
void FCD_ADC0_ReadAsString(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE);
void FCD_ADC0_ADC_RAW_Configure_Channel();
MX_UINT8 FCD_ADC0_ADC_RAW_Sample_Channel_Byte();
MX_UINT16 FCD_ADC0_ADC_RAW_Sample_Channel_Int();
MX_UINT8 FCD_ADC0_ADC_RAW_Average_Channel_Byte(MX_UINT8 NumSamples, MX_UINT8 DelayUs);
MX_UINT16 FCD_ADC0_ADC_RAW_Average_Channel_Int(MX_UINT8 NumSamples, MX_UINT8 DelayUs);
void FCD_ADC0_ADC_RAW_Disable_Channel();



//LED(0): //Macro implementations


void FCD_LED0_LEDOn()
{
	
		#if( LED_1__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#endif

}

void FCD_LED0_LEDOff()
{
	
		#if( LED_1__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_1__LED_PORT	, LED_1__LED_TRIS , LED_1__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#endif

}



//LED(1): //Macro implementations


void FCD_LED1_LEDOn()
{
	
		#if( LED_2__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#endif

}

void FCD_LED1_LEDOff()
{
	
		#if( LED_2__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_2__LED_PORT	, LED_2__LED_TRIS , LED_2__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#endif

}



//ADC(0): //Macro implementations


void FCD_ADC0_SampleADC()
{
	
	    //unused

}

MX_UINT8 FCD_ADC0_ReadAsByte()
{
	
		MX_UINT8 retVal;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_3_MX_ADC_CHANNEL , ADC_3_MX_ADC_CONVSP , ADC_3_MX_ADC_VREFOP , ADC_3_MX_ADC_ACTIME );

		retVal = FC_CAL_Sample_ADC( 0 );				//Perform Sample - Return as byte

		FC_CAL_Disable_ADC ();

		return (retVal);

}

MX_UINT16 FCD_ADC0_ReadAsInt()
{
	
		MX_UINT16 retVal;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_3_MX_ADC_CHANNEL , ADC_3_MX_ADC_CONVSP , ADC_3_MX_ADC_VREFOP , ADC_3_MX_ADC_ACTIME );

		retVal = FC_CAL_Sample_ADC( 1 );				//Perform Sample - Return as MX_UINT16

		FC_CAL_Disable_ADC ();

		return (retVal);

}

MX_FLOAT FCD_ADC0_ReadAsVoltage()
{
	
		MX_UINT16 iSample;
		MX_FLOAT fSample, fVoltage, fVperDiv;

		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_3_MX_ADC_CHANNEL , ADC_3_MX_ADC_CONVSP , ADC_3_MX_ADC_VREFOP , ADC_3_MX_ADC_ACTIME );

	  #ifdef MX_ADC_BITS_8
		iSample = FC_CAL_Sample_ADC( 0 );								//Perform Sample - Return as byte
	  #else
		iSample = FC_CAL_Sample_ADC( 1 );								//Perform Sample - Return as MX_UINT16
	  #endif

	  	FC_CAL_Disable_ADC ();											//Switch off ADC peripheral
		fVoltage = flt_fromi( ADC_3_MX_ADC_VREFVOL );						//Convert reference voltage count to floating point (0 - 500 x 10mV)
		fVoltage = flt_mul(fVoltage, 0.01);								//Convert reference voltage count to actual voltage (0 - 5)

	  #ifdef MX_ADC_BITS_8
		fVperDiv = flt_mul(fVoltage, 0.00390625);						//Convert actual voltage to voltage per division (VRef / 256)
	  #endif
	  #ifdef MX_ADC_BITS_10
		fVperDiv = flt_mul(fVoltage, 0.000976);							//Convert actual voltage to voltage per division (VRef / 1024)
	  #endif
	  #ifdef MX_ADC_BITS_12
		fVperDiv = flt_mul(fVoltage, 0.00024414);						//Convert actual voltage to voltage per division (VRef / 4096)
	  #endif

		fSample = flt_fromi(iSample);									//Convert to floating point variable
		fVoltage = flt_mul(fSample, fVperDiv);							//Calculate floating point voltage

		return (fVoltage);

}

void FCD_ADC0_ReadAsString(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE)
{
	
		MX_FLOAT fVoltage;

		fVoltage = FCD_ADC0_ReadAsVoltage();
		FCI_FLOAT_TO_STRING(fVoltage, 2, FCR_RETVAL, FCR_RETVAL_SIZE);	//Convert to String

}

void FCD_ADC0_ADC_RAW_Configure_Channel()
{
	
		//Configure & Enable ADC Channel
		FC_CAL_Enable_ADC ( ADC_3_MX_ADC_CHANNEL , ADC_3_MX_ADC_CONVSP , ADC_3_MX_ADC_VREFOP , ADC_3_MX_ADC_ACTIME );

}

MX_UINT8 FCD_ADC0_ADC_RAW_Sample_Channel_Byte()
{
	
		return FC_CAL_Sample_ADC( 0 );									//Perform Sample - Return as byte

}

MX_UINT16 FCD_ADC0_ADC_RAW_Sample_Channel_Int()
{
	
		return FC_CAL_Sample_ADC( 1 );									//Perform Sample - Return as MX_UINT16

}

MX_UINT8 FCD_ADC0_ADC_RAW_Average_Channel_Byte(MX_UINT8 NumSamples, MX_UINT8 DelayUs)
{
	
		MX_UINT32 average = 0;
		MX_UINT8 count;

		for (count=0; count<NumSamples; count++)
		{
			average = average + FC_CAL_Sample_ADC( 0 );					//Perform Sample - Return as byte - add to average

			if (DelayUs)
				delay_us(DelayUs);										//If delay is not 0 then pause between samples
		}
		average = average / count;

		return (average & 0xFF);										//Return average as byte

}

MX_UINT16 FCD_ADC0_ADC_RAW_Average_Channel_Int(MX_UINT8 NumSamples, MX_UINT8 DelayUs)
{
	
		MX_UINT32 average = 0;
		MX_UINT8 count;

		for (count=0; count<NumSamples; count++)
		{
			average = average + FC_CAL_Sample_ADC( 1 );					//Perform Sample - Return as MX_UINT16 - add to average

			if (DelayUs)
				delay_us(DelayUs);										//If delay is not 0 then pause between samples
		}
		average = average / count;

		return (average & 0x1FFF);										//Return average as MX_SINT16

}

void FCD_ADC0_ADC_RAW_Disable_Channel()
{
	
		FC_CAL_Disable_ADC ();											//Disable ADC Channel

}

#include "C:\Program Files\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_stored_values()
{

	//Switch
	//Switch: DIGIT?
	switch (FCV_DIGIT)
	{
		case 1:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b10011111
			FCV_VALUE = 159;

			break;
		}
		case 2:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b00100100
			FCV_VALUE = 36;

			break;
		}
		case 3:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b00001101
			FCV_VALUE = 13;

			break;
		}
		case 4:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b10011001
			FCV_VALUE = 153;

			break;
		}
		case 5:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b01001001
			FCV_VALUE = 73;

			break;
		}
		case 6:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b01000001
			FCV_VALUE = 65;

			break;
		}
		case 7:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b00011111
			FCV_VALUE = 31;

			break;
		}
		case 8:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b00000001
			FCV_VALUE = 1;

			break;
		}
		case 9:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b00001001
			FCV_VALUE = 9;

			break;
		}
		case 0:
		{
			//Calculation
			//Calculation:
			//  VALUE = 0b00000011
			FCV_VALUE = 3;

			break;
		}
		// default:

	}

}


void FCM_display()
{

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP2=0; FCLV_LOOP2<8; FCLV_LOOP2++)
	{

		//Calculation
		//Calculation:
		//  DAT = VALUE AND 1
		//  VALUE = VALUE >> 1
		FCV_DAT = FCV_VALUE & 1;
		FCV_VALUE = FCV_VALUE >> 1;

		//DATA
		//Output: DAT -> C5
		trisc = trisc & 0xDF;
		if ((FCV_DAT))
			portc = (portc & 0xDF) | 0x20;
		else
			portc = portc & 0xDF;

		//CLK
		//Output: 0 -> C4
		trisc = trisc & 0xEF;
		if ((0))
			portc = (portc & 0xEF) | 0x10;
		else
			portc = portc & 0xEF;

		//Delay
		//Delay: 10 ms
		delay_ms(10);

		//CLK
		//Output: 1 -> C4
		trisc = trisc & 0xEF;
		if ((1))
			portc = (portc & 0xEF) | 0x10;
		else
			portc = portc & 0xEF;


	}

	//REG
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//Delay
	//Delay: 1 ms
	delay_ms(1);

	//REG
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

}


void FCM_clear()
{

	//Calculation
	//Calculation:
	//  VALUE = 0b11111111
	FCV_VALUE = 255;

	//Call Macro
	//Call Macro: display()
	FCM_display();

}


void FCM_Value_OUT()
{

	//CLK
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//REG
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//OE
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Output
	//Output: 0 -> A4
	trisa = trisa & 0xEF;
	if ((0))
		porta = (porta & 0xEF) | 0x10;
	else
		porta = porta & 0xEF;

	//Output
	//Output: 1 -> A5
	trisa = trisa & 0xDF;
	if ((1))
		porta = (porta & 0xDF) | 0x20;
	else
		porta = porta & 0xDF;

	//Call Macro
	//Call Macro: clear()
	FCM_clear();

	//Calculation
	//Calculation:
	//  HUNDREDS = COUNT / 100
	//  TENS = (COUNT / 10) MOD 10
	//  ONES = COUNT MOD 10
	FCV_HUNDREDS = FCV_COUNT / 100;
	FCV_TENS = (FCV_COUNT / 10) % 10;
	FCV_ONES = FCV_COUNT % 10;

	//Calculation
	//Calculation:
	//  DIGIT = HUNDREDS
	FCV_DIGIT = FCV_HUNDREDS;

	//Call Macro
	//Call Macro: stored_values()
	FCM_stored_values();

	//Call Macro
	//Call Macro: display()
	FCM_display();

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Calculation
	//Calculation:
	//  DIGIT = TENS
	FCV_DIGIT = FCV_TENS;

	//Call Macro
	//Call Macro: stored_values()
	FCM_stored_values();

	//Call Macro
	//Call Macro: display()
	FCM_display();

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Calculation
	//Calculation:
	//  DIGIT = ONES
	FCV_DIGIT = FCV_ONES;

	//Call Macro
	//Call Macro: stored_values()
	FCM_stored_values();

	//Call Macro
	//Call Macro: display()
	FCM_display();

	//Delay
	//Delay: 1 s
	delay_s(1);

}


void FCM_lowbat_detect()
{

	//Call Component Macro
	//Call Component Macro: analog=ReadAsByte()
	FCV_ANALOG = FCD_ADC0_ReadAsByte();

	//Calculation
	//Calculation:
	//  COUNT = analog
	FCV_COUNT = FCV_ANALOG;

	//Decision
	//Decision: analog < 152?
	if (FCV_ANALOG < 152)
	{

		//Call Component Macro
		//Call Component Macro: LEDOff()
		FCD_LED0_LEDOff();

		//Loop
		//Loop: While analog > 155
		while (!(FCV_ANALOG > 155))
		{

			//Call Component Macro
			//Call Component Macro: analog=ReadAsByte()
			FCV_ANALOG = FCD_ADC0_ReadAsByte();

			//Call Component Macro
			//Call Component Macro: LEDOn()
			FCD_LED1_LEDOn();

			//Delay
			//Delay: 400 ms
			delay_ms(255);
			delay_ms(145);

			//Call Component Macro
			//Call Component Macro: LEDOff()
			FCD_LED1_LEDOff();

			//Input
			//Input: A2 -> switch
			trisa = trisa | 0x04;
			FCV_SWITCH = ((porta & 0x04) == 0x04);

			//Calculation
			//Calculation:
			//  COUNT = analog
			FCV_COUNT = FCV_ANALOG;

			//Call Macro
			//Call Macro: Value_OUT()
			FCM_Value_OUT();


		}

	} else {

		//Call Component Macro
		//Call Component Macro: LEDOn()
		FCD_LED0_LEDOn();

		//Call Component Macro
		//Call Component Macro: LEDOff()
		FCD_LED1_LEDOff();

		//Call Macro
		//Call Macro: Value_OUT()
		FCM_Value_OUT();

	}

}


void FCM_int0()
{

}



void main()
{
	//Initialization
	ansel = 0;
anselh = 0;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Calculation
	//Calculation:
	//  digit = 2
	FCV_DIGIT = 2;

	//CLK
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//REG
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//OE
	//Output: 0 -> C2
	trisc = trisc & 0xFB;
	if ((0))
		portc = (portc & 0xFB) | 0x04;
	else
		portc = portc & 0xFB;

	//Output
	//Output: 0 -> A4
	trisa = trisa & 0xEF;
	if ((0))
		porta = (porta & 0xEF) | 0x10;
	else
		porta = porta & 0xEF;

	//Output
	//Output: 1 -> A5
	trisa = trisa & 0xDF;
	if ((1))
		porta = (porta & 0xDF) | 0x20;
	else
		porta = porta & 0xDF;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Call Macro
		//Call Macro: stored_values()
		FCM_stored_values();

		//Loop
		//Loop: Loop 8 times
		for (FCLV_LOOP1=0; FCLV_LOOP1<8; FCLV_LOOP1++)
		{

			//Calculation
			//Calculation:
			//  DAT = VALUE AND 1
			//  VALUE = VALUE >> 1
			FCV_DAT = FCV_VALUE & 1;
			FCV_VALUE = FCV_VALUE >> 1;

			//DATA
			//Output: DAT -> C5
			trisc = trisc & 0xDF;
			if ((FCV_DAT))
				portc = (portc & 0xDF) | 0x20;
			else
				portc = portc & 0xDF;

			//CLK
			//Output: 0 -> C4
			trisc = trisc & 0xEF;
			if ((0))
				portc = (portc & 0xEF) | 0x10;
			else
				portc = portc & 0xEF;

			//Delay
			//Delay: 10 ms
			delay_ms(10);

			//CLK
			//Output: 1 -> C4
			trisc = trisc & 0xEF;
			if ((1))
				portc = (portc & 0xEF) | 0x10;
			else
				portc = portc & 0xEF;


		}

		//REG
		//Output: 1 -> C3
		trisc = trisc & 0xF7;
		if ((1))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//Delay
		//Delay: 1 ms
		delay_ms(1);

		//REG
		//Output: 0 -> C3
		trisc = trisc & 0xF7;
		if ((0))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



