//************************************************************************************
//**  
//**  File name:     C:\Users\BlueFlame17\Desktop\NICE2018\Program\EMRA_test.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Sunday, July 22, 2018 02:08:41
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F690
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_3
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portb
#define MX_SPI_1_MISO_TRIS trisb
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 7
#define MX_SPI_1_CLK_PORT portb
#define MX_SPI_1_CLK_TRIS trisb
#define MX_SPI_1_CLK_PIN 6
#define MX_SPI_1_SS_PORT portb
#define MX_SPI_1_SS_TRIS trisb
#define MX_UART_1
#define MX_UART_1_TX_PORT portb
#define MX_UART_1_TX_TRIS trisb
#define MX_UART_1_TX_PIN 7
#define MX_UART_1_RX_PORT portb
#define MX_UART_1_RX_TRIS trisb
#define MX_UART_1_RX_PIN 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portb
#define MX_I2C_1_SDA_TRIS trisb
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portb
#define MX_I2C_1_SCL_TRIS trisb
#define MX_I2C_1_SCL_PIN 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 5

//Functions
#define MX_CLK_SPEED 4000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x30d4
#endif
#ifdef HI_TECH_C
__CONFIG(0x30d4);
#endif

//Internal functions
#include "C:\Program Files\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_stored_values();
void FCM_display();
void FCM_clear();
void FCM_show_analog_read();


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_UINT8 FCV_TENS;
MX_UINT8 FCV_DIGIT;
MX_UINT8 FCV_DATA;
MX_UINT8 FCV_ANALOG_READ;
MX_UINT8 FCV_ONES;
MX_UINT8 FCV_HUNDREDS;
MX_BOOL FCV_DATA_OUT;

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;


#include "C:\Program Files\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_stored_values()
{

	//Switch
	//Switch: digit?
	switch (FCV_DIGIT)
	{
		case 1:
		{
			//Calculation
			//Calculation:
			//  data = 0b10011111
			FCV_DATA = 159;

			break;
		}
		case 2:
		{
			//Calculation
			//Calculation:
			//  data = 0b00100100
			FCV_DATA = 36;

			break;
		}
		case 3:
		{
			//Calculation
			//Calculation:
			//  data = 0b00001101
			FCV_DATA = 13;

			break;
		}
		case 4:
		{
			//Calculation
			//Calculation:
			//  data = 0b10011001
			FCV_DATA = 153;

			break;
		}
		case 5:
		{
			//Calculation
			//Calculation:
			//  data = 0b01001001
			FCV_DATA = 73;

			break;
		}
		case 6:
		{
			//Calculation
			//Calculation:
			//  data = 0b01000001
			FCV_DATA = 65;

			break;
		}
		case 7:
		{
			//Calculation
			//Calculation:
			//  data = 0b00011111
			FCV_DATA = 31;

			break;
		}
		case 8:
		{
			//Calculation
			//Calculation:
			//  data = 0b00000001
			FCV_DATA = 1;

			break;
		}
		case 9:
		{
			//Calculation
			//Calculation:
			//  data = 0b00001001
			FCV_DATA = 9;

			break;
		}
		case 0:
		{
			//Calculation
			//Calculation:
			//  data = 0b00000011
			FCV_DATA = 3;

			break;
		}
		// default:

	}

}


void FCM_display()
{

	//Call Macro
	//Call Macro: stored_values()
	FCM_stored_values();

	//OE
	//Output: 0 -> C5
	trisc = trisc & 0xDF;
	if ((0))
		portc = (portc & 0xDF) | 0x20;
	else
		portc = portc & 0xDF;

	//CLK
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//REG
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP1=0; FCLV_LOOP1<8; FCLV_LOOP1++)
	{

		//Calculation
		//Calculation:
		//  data_out = data AND 1
		//  data = data >> 1
		FCV_DATA_OUT = FCV_DATA & 1;
		FCV_DATA = FCV_DATA >> 1;

		//DAT
		//Output: data_out -> C7
		trisc = trisc & 0x7F;
		if ((FCV_DATA_OUT))
			portc = (portc & 0x7F) | 0x80;
		else
			portc = portc & 0x7F;

		//CLK
		//Output: 0 -> C3
		trisc = trisc & 0xF7;
		if ((0))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//Delay
		//Delay: 100 us
		delay_us(100);

		//CLK
		//Output: 1 -> C3
		trisc = trisc & 0xF7;
		if ((1))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;


	}

	//REG
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Delay
	//Delay: 100 us
	delay_us(100);

	//REG
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

}


void FCM_clear()
{

	//Calculation
	//Calculation:
	//  data = 255
	FCV_DATA = 255;

	//OE
	//Output: 0 -> C5
	trisc = trisc & 0xDF;
	if ((0))
		portc = (portc & 0xDF) | 0x20;
	else
		portc = portc & 0xDF;

	//CLK
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//REG
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP2=0; FCLV_LOOP2<8; FCLV_LOOP2++)
	{

		//Calculation
		//Calculation:
		//  data_out = data AND 1
		//  data = data >> 1
		FCV_DATA_OUT = FCV_DATA & 1;
		FCV_DATA = FCV_DATA >> 1;

		//DAT
		//Output: data_out -> C7
		trisc = trisc & 0x7F;
		if ((FCV_DATA_OUT))
			portc = (portc & 0x7F) | 0x80;
		else
			portc = portc & 0x7F;

		//CLK
		//Output: 0 -> C3
		trisc = trisc & 0xF7;
		if ((0))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//Delay
		//Delay: 100 us
		delay_us(100);

		//CLK
		//Output: 1 -> C3
		trisc = trisc & 0xF7;
		if ((1))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;


	}

	//REG
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Delay
	//Delay: 100 us
	delay_us(100);

	//REG
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

}


void FCM_show_analog_read()
{

	//Output
	//Output: 0 -> A4
	trisa = trisa & 0xEF;
	if ((0))
		porta = (porta & 0xEF) | 0x10;
	else
		porta = porta & 0xEF;

	//Output
	//Output: 1 -> A5
	trisa = trisa & 0xDF;
	if ((1))
		porta = (porta & 0xDF) | 0x20;
	else
		porta = porta & 0xDF;

	//Calculation
	//Calculation:
	//  hundreds = analog_read / 100
	//  tens = (analog_read MOD 100) / 10
	//  ones = analog_read MOD 10
	FCV_HUNDREDS = FCV_ANALOG_READ / 100;
	FCV_TENS = (FCV_ANALOG_READ % 100) / 10;
	FCV_ONES = FCV_ANALOG_READ % 10;

	//Calculation
	//Calculation:
	//  digit = hundreds
	FCV_DIGIT = FCV_HUNDREDS;

	//Call Macro
	//Call Macro: display()
	FCM_display();

	//Delay
	//Delay: 400 ms
	delay_ms(255);
	delay_ms(145);

	//Calculation
	//Calculation:
	//  digit = tens
	FCV_DIGIT = FCV_TENS;

	//Call Macro
	//Call Macro: display()
	FCM_display();

	//Delay
	//Delay: 400 ms
	delay_ms(255);
	delay_ms(145);

	//Calculation
	//Calculation:
	//  digit = ones
	FCV_DIGIT = FCV_ONES;

	//Call Macro
	//Call Macro: display()
	FCM_display();

	//Delay
	//Delay: 400 ms
	delay_ms(255);
	delay_ms(145);

	//Call Macro
	//Call Macro: clear()
	FCM_clear();

}



void main()
{
	//Initialization
	ansel = 0;
anselh = 0;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Loop
	//Loop: While 1
	while (1)
	{

		//Output
		//Output: 1 -> C5
		trisc = trisc & 0xDF;
		if ((1))
			portc = (portc & 0xDF) | 0x20;
		else
			portc = portc & 0xDF;

		//Delay
		//Delay: 10 us
		delay_us(10);

		//Output
		//Output: 0 -> C5
		trisc = trisc & 0xDF;
		if ((0))
			portc = (portc & 0xDF) | 0x20;
		else
			portc = portc & 0xDF;

		//Delay
		//Delay: 10 us
		delay_us(10);


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



