//************************************************************************************
//**  
//**  File name:     D:\KennyNeutronsInnovations\NICE2018\Program\EMRA_FINAL.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Wednesday, February 20, 2019 21:17:51
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F688
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_3
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_SIZE 256
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 4
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 5

//Functions
#define MX_CLK_SPEED 4000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x33f4
#endif
#ifdef HI_TECH_C
__CONFIG(0x33f4);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_int();
void FCM_Switch_Check();
void FCM_repel();


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_BOOL FCV_SWITCH;
MX_UINT8 FCV_COUNTER = (0x0);
MX_BOOL FCV_FLAG;
MX_UINT8 FCV_NOTIF = (0x0);
MX_BOOL FCV_VC;

MX_UINT8 FCLV_LOOP1;



//LED(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_1__LED_PORT		portc
#define LED_1__LED_TRIS		trisc
#define LED_1__LED_PIN		5
#define LED_1__LED_POLE		0




//LED(0): //Macro function declarations

void FCD_LED0_LEDOn();
void FCD_LED0_LEDOff();


//LED(1): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_2__LED_PORT		portc
#define LED_2__LED_TRIS		trisc
#define LED_2__LED_PIN		4
#define LED_2__LED_POLE		0




//LED(1): //Macro function declarations

void FCD_LED1_LEDOn();
void FCD_LED1_LEDOff();



//LED(0): //Macro implementations


void FCD_LED0_LEDOn()
{
	
		#if( LED_1__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#endif

}

void FCD_LED0_LEDOff()
{
	
		#if( LED_1__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_1__LED_PORT	, LED_1__LED_TRIS , LED_1__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#endif

}



//LED(1): //Macro implementations


void FCD_LED1_LEDOn()
{
	
		#if( LED_2__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#endif

}

void FCD_LED1_LEDOff()
{
	
		#if( LED_2__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_2__LED_PORT	, LED_2__LED_TRIS , LED_2__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#endif

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_int()
{

}


void FCM_Switch_Check()
{

	//Loop
	//Loop: While switch = 1
	while (!(FCV_SWITCH == 1))
	{

		//Input
		//Input: A2 -> switch
		trisa = trisa | 0x04;
		FCV_SWITCH = ((porta & 0x04) == 0x04);


	}

}


void FCM_repel()
{

	//Output
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//Delay
	//Delay: 3 us
	delay_us(3);

	//Output
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//Delay
	//Delay: 3 us
	delay_us(3);

}



void main()
{
	//Initialization
	ansel = 0x00;
cmcon0 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Connection Point
	//Connection Point: [A]: A
FCC_Main_A:
;

	//Interrupt
	//Interrupt: Enable RB0INT
	st_bit(option_reg,INTEDG);
	st_bit(intcon,GIE);
	st_bit(intcon, INTE);

	//Delay
	//Delay: 100 ms
	delay_ms(100);

	//C Code
	//C Code:
	/*
	  Enter C code below this comment
	*/
	sleep();

	//Call Macro
	//Call Macro: Switch_Check()
	FCM_Switch_Check();

	//Calculation
	//Calculation:
	//  switch = 1
	//  flag = 0
	FCV_SWITCH = 1;
	FCV_FLAG = 0;

	//Calculation
	//Calculation:
	//  counter = 0
	//  notif = 0
	FCV_COUNTER = 0;
	FCV_NOTIF = 0;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Output
		//Output: 0 -> C1
		trisc = trisc & 0xFD;
		if ((0))
			portc = (portc & 0xFD) | 0x02;
		else
			portc = portc & 0xFD;

		//Output
		//Output: 1 -> C2
		trisc = trisc & 0xFB;
		if ((1))
			portc = (portc & 0xFB) | 0x04;
		else
			portc = portc & 0xFB;

		//Input
		//Input: A2 -> switch
		trisa = trisa | 0x04;
		FCV_SWITCH = ((porta & 0x04) == 0x04);

		//Decision
		//Decision: switch = 0?
		if (FCV_SWITCH == 0)
		{

			//Call Component Macro
			//Call Component Macro: LEDOn()
			FCD_LED1_LEDOn();

			//Delay
			//Delay: 2 s
			delay_s(2);

			//Input
			//Input: A2 -> switch
			trisa = trisa | 0x04;
			FCV_SWITCH = ((porta & 0x04) == 0x04);

			//Decision
			//Decision: switch = 0?
			if (FCV_SWITCH == 0)
			{

				//Call Component Macro
				//Call Component Macro: LEDOn()
				FCD_LED0_LEDOn();

				//Delay
				//Delay: 1 s
				delay_s(1);

				//Call Component Macro
				//Call Component Macro: LEDOff()
				FCD_LED0_LEDOff();

				//Call Component Macro
				//Call Component Macro: LEDOff()
				FCD_LED1_LEDOff();

				//Call Macro
				//Call Macro: Switch_Check()
				FCM_Switch_Check();

				//Interrupt
				//Interrupt: Enable RB0INT
				st_bit(option_reg,INTEDG);
				st_bit(intcon,GIE);
				st_bit(intcon, INTE);

				//Delay
				//Delay: 3 s
				delay_s(3);

				//Call Component Macro
				//Call Component Macro: LEDOn()
				FCD_LED0_LEDOn();

				//Delay
				//Delay: 100 ms
				delay_ms(100);

				//Call Component Macro
				//Call Component Macro: LEDOff()
				FCD_LED0_LEDOff();

				//C Code
				//C Code:
				/*
				  Enter C code below this comment
				*/
				sleep();

				//Loop
				//Loop: Loop 10 times
				for (FCLV_LOOP1=0; FCLV_LOOP1<10; FCLV_LOOP1++)
				{

					//Call Component Macro
					//Call Component Macro: LEDOn()
					FCD_LED1_LEDOn();

					//Delay
					//Delay: 100 ms
					delay_ms(100);

					//Call Component Macro
					//Call Component Macro: LEDOff()
					FCD_LED1_LEDOff();

					//Delay
					//Delay: 100 ms
					delay_ms(100);


				}

				//Call Macro
				//Call Macro: Switch_Check()
				FCM_Switch_Check();

				//Calculation
				//Calculation:
				//  counter = 0
				//  notif = 0
				FCV_COUNTER = 0;
				FCV_NOTIF = 0;

			} else {

				//Call Component Macro
				//Call Component Macro: LEDOff()
				FCD_LED1_LEDOff();

			}

		} else {

			//Interrupt
			//Interrupt: Disable RB0INT
			cr_bit(intcon, INTE);

			//Loop
			//Loop: While switch = 0
			while (!(FCV_SWITCH == 0))
			{

				//Call Macro
				//Call Macro: repel()
				FCM_repel();

				//Input
				//Input: A2 -> switch
				trisa = trisa | 0x04;
				FCV_SWITCH = ((porta & 0x04) == 0x04);


			}

		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
	//Handler code for [RB0INT]
	#ifndef MX_INTHANDLER_intcon_INTF
	#define MX_INTHANDLER_intcon_INTF
	if (ts_bit(intcon, INTF) && ts_bit(intcon, INTE))
	{
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 1;
		#endif	
		FCM_int();
		cr_bit(intcon, INTF);
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 0;
		#endif	
	}
	#else
	#warning "This interrupt has previously been enabled, so the macro <int> may never get called."
	#endif


	//Handler code for [RB0INT]
	#ifndef MX_INTHANDLER_intcon_INTF
	#define MX_INTHANDLER_intcon_INTF
	if (ts_bit(intcon, INTF) && ts_bit(intcon, INTE))
	{
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 1;
		#endif	
		FCM_int();
		cr_bit(intcon, INTF);
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 0;
		#endif	
	}
	#else
	#warning "This interrupt has previously been enabled, so the macro <int> may never get called."
	#endif


}



