//************************************************************************************
//**  
//**  File name:     C:\Users\BlueFlame17\Desktop\NICE2018\Program\Test20180723.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Tuesday, July 31, 2018 02:33:47
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F690
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_3
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portb
#define MX_SPI_1_MISO_TRIS trisb
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 7
#define MX_SPI_1_CLK_PORT portb
#define MX_SPI_1_CLK_TRIS trisb
#define MX_SPI_1_CLK_PIN 6
#define MX_SPI_1_SS_PORT portb
#define MX_SPI_1_SS_TRIS trisb
#define MX_UART_1
#define MX_UART_1_TX_PORT portb
#define MX_UART_1_TX_TRIS trisb
#define MX_UART_1_TX_PIN 7
#define MX_UART_1_RX_PORT portb
#define MX_UART_1_RX_TRIS trisb
#define MX_UART_1_RX_PIN 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portb
#define MX_I2C_1_SDA_TRIS trisb
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portb
#define MX_I2C_1_SCL_TRIS trisb
#define MX_I2C_1_SCL_PIN 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 5

//Functions
#define MX_CLK_SPEED 4000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x33f4
#endif
#ifdef HI_TECH_C
__CONFIG(0x33f4);
#endif

//Internal functions
#include "C:\Program Files\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_int();
void FCM_Switch_Check();
void FCM_repel();


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_BOOL FCV_SWITCH;
MX_UINT8 FCV_COUNTER = (0x0);
MX_BOOL FCV_FLAG;
MX_UINT8 FCV_NOTIF = (0x0);
MX_BOOL FCV_VC = (0);

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;



//LED(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_1__LED_PORT		portc
#define LED_1__LED_TRIS		trisc
#define LED_1__LED_PIN		5
#define LED_1__LED_POLE		1




//LED(0): //Macro function declarations

void FCD_LED0_LEDOn();
void FCD_LED0_LEDOff();


//LED(1): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_2__LED_PORT		portc
#define LED_2__LED_TRIS		trisc
#define LED_2__LED_PIN		4
#define LED_2__LED_POLE		1




//LED(1): //Macro function declarations

void FCD_LED1_LEDOn();
void FCD_LED1_LEDOff();



//LED(0): //Macro implementations


void FCD_LED0_LEDOn()
{
	
		#if( LED_1__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#endif

}

void FCD_LED0_LEDOff()
{
	
		#if( LED_1__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_1__LED_PORT	, LED_1__LED_TRIS , LED_1__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_1__LED_PORT , LED_1__LED_TRIS , LED_1__LED_PIN );
		#endif

}



//LED(1): //Macro implementations


void FCD_LED1_LEDOn()
{
	
		#if( LED_2__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#endif

}

void FCD_LED1_LEDOff()
{
	
		#if( LED_2__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_2__LED_PORT	, LED_2__LED_TRIS , LED_2__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#endif

}

#include "C:\Program Files\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_int()
{

}


void FCM_Switch_Check()
{

	//Loop
	//Loop: While switch = 1
	while (!(FCV_SWITCH == 1))
	{

		//Input
		//Input: A2 -> switch
		trisa = trisa | 0x04;
		FCV_SWITCH = ((porta & 0x04) == 0x04);


	}

}


void FCM_repel()
{

	//Output
	//Output: 1 -> C5
	trisc = trisc & 0xDF;
	if ((1))
		portc = (portc & 0xDF) | 0x20;
	else
		portc = portc & 0xDF;

	//Delay
	//Delay: 15 us
	delay_us(15);

	//Output
	//Output: 0 -> C5
	trisc = trisc & 0xDF;
	if ((0))
		portc = (portc & 0xDF) | 0x20;
	else
		portc = portc & 0xDF;

	//Delay
	//Delay: 15 us
	delay_us(15);

}



void main()
{
	//Initialization
	ansel = 0;
anselh = 0;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Connection Point
	//Connection Point: [A]: A
FCC_Main_A:
;

	//Interrupt
	//Interrupt: Enable GP2INT
	st_bit(option_reg,INTEDG);
	st_bit(intcon,GIE);
	st_bit(intcon, INTE);

	//Delay
	//Delay: 100 ms
	delay_ms(100);

	//C Code
	//C Code:
	/*
	  Enter C code below this comment
	*/
	sleep();

	//Call Macro
	//Call Macro: Switch_Check()
	FCM_Switch_Check();

	//Calculation
	//Calculation:
	//  switch = 1
	//  flag = 0
	FCV_SWITCH = 1;
	FCV_FLAG = 0;

	//Calculation
	//Calculation:
	//  counter = 0
	//  notif = 0
	FCV_COUNTER = 0;
	FCV_NOTIF = 0;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Decision
		//Decision: flag = 0?
		if (FCV_FLAG == 0)
		{

			//Connection Point
			//Connection Point: [B]: B
FCC_Main_B:
;

			//Loop
			//Loop: Loop 5 times
			for (FCLV_LOOP2=0; FCLV_LOOP2<5; FCLV_LOOP2++)
			{

				//Call Component Macro
				//Call Component Macro: LEDOn()
				FCD_LED0_LEDOn();

				//Call Component Macro
				//Call Component Macro: LEDOff()
				FCD_LED1_LEDOff();

				//Delay
				//Delay: 300 ms
				delay_ms(255);
				delay_ms(45);

				//Call Component Macro
				//Call Component Macro: LEDOff()
				FCD_LED0_LEDOff();

				//Delay
				//Delay: 300 ms
				delay_ms(255);
				delay_ms(45);


			}

			//Interrupt
			//Interrupt: Enable GP2INT
			st_bit(option_reg,INTEDG);
			st_bit(intcon,GIE);
			st_bit(intcon, INTE);

			//C Code
			//C Code:
			/*
			  Enter C code below this comment
			*/
			sleep();

			//Call Component Macro
			//Call Component Macro: LEDOn()
			FCD_LED0_LEDOn();

			//Delay
			//Delay: 1 s
			delay_s(1);

			//Input
			//Input: A2 -> switch
			trisa = trisa | 0x04;
			FCV_SWITCH = ((porta & 0x04) == 0x04);

			//Decision
			//Decision: switch = 0?
			if (FCV_SWITCH == 0)
			{

				//Loop
				//Loop: Loop 15 times
				for (FCLV_LOOP3=0; FCLV_LOOP3<15; FCLV_LOOP3++)
				{

					//Loop
					//Loop: While switch = 0
					while (FCV_SWITCH == 0)
					{

						//Input
						//Input: A2 -> switch
						trisa = trisa | 0x04;
						FCV_SWITCH = ((porta & 0x04) == 0x04);

						//Input
						//Input: B6 -> VC
						trisb = trisb | 0x40;
						FCV_VC = ((portb & 0x40) == 0x40);

						//Decision
						//Decision: VC = 1?
						if (FCV_VC == 1)
						{

							//Call Component Macro
							//Call Component Macro: LEDOn()
							FCD_LED0_LEDOn();

							//Call Component Macro
							//Call Component Macro: LEDOn()
							FCD_LED1_LEDOn();

							//Call Macro
							//Call Macro: Switch_Check()
							FCM_Switch_Check();

							//Delay
							//Delay: 1 ms
							delay_ms(1);

							//Call Component Macro
							//Call Component Macro: LEDOff()
							FCD_LED0_LEDOff();

							//Call Component Macro
							//Call Component Macro: LEDOff()
							FCD_LED1_LEDOff();

							//Goto Connection Point
							//Goto Connection Point: [C]: C
							goto FCC_Main_C;

						// } else {

						}

						//Call Component Macro
						//Call Component Macro: LEDOff()
						FCD_LED0_LEDOff();

						//Call Component Macro
						//Call Component Macro: LEDOn()
						FCD_LED1_LEDOn();

						//Delay
						//Delay: 200 ms
						delay_ms(200);

						//Call Component Macro
						//Call Component Macro: LEDOn()
						FCD_LED0_LEDOn();

						//Call Component Macro
						//Call Component Macro: LEDOff()
						FCD_LED1_LEDOff();

						//Delay
						//Delay: 200 ms
						delay_ms(200);


					}


				}

				//Goto Connection Point
				//Goto Connection Point: [B]: B
				goto FCC_Main_B;

				//Connection Point
				//Connection Point: [C]: C
FCC_Main_C:
;

				//Loop
				//Loop: Loop 10 times
				for (FCLV_LOOP4=0; FCLV_LOOP4<10; FCLV_LOOP4++)
				{

					//Call Component Macro
					//Call Component Macro: LEDOn()
					FCD_LED0_LEDOn();

					//Call Component Macro
					//Call Component Macro: LEDOff()
					FCD_LED1_LEDOff();

					//Delay
					//Delay: 100 ms
					delay_ms(100);

					//Call Component Macro
					//Call Component Macro: LEDOff()
					FCD_LED0_LEDOff();

					//Call Component Macro
					//Call Component Macro: LEDOn()
					FCD_LED1_LEDOn();

					//Delay
					//Delay: 100 ms
					delay_ms(100);


				}

				//Call Component Macro
				//Call Component Macro: LEDOn()
				FCD_LED0_LEDOn();

				//Call Component Macro
				//Call Component Macro: LEDOn()
				FCD_LED1_LEDOn();

				//Delay
				//Delay: 1 s
				delay_s(1);

				//Call Component Macro
				//Call Component Macro: LEDOff()
				FCD_LED0_LEDOff();

				//Call Component Macro
				//Call Component Macro: LEDOff()
				FCD_LED1_LEDOff();

				//Interrupt
				//Interrupt: Enable GP2INT
				st_bit(option_reg,INTEDG);
				st_bit(intcon,GIE);
				st_bit(intcon, INTE);

				//C Code
				//C Code:
				/*
				  Enter C code below this comment
				*/
				sleep();

				//Input
				//Input: B6 -> VC
				trisb = trisb | 0x40;
				FCV_VC = ((portb & 0x40) == 0x40);

				//Decision
				//Decision: VC = 1?
				if (FCV_VC == 1)
				{

					//Goto Connection Point
					//Goto Connection Point: [C]: C
					goto FCC_Main_C;

				} else {

					//Calculation
					//Calculation:
					//  flag = 1
					FCV_FLAG = 1;

					//Call Component Macro
					//Call Component Macro: LEDOn()
					FCD_LED1_LEDOn();

					//Delay
					//Delay: 2 s
					delay_s(2);

					//Call Macro
					//Call Macro: Switch_Check()
					FCM_Switch_Check();

					//Call Component Macro
					//Call Component Macro: LEDOff()
					FCD_LED1_LEDOff();

					//Calculation
					//Calculation:
					//  counter = 0
					//  notif = 0
					FCV_COUNTER = 0;
					FCV_NOTIF = 0;

				}

			} else {

				//Goto Connection Point
				//Goto Connection Point: [B]: B
				goto FCC_Main_B;

			}

		} else {

			//Input
			//Input: B6 -> VC
			trisb = trisb | 0x40;
			FCV_VC = ((portb & 0x40) == 0x40);

			//Decision
			//Decision: VC = 1?
			if (FCV_VC == 1)
			{

				//Goto Connection Point
				//Goto Connection Point: [C]: C
				goto FCC_Main_C;

			} else {

				//Input
				//Input: A2 -> switch
				trisa = trisa | 0x04;
				FCV_SWITCH = ((porta & 0x04) == 0x04);

				//Decision
				//Decision: switch = 0?
				if (FCV_SWITCH == 0)
				{

					//Call Component Macro
					//Call Component Macro: LEDOn()
					FCD_LED1_LEDOn();

					//Delay
					//Delay: 2 s
					delay_s(2);

					//Input
					//Input: A2 -> switch
					trisa = trisa | 0x04;
					FCV_SWITCH = ((porta & 0x04) == 0x04);

					//Decision
					//Decision: switch = 0?
					if (FCV_SWITCH == 0)
					{

						//Call Component Macro
						//Call Component Macro: LEDOn()
						FCD_LED0_LEDOn();

						//Delay
						//Delay: 1 s
						delay_s(1);

						//Call Component Macro
						//Call Component Macro: LEDOff()
						FCD_LED0_LEDOff();

						//Call Component Macro
						//Call Component Macro: LEDOff()
						FCD_LED1_LEDOff();

						//Call Macro
						//Call Macro: Switch_Check()
						FCM_Switch_Check();

						//Interrupt
						//Interrupt: Enable GP2INT
						st_bit(option_reg,INTEDG);
						st_bit(intcon,GIE);
						st_bit(intcon, INTE);

						//Delay
						//Delay: 3 s
						delay_s(3);

						//Call Component Macro
						//Call Component Macro: LEDOn()
						FCD_LED0_LEDOn();

						//Delay
						//Delay: 100 ms
						delay_ms(100);

						//Call Component Macro
						//Call Component Macro: LEDOff()
						FCD_LED0_LEDOff();

						//C Code
						//C Code:
						/*
						  Enter C code below this comment
						*/
						sleep();

						//Loop
						//Loop: Loop 10 times
						for (FCLV_LOOP1=0; FCLV_LOOP1<10; FCLV_LOOP1++)
						{

							//Call Component Macro
							//Call Component Macro: LEDOn()
							FCD_LED1_LEDOn();

							//Delay
							//Delay: 100 ms
							delay_ms(100);

							//Call Component Macro
							//Call Component Macro: LEDOff()
							FCD_LED1_LEDOff();

							//Delay
							//Delay: 100 ms
							delay_ms(100);


						}

						//Call Macro
						//Call Macro: Switch_Check()
						FCM_Switch_Check();

						//Calculation
						//Calculation:
						//  counter = 0
						//  notif = 0
						FCV_COUNTER = 0;
						FCV_NOTIF = 0;

					} else {

						//Call Component Macro
						//Call Component Macro: LEDOff()
						FCD_LED1_LEDOff();

					}

				} else {

					//Interrupt
					//Interrupt: Disable GP2INT
					cr_bit(intcon, INTE);

					//Loop
					//Loop: While switch = 0
					while (!(FCV_SWITCH == 0))
					{

						//Call Macro
						//Call Macro: repel()
						FCM_repel();

						//Input
						//Input: A2 -> switch
						trisa = trisa | 0x04;
						FCV_SWITCH = ((porta & 0x04) == 0x04);


					}

				}

			}

		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
	//Handler code for [GP2INT]
	#ifndef MX_INTHANDLER_intcon_INTF
	#define MX_INTHANDLER_intcon_INTF
	if (ts_bit(intcon, INTF) && ts_bit(intcon, INTE))
	{
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 1;
		#endif	
		FCM_int();
		cr_bit(intcon, INTF);
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 0;
		#endif	
	}
	#else
	#warning "This interrupt has previously been enabled, so the macro <int> may never get called."
	#endif


	//Handler code for [GP2INT]
	#ifndef MX_INTHANDLER_intcon_INTF
	#define MX_INTHANDLER_intcon_INTF
	if (ts_bit(intcon, INTF) && ts_bit(intcon, INTE))
	{
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 1;
		#endif	
		FCM_int();
		cr_bit(intcon, INTF);
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 0;
		#endif	
	}
	#else
	#warning "This interrupt has previously been enabled, so the macro <int> may never get called."
	#endif


	//Handler code for [GP2INT]
	#ifndef MX_INTHANDLER_intcon_INTF
	#define MX_INTHANDLER_intcon_INTF
	if (ts_bit(intcon, INTF) && ts_bit(intcon, INTE))
	{
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 1;
		#endif	
		FCM_int();
		cr_bit(intcon, INTF);
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 0;
		#endif	
	}
	#else
	#warning "This interrupt has previously been enabled, so the macro <int> may never get called."
	#endif


	//Handler code for [GP2INT]
	#ifndef MX_INTHANDLER_intcon_INTF
	#define MX_INTHANDLER_intcon_INTF
	if (ts_bit(intcon, INTF) && ts_bit(intcon, INTE))
	{
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 1;
		#endif	
		FCM_int();
		cr_bit(intcon, INTF);
		#ifdef USE_FLOWCODE_ICD
			extern char ICD_Interrupt_Enable = 0;
		#endif	
	}
	#else
	#warning "This interrupt has previously been enabled, so the macro <int> may never get called."
	#endif


}



