# MPLAB IDE generated this makefile for use with GNU make.
# Project: nrf24l01_gyro.mcp
# Date: Sat Sep 05 17:41:11 2020

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

nrf24l01_gyro.cof : nrf24l01_gyro.o
	$(CC) /p16F690 "nrf24l01_gyro.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"nrf24l01_gyro.cof" /M"nrf24l01_gyro.map" /W /x

nrf24l01_gyro.o : nrf24l01_gyro.asm ../../../../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F690.INC
	$(AS) /q /p16F690 "nrf24l01_gyro.asm" /l"nrf24l01_gyro.lst" /e"nrf24l01_gyro.err" /d__DEBUG=1 /c-

clean : 
	$(CC) "nrf24l01_gyro.o" "nrf24l01_gyro.hex" "nrf24l01_gyro.err" "nrf24l01_gyro.lst" "nrf24l01_gyro.cof"

