# MPLAB IDE generated this makefile for use with GNU make.
# Project: HUB6TEST0.mcp
# Date: Tue Sep 10 14:04:41 2019

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

HUBTEST0.cof : HUBTEST0.o
	$(CC) /p16F690 "HUBTEST0.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"HUBTEST0.cof" /M"HUBTEST0.map" /W /x

HUBTEST0.o : HUBTEST0.ASM ../../../../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F690.INC
	$(AS) /q /p16F690 "HUBTEST0.ASM" /l"HUBTEST0.lst" /e"HUBTEST0.err" /d__DEBUG=1

clean : 
	$(CC) "HUBTEST0.o" "HUBTEST0.hex" "HUBTEST0.err" "HUBTEST0.lst" "HUBTEST0.cof"

