//************************************************************************************
//**  
//**  File name:     C:\Users\gerpe\OneDrive\GER-PER 2016\Documents\KennyNeutron\dotHex\I2C\I2C.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Tuesday, December 17, 2019 15:39:07
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F873A
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_1
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 128
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 2000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x3f3a
#endif
#ifdef HI_TECH_C
__CONFIG(0x3f3a);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_IIC_START();
void FCM_IIC_STOP();
void FCM_IIC_CLKP();
void FCM_IIC_WRITEID_W();
void FCM_IIC_SACK();


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_UINT8 FCV_RETURN = (0x1);
MX_BOOL FCV_ACK;




//LCDDisplay(0): //Defines:

/**** Macro Substitutions ****
a = Unique Component Reference Number
b = D1 Port Letter
c = D2 Port Letter
d = D3 Port Letter
e = D4 Port Letter
f = RS Port Letter
g = E Port Letter
h = Data 1_Pin
i = Data 2 Pin
j = Data 3 Pin
k = Data 4 Pin
l = RS Pin
m = Enable Pin
n = Row Count
o = Column Count
******************************/

	//component connections
	#define LCD_1__PORT0    portc
	#define LCD_1__PORT1    portb
	#define LCD_1__PORT2    portb
	#define LCD_1__PORT3    portc
	#define LCD_1__PORT4    portc
	#define LCD_1__PORT5    portc
	#define LCD_1__TRIS0    trisc
	#define LCD_1__TRIS1    trisb
	#define LCD_1__TRIS2    trisb
	#define LCD_1__TRIS3    trisc
	#define LCD_1__TRIS4    trisc
	#define LCD_1__TRIS5    trisc
	#define LCD_1__BIT0    	2
	#define LCD_1__BIT1    	3
	#define LCD_1__BIT2    	4
	#define LCD_1__BIT3    	5
	#define LCD_1__RS      	0
	#define LCD_1__E       	1
	#define LCD_1__ROWCNT	4
	#define LCD_1__COLCNT	20

	#ifdef _BOOSTC
	  #define LCD_1__DELAY   delay_10us(10)
	#endif
	#ifdef _C2C_
	  #define LCD_1__DELAY   delay_us(100)
	#endif
	#ifdef HI_TECH_C
	  #define LCD_1__DELAY   __delay_us(120)
	#endif
	#ifndef LCD_1__DELAY
	  #define LCD_1__DELAY   delay_us(100)
	#endif




//LCDDisplay(0): //Macro function declarations

void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask);
void FCD_LCDDisplay0_Start();
void FCD_LCDDisplay0_Clear();
void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character);
void FCD_LCDDisplay0_Command(MX_UINT8 in);
void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y);
void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number);
void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String);
void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions);
void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line);
void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7);


//I2C_Master(0): //Defines:

/**** Macro Substitutions ****
a = Unique component ID
b = I2C Channel - 0=SW, 1-4=HW
c = Baud Rate
d = SM BUS Enable 0/2
e = Slew Rate Enable 0/1
f = Bitbanged Data Port Letter
g = Bitbanged Data Pin
h = Bitbanged Clock Port Letter
i = Bitbanged Clock Pin
******************************/

//BMODE
//Bit 0 - Slew Control
//Bit 1 - SMBus Control

//Definitions for I2C slot allocation
#ifndef	MX_I2C_REF1
	#define MX_I2C_REF1
	#define I2CMASTER_2_MX_I2C_UREF			1
	#define MX_I2C_CHANNEL_1		0
	#define MX_I2C_SDA_PIN_1		4
	#define MX_I2C_SDA_PORT_1		portc
	#define MX_I2C_SDA_TRIS_1		trisc
	#define MX_I2C_SCL_PIN_1		3
	#define MX_I2C_SCL_PORT_1		portc
	#define MX_I2C_SCL_TRIS_1		trisc
	#define MX_I2C_BMODE_1			1 | 0
	#define MX_I2C_BAUD_1			100000
	#define MX_I2C_INT_1			0
#else
 #ifndef MX_I2C_REF2
	#define MX_I2C_REF2
	#define I2CMASTER_2_MX_I2C_UREF			2
	#define MX_I2C_CHANNEL_2		0
	#define MX_I2C_SDA_PIN_2		4
	#define MX_I2C_SDA_PORT_2		portc
	#define MX_I2C_SDA_TRIS_2		trisc
	#define MX_I2C_SCL_PIN_2		3
	#define MX_I2C_SCL_PORT_2		portc
	#define MX_I2C_SCL_TRIS_2		trisc
	#define MX_I2C_BMODE_2			1 | 0
	#define MX_I2C_BAUD_2			100000
	#define MX_I2C_INT_2			0
 #else
  #ifndef MX_I2C_REF3
	#define MX_I2C_REF3
	#define I2CMASTER_2_MX_I2C_UREF			3
	#define MX_I2C_CHANNEL_3		0
	#define MX_I2C_SDA_PIN_3		4
	#define MX_I2C_SDA_PORT_3		portc
	#define MX_I2C_SDA_TRIS_3		trisc
	#define MX_I2C_SCL_PIN_3		3
	#define MX_I2C_SCL_PORT_3		portc
	#define MX_I2C_SCL_TRIS_3		trisc
	#define MX_I2C_BMODE_3			1 | 0
	#define MX_I2C_BAUD_3			100000
	#define MX_I2C_INT_3			0
  #else
   #ifndef MX_I2C_REF4
	#define MX_I2C_REF4
	#define I2CMASTER_2_MX_I2C_UREF			4
	#define MX_I2C_CHANNEL_4		0
	#define MX_I2C_SDA_PIN_4		4
	#define MX_I2C_SDA_PORT_4		portc
	#define MX_I2C_SDA_TRIS_4		trisc
	#define MX_I2C_SCL_PIN_4		3
	#define MX_I2C_SCL_PORT_4		portc
	#define MX_I2C_SCL_TRIS_4		trisc
	#define MX_I2C_BMODE_4			1 | 0
	#define MX_I2C_BAUD_4			100000
	#define MX_I2C_INT_4			0
   #endif
  #endif
 #endif
#endif

#define I2CMASTER_2_I2C_Master_Init		CAL_APPEND(FC_CAL_I2C_Master_Init_, I2CMASTER_2_MX_I2C_UREF)
#define I2CMASTER_2_I2C_Master_Uninit	CAL_APPEND(FC_CAL_I2C_Master_Uninit_, I2CMASTER_2_MX_I2C_UREF)
#define I2CMASTER_2_I2C_Master_Start		CAL_APPEND(FC_CAL_I2C_Master_Start_, I2CMASTER_2_MX_I2C_UREF)
#define I2CMASTER_2_I2C_Master_Restart	CAL_APPEND(FC_CAL_I2C_Master_Restart_, I2CMASTER_2_MX_I2C_UREF)
#define I2CMASTER_2_I2C_Master_Stop		CAL_APPEND(FC_CAL_I2C_Master_Stop_, I2CMASTER_2_MX_I2C_UREF)
#define I2CMASTER_2_I2C_Master_TX_Byte	CAL_APPEND(FC_CAL_I2C_Master_TX_Byte_, I2CMASTER_2_MX_I2C_UREF)
#define I2CMASTER_2_I2C_Master_RX_Byte	CAL_APPEND(FC_CAL_I2C_Master_RX_Byte_, I2CMASTER_2_MX_I2C_UREF)

extern void I2CMASTER_2_I2C_Master_Init ();
extern void I2CMASTER_2_I2C_Master_Uninit ();
extern void I2CMASTER_2_I2C_Master_Start ();
extern void I2CMASTER_2_I2C_Master_Restart ();
extern void I2CMASTER_2_I2C_Master_Stop ();
extern MX_UINT8 I2CMASTER_2_I2C_Master_TX_Byte (MX_UINT8 Data);
extern MX_UINT8 I2CMASTER_2_I2C_Master_RX_Byte (MX_UINT8 Last);




//I2C_Master(0): //Macro function declarations

void FCD_I2C_Master0_MI2C_Init();
void FCD_I2C_Master0_MI2C_Start();
void FCD_I2C_Master0_MI2C_Restart();
void FCD_I2C_Master0_MI2C_Stop();
MX_UINT8 FCD_I2C_Master0_MI2C_Transmit_Byte(MX_UINT8 Data);
MX_UINT8 FCD_I2C_Master0_MI2C_Receive_Byte(MX_UINT8 Last);
void FCD_I2C_Master0_MI2C_Send_Byte_Transaction(MX_UINT8 Device_ID, MX_UINT8 AddrH, MX_UINT8 AddrL, MX_UINT8 Data);
MX_UINT8 FCD_I2C_Master0_MI2C_Receive_Byte_Transaction(MX_UINT8 Device_ID, MX_UINT8 AddrH, MX_UINT8 AddrL);



//LCDDisplay(0): //Macro implementations


void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask)
{
	
		MX_UINT8 pt;

		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		pt = ((in >> 4) & 0x0f);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		pt = (in & 0x0f);
		LCD_1__DELAY;
		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;

}

void FCD_LCDDisplay0_Start()
{
	
		FC_CAL_Bit_Low_DDR(LCD_1__PORT0, LCD_1__TRIS0, LCD_1__BIT0);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT1, LCD_1__TRIS1, LCD_1__BIT1);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT2, LCD_1__TRIS2, LCD_1__BIT2);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT3, LCD_1__TRIS3, LCD_1__BIT3);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT4, LCD_1__TRIS4, LCD_1__RS);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT5, LCD_1__TRIS5, LCD_1__E);

		Wdt_Delay_Ms(12);

		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x32, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x2c, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x06, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x0c, 0);
		Wdt_Delay_Ms(2);

		//clear the display
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Clear()
{
	
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character)
{
	
		FCD_LCDDisplay0_RawSend(Character, 0x10);

}

void FCD_LCDDisplay0_Command(MX_UINT8 in)
{
	
		FCD_LCDDisplay0_RawSend(in, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y)
{
	
	  #if (LCD_1__ROWCNT == 1)
	    y=0x80;
	  #endif

	  #if (LCD_1__ROWCNT == 2)
		if (y==0)
			y=0x80;
		else
			y=0xc0;
	  #endif

	  #if (LCD_1__ROWCNT == 4)
		if (y==0)
			y=0x80;
		else if (y==1)
			y=0xc0;

		#if (LCD_1__COLCNT == 16)
			else if (y==2)
				y=0x90;
			else
				y=0xd0;
		#endif

		#if (LCD_1__COLCNT == 20)
			else if (y==2)
				y=0x94;
			else
				y=0xd4;
		#endif
	  #endif

		FCD_LCDDisplay0_RawSend(y+x, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number)
{
	
		MX_SINT16 tmp_int;
		MX_UINT8 tmp_byte;

		if (Number < 0)
		{
			FCD_LCDDisplay0_RawSend('-', 0x10);
			Number = 0 - Number;
		}

		tmp_int = Number;
		if (Number >= 10000)
		{
			tmp_byte = tmp_int / 10000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10000;
				tmp_byte--;
			}
		}
		if (Number >= 1000)
		{
			tmp_byte = tmp_int / 1000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 1000;
				tmp_byte--;
			}
		}
		if (Number >= 100)
		{
			tmp_byte = tmp_int / 100;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 100;
				tmp_byte--;
			}
		}
		if (Number >= 10)
		{
			tmp_byte = tmp_int / 10;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10;
				tmp_byte--;
			}
		}
		FCD_LCDDisplay0_RawSend('0' + tmp_int, 0x10);

}

void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx = 0;

		for (idx=0; idx<MSZ_String; idx++)
		{
			if (String[idx] == 0)
			{
				break;
			}
			FCD_LCDDisplay0_RawSend(String[idx], 0x10);
		}

}

void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions)
{
	
		MX_UINT8 cmd = 0;
		MX_UINT8 count;

		//Choose the direction
		switch (Direction)
		{
			case 0:
			case 'l':
			case 'L':

				cmd = 0x18;
				break;

			case 1:
			case 'r':
			case 'R':

				cmd = 0x1C;
				break;

			default:
				break;
		}

		//If direction accepted then scroll the specified amount
		if (cmd)
		{
			for (count = 0; count < Num_Positions; count++)
				FCD_LCDDisplay0_Command(cmd);
		}

}

void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line)
{
	
		MX_UINT8 count;
		MX_UINT8 rowcount;

		//Define number of columns per line
		#if (LCD_1__ROWCNT == 1)
			rowcount=80;
		#endif

		#if (LCD_1__ROWCNT == 2)
			rowcount=40;
		#endif

		#if (LCD_1__ROWCNT == 4)
			#if (LCD_1__COLCNT == 16)
				rowcount=16;
			#endif
			#if (LCD_1__COLCNT == 20)
				rowcount=20;
			#endif
		#endif

		//Start at beginning of the line
		FCD_LCDDisplay0_Cursor (0, Line);

		//Send out spaces to clear line
		for (count = 0; count < rowcount; count++)
			FCD_LCDDisplay0_RawSend(' ', 0x10);

		//Move back to the beginning of the line.
		FCD_LCDDisplay0_Cursor (0, Line);

}

void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7)
{
	   //set CGRAM address

	   FCD_LCDDisplay0_RawSend(64 + (nIdx << 3), 0);
	   delay_ms(2);

	   //write CGRAM data
	   FCD_LCDDisplay0_RawSend(d0, 0x10);
	   FCD_LCDDisplay0_RawSend(d1, 0x10);
	   FCD_LCDDisplay0_RawSend(d2, 0x10);
	   FCD_LCDDisplay0_RawSend(d3, 0x10);
	   FCD_LCDDisplay0_RawSend(d4, 0x10);
	   FCD_LCDDisplay0_RawSend(d5, 0x10);
	   FCD_LCDDisplay0_RawSend(d6, 0x10);
	   FCD_LCDDisplay0_RawSend(d7, 0x10);

	   //Clear the display
	   FCD_LCDDisplay0_RawSend(0x01, 0);
	   delay_ms(2);
	   FCD_LCDDisplay0_RawSend(0x02, 0);
	   delay_ms(2);

}



//I2C_Master(0): //Macro implementations


void FCD_I2C_Master0_MI2C_Init()
{
	
		I2CMASTER_2_I2C_Master_Init();

}

void FCD_I2C_Master0_MI2C_Start()
{
	
		I2CMASTER_2_I2C_Master_Start();

}

void FCD_I2C_Master0_MI2C_Restart()
{
	
		I2CMASTER_2_I2C_Master_Restart();

}

void FCD_I2C_Master0_MI2C_Stop()
{
	
		I2CMASTER_2_I2C_Master_Stop();

}

MX_UINT8 FCD_I2C_Master0_MI2C_Transmit_Byte(MX_UINT8 Data)
{
	
		return I2CMASTER_2_I2C_Master_TX_Byte(Data);

}

MX_UINT8 FCD_I2C_Master0_MI2C_Receive_Byte(MX_UINT8 Last)
{
	
		return I2CMASTER_2_I2C_Master_RX_Byte(Last);

}

void FCD_I2C_Master0_MI2C_Send_Byte_Transaction(MX_UINT8 Device_ID, MX_UINT8 AddrH, MX_UINT8 AddrL, MX_UINT8 Data)
{
	
		Device_ID = Device_ID << 1;					//Shift Device ID to enable write mode

		I2CMASTER_2_I2C_Master_Start();						//Start transaction
		I2CMASTER_2_I2C_Master_TX_Byte(Device_ID);			//Transmit Device Address
		I2CMASTER_2_I2C_Master_TX_Byte(AddrH);				//Transmit Internal Address
		I2CMASTER_2_I2C_Master_TX_Byte(AddrL);
		I2CMASTER_2_I2C_Master_TX_Byte(Data);				//Send Data byte
		I2CMASTER_2_I2C_Master_Stop();						//Stop Transaction

}

MX_UINT8 FCD_I2C_Master0_MI2C_Receive_Byte_Transaction(MX_UINT8 Device_ID, MX_UINT8 AddrH, MX_UINT8 AddrL)
{
	
		MX_UINT8 RetVal = 0;
		Device_ID = Device_ID << 1;					//Shift Device ID to enable write mode

		I2CMASTER_2_I2C_Master_Start();						//Start transaction
		I2CMASTER_2_I2C_Master_TX_Byte(Device_ID);			//Transmit Device Address
		I2CMASTER_2_I2C_Master_TX_Byte(AddrH);				//Transmit Internal Address
		I2CMASTER_2_I2C_Master_TX_Byte(AddrL);
		I2CMASTER_2_I2C_Master_Restart();					//Restart transaction

		Device_ID = Device_ID | 0x01;				//Change Device ID to read mode
		I2CMASTER_2_I2C_Master_TX_Byte(Device_ID);			//Transmit Device Address
		RetVal = I2CMASTER_2_I2C_Master_RX_Byte(1);			//Read data at address
		I2CMASTER_2_I2C_Master_Stop();						//Stop Transaction

		return RetVal;								//Return data

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_IIC_START()
{

	//I2C_DAT
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//CLK
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//Delay
	//Delay: 1 us
	delay_us(1);

	//I2C_DAT
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//CLK
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

}


void FCM_IIC_STOP()
{

	//I2C_DAT
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//CLK
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//Delay
	//Delay: 1 us
	delay_us(1);

	//CLK
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//I2C_DAT
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

}


void FCM_IIC_CLKP()
{

	//CLK
	//Output: 1 -> C3
	trisc = trisc & 0xF7;
	if ((1))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//CLK
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

}


void FCM_IIC_WRITEID_W()
{

	//Call Macro
	//Call Macro: IIC_START()
	FCM_IIC_START();

	//I2C_DAT
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

	//I2C_DAT
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

	//I2C_DAT
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

	//I2C_DAT
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

	//I2C_DAT
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

	//I2C_DAT
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

	//I2C_DAT
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

	//I2C_DAT
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

	//Call Macro
	//Call Macro: IIC_SACK()
	FCM_IIC_SACK();

	//Call Macro
	//Call Macro: IIC_STOP()
	FCM_IIC_STOP();

}


void FCM_IIC_SACK()
{

	//Connection Point
	//Connection Point: [A]: A
FCC_IIC_SACK_A:
;

	//DATA
	//Input: C4 -> ack
	trisc = trisc | 0x10;
	FCV_ACK = ((portc & 0x10) == 0x10);

	//Decision
	//Decision: ack = 1?
	if (FCV_ACK == 1)
	{

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_IIC_SACK_A;

	// } else {

	}

	//Call Macro
	//Call Macro: IIC_CLKP()
	FCM_IIC_CLKP();

}



void main()
{
	//Initialization
	adcon1 = 0x07;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Call Component Macro
	//Call Component Macro: MI2C_Init()
	FCD_I2C_Master0_MI2C_Init();

	//Call Component Macro
	//Call Component Macro: Start()
	FCD_LCDDisplay0_Start();

	//Call Component Macro
	//Call Component Macro: Clear()
	FCD_LCDDisplay0_Clear();

	//Loop
	//Loop: While 1
	while (1)
	{

		//Call Component Macro
		//Call Component Macro: Cursor(0, 0)
		FCD_LCDDisplay0_Cursor(0, 0);

		//Call Component Macro
		//Call Component Macro: PrintString("hello world")
		FCD_LCDDisplay0_PrintString("hello world", 11);


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



