//************************************************************************************
//**  
//**  File name:     C:\Users\gerpe\OneDrive\GER-PER 2016\Documents\KennyNeutron\2020\Thermometer\Flowcode\thermo873a_v3_12V.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Wednesday, August 05, 2020 12:15:51
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 1
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 1
#define MX_USES_BOOL 1
#define MX_USES_UINT16 1
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F873A
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_1
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 128
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 3276800
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x1f32
#endif
#ifdef HI_TECH_C
__CONFIG(0x1f32);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_scan1();
void FCM_scan2();
void FCM_scan3();
void FCM_scan4();
void FCM_scan_off();
void FCM_test();
void FCM_seg_pattern();
void FCM_display_temp();
void FCM_all_input();
void FCM_pass();
void FCM_failed();
void FCM_calc();
void FCM_i2c_comm();
void FCM_lights_off();
void FCM_beep_once();
void FCM_get_temp();
void FCM_display_repeat();
void FCM_repeat();
void FCM_display_fail();
void FCM_calibrate();
void FCM_display_temp_calib();
void FCM_calc_calib();


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_UINT8 FCV_TEMP_TENS = (0x0);
MX_UINT8 FCV_D_BYTE = (0x0);
MX_SINT32 FCV_RAW = (0);
MX_UINT8 FCV_DATA0 = (0xff);
MX_SINT16 FCV_TEMP_CDP = (0);
MX_UINT8 FCV_DATA1 = (0xff);
MX_UINT8 FCV_RET_BYTE = (0x0);
MX_UINT8 FCV_DP2 = (0x0);
MX_UINT8 FCV_DATA2 = (0xff);
MX_UINT8 FCV_RESET_COUNTER = (0x0);
MX_UINT8 FCV_TEMP_DEC = (0x0);
MX_BOOL FCV_PROX_BIT = (1);
MX_UINT8 FCV_TEMP_ONES = (0x0);
MX_UINT8 FCV_LSB = (0xff);
MX_UINT8 FCV_RT_BYTE = (0xff);
MX_UINT8 FCV_PROX_COUNTER = (0x0);
MX_UINT8 FCV_MSB = (0xff);
MX_UINT8 FCV_DIGIT = (0x0);
MX_UINT16 FCV_CALIB_SUBTRACTOR;
MX_UINT8 FCV_SWR = (0x1);
MX_BOOL FCV_SW0 = (1);
MX_BOOL FCV_FLAGBIT = (1);
MX_SINT32 FCV_TEMP_C;
MX_UINT8 FCV_I2C_RX = (0x0);
MX_UINT8 FCV_CALIB_FACTOR = (0x0);
MX_UINT8 FCV_CALIB_COUNT;
MX_UINT8 FCV_DATA_PREV = (0x0);
MX_UINT16 FCV_SAVE_CALIB0 = (0x0);
MX_UINT8 FCV_SW_CALIB = (0x0);
MX_UINT8 FCV_SAVE_CALIB1;
MX_SINT16 FCV_CALIB_OFFSET;
MX_BOOL FCV_SWG = (1);
MX_UINT8 FCV_DATA_DIFF = (0x0);

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;
MX_UINT8 FCLV_LOOP5;
MX_UINT8 FCLV_LOOP6;
MX_UINT8 FCLV_LOOP7;
MX_UINT8 FCLV_LOOP8;
MX_UINT8 FCLV_LOOP9;
MX_UINT8 FCLV_LOOP10;
MX_UINT8 FCLV_LOOP11;



//PWM(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = PWM Channel - 0=SW / 1-8=HW
c = PWM Alt Pin FCD_PWM0_Enable - 0=Standard / 1=Alt
d = PWM Period
e = PWM Prescaler 1
******************************/

//Period and Prescaler Defines
#ifndef MX_PWM_PERIOD
  #define MX_PWM_PERIOD				255
#else
  #if (MX_PWM_PERIOD != 255)
    #error "PWM period value must be the same in all PWM modules"
  #endif
#endif

#ifndef MX_PWM_PRESCALE1
  #define MX_PWM_PRESCALE1			1
#else
  #if (MX_PWM_PRESCALE1 != 1)
    #error "PWM prescale value must be the same in all PWM modules"
  #endif
#endif

//Definitions for PWM slot allocation
#ifndef	MX_PWM_REF1
			#define MX_PWM_REF1
			#define PWM_1_MX_PWM_UREF			1
			#define MX_PWM_CHANNEL_1		2
			#define MX_PWM_HWALT_1			0
#else
 #ifndef	MX_PWM_REF2
			#define MX_PWM_REF2
			#define PWM_1_MX_PWM_UREF			2
			#define MX_PWM_CHANNEL_2		2
			#define MX_PWM_HWALT_2			0
 #else
  #ifndef	MX_PWM_REF3
			#define MX_PWM_REF3
			#define PWM_1_MX_PWM_UREF			3
			#define MX_PWM_CHANNEL_3		2
			#define MX_PWM_HWALT_3			0
  #else
   #ifndef	MX_PWM_REF4
			#define MX_PWM_REF4
			#define PWM_1_MX_PWM_UREF			4
			#define MX_PWM_CHANNEL_4		2
			#define MX_PWM_HWALT_4			0
   #else
    #ifndef	MX_PWM_REF5
			#define MX_PWM_REF5
			#define PWM_1_MX_PWM_UREF			5
			#define MX_PWM_CHANNEL_5		2
			#define MX_PWM_HWALT_5			0
    #else
     #ifndef	MX_PWM_REF6
			#define MX_PWM_REF6
			#define PWM_1_MX_PWM_UREF			6
			#define MX_PWM_CHANNEL_6		2
			#define MX_PWM_HWALT_6			0
     #else
      #ifndef	MX_PWM_REF7
			#define MX_PWM_REF7
			#define PWM_1_MX_PWM_UREF			7
			#define MX_PWM_CHANNEL_7		2
			#define MX_PWM_HWALT_7			0
      #else
       #ifndef	MX_PWM_REF8
			#define MX_PWM_REF8
			#define PWM_1_MX_PWM_UREF			8
			#define MX_PWM_CHANNEL_8		2
			#define MX_PWM_HWALT_8			0
       #else
        #ifndef	MX_PWM_REF9
			#define MX_PWM_REF9
			#define PWM_1_MX_PWM_UREF			9
			#define MX_PWM_CHANNEL_9		2
			#define MX_PWM_HWALT_9			0
        #else
         #ifndef	MX_PWM_REF10
			#define MX_PWM_REF10
			#define PWM_1_MX_PWM_UREF			10
			#define MX_PWM_CHANNEL_10		2
			#define MX_PWM_HWALT_10			0
         #endif
        #endif
       #endif
      #endif
     #endif
    #endif
   #endif
  #endif
 #endif
#endif

#define PWM_1_PWM_Enable_Channel		CAL_APPEND(FC_CAL_PWM_Enable_Channel_, PWM_1_MX_PWM_UREF)
#define PWM_1_PWM_Disable_Channel		CAL_APPEND(FC_CAL_PWM_Disable_Channel_, PWM_1_MX_PWM_UREF)
#define PWM_1_PWM_Set_Duty_8Bit		CAL_APPEND(FC_CAL_PWM_Set_Duty_8Bit_, PWM_1_MX_PWM_UREF)
#define PWM_1_PWM_Change_Period		CAL_APPEND(FC_CAL_PWM_Change_Period_, PWM_1_MX_PWM_UREF)
#define PWM_1_PWM_Set_Duty_10Bit		CAL_APPEND(FC_CAL_PWM_Set_Duty_10Bit_, PWM_1_MX_PWM_UREF)

extern void PWM_1_PWM_Enable_Channel ();
extern void PWM_1_PWM_Disable_Channel ();
extern void PWM_1_PWM_Set_Duty_8Bit (MX_UINT8 duty);
extern void PWM_1_PWM_Change_Period (MX_UINT8 period, MX_UINT16 prescaler);
extern void PWM_1_PWM_Set_Duty_10Bit (MX_UINT16 duty);




//PWM(0): //Macro function declarations

void FCD_PWM0_Enable();
void FCD_PWM0_Disable();
void FCD_PWM0_SetDutyCycle(MX_UINT8 nDuty);
void FCD_PWM0_ChangePeriod(MX_UINT8 nPeriodVal, MX_UINT8 nPrescalerVal);
void FCD_PWM0_SetDutyCycle10bit(MX_SINT16 nDuty);


//LED(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_2__LED_PORT		porta
#define LED_2__LED_TRIS		trisa
#define LED_2__LED_PIN		5
#define LED_2__LED_POLE		1




//LED(0): //Macro function declarations

void FCD_LED0_LEDOn();
void FCD_LED0_LEDOff();


//LED(1): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = LED Port Letter
c = LED Pin Number
d = LED Active Polarity
******************************/

#define LED_3__LED_PORT		portc
#define LED_3__LED_TRIS		trisc
#define LED_3__LED_PIN		5
#define LED_3__LED_POLE		1




//LED(1): //Macro function declarations

void FCD_LED1_LEDOn();
void FCD_LED1_LEDOff();


//I2C_Master(0): //Defines:

/**** Macro Substitutions ****
a = Unique component ID
b = I2C Channel - 0=SW, 1-4=HW
c = Baud Rate
d = SM BUS Enable 0/2
e = Slew Rate Enable 0/1
f = Bitbanged Data Port Letter
g = Bitbanged Data Pin
h = Bitbanged Clock Port Letter
i = Bitbanged Clock Pin
******************************/

//BMODE
//Bit 0 - Slew Control
//Bit 1 - SMBus Control

//Definitions for I2C slot allocation
#ifndef	MX_I2C_REF1
	#define MX_I2C_REF1
	#define I2CMASTER_5_MX_I2C_UREF			1
	#define MX_I2C_CHANNEL_1		1
	#define MX_I2C_SDA_PIN_1		4
	#define MX_I2C_SDA_PORT_1		portd
	#define MX_I2C_SDA_TRIS_1		trisd
	#define MX_I2C_SCL_PIN_1		3
	#define MX_I2C_SCL_PORT_1		portd
	#define MX_I2C_SCL_TRIS_1		trisd
	#define MX_I2C_BMODE_1			0 | 0
	#define MX_I2C_BAUD_1			100000
	#define MX_I2C_INT_1			0
#else
 #ifndef MX_I2C_REF2
	#define MX_I2C_REF2
	#define I2CMASTER_5_MX_I2C_UREF			2
	#define MX_I2C_CHANNEL_2		1
	#define MX_I2C_SDA_PIN_2		4
	#define MX_I2C_SDA_PORT_2		portd
	#define MX_I2C_SDA_TRIS_2		trisd
	#define MX_I2C_SCL_PIN_2		3
	#define MX_I2C_SCL_PORT_2		portd
	#define MX_I2C_SCL_TRIS_2		trisd
	#define MX_I2C_BMODE_2			0 | 0
	#define MX_I2C_BAUD_2			100000
	#define MX_I2C_INT_2			0
 #else
  #ifndef MX_I2C_REF3
	#define MX_I2C_REF3
	#define I2CMASTER_5_MX_I2C_UREF			3
	#define MX_I2C_CHANNEL_3		1
	#define MX_I2C_SDA_PIN_3		4
	#define MX_I2C_SDA_PORT_3		portd
	#define MX_I2C_SDA_TRIS_3		trisd
	#define MX_I2C_SCL_PIN_3		3
	#define MX_I2C_SCL_PORT_3		portd
	#define MX_I2C_SCL_TRIS_3		trisd
	#define MX_I2C_BMODE_3			0 | 0
	#define MX_I2C_BAUD_3			100000
	#define MX_I2C_INT_3			0
  #else
   #ifndef MX_I2C_REF4
	#define MX_I2C_REF4
	#define I2CMASTER_5_MX_I2C_UREF			4
	#define MX_I2C_CHANNEL_4		1
	#define MX_I2C_SDA_PIN_4		4
	#define MX_I2C_SDA_PORT_4		portd
	#define MX_I2C_SDA_TRIS_4		trisd
	#define MX_I2C_SCL_PIN_4		3
	#define MX_I2C_SCL_PORT_4		portd
	#define MX_I2C_SCL_TRIS_4		trisd
	#define MX_I2C_BMODE_4			0 | 0
	#define MX_I2C_BAUD_4			100000
	#define MX_I2C_INT_4			0
   #endif
  #endif
 #endif
#endif

#define I2CMASTER_5_I2C_Master_Init		CAL_APPEND(FC_CAL_I2C_Master_Init_, I2CMASTER_5_MX_I2C_UREF)
#define I2CMASTER_5_I2C_Master_Uninit	CAL_APPEND(FC_CAL_I2C_Master_Uninit_, I2CMASTER_5_MX_I2C_UREF)
#define I2CMASTER_5_I2C_Master_Start		CAL_APPEND(FC_CAL_I2C_Master_Start_, I2CMASTER_5_MX_I2C_UREF)
#define I2CMASTER_5_I2C_Master_Restart	CAL_APPEND(FC_CAL_I2C_Master_Restart_, I2CMASTER_5_MX_I2C_UREF)
#define I2CMASTER_5_I2C_Master_Stop		CAL_APPEND(FC_CAL_I2C_Master_Stop_, I2CMASTER_5_MX_I2C_UREF)
#define I2CMASTER_5_I2C_Master_TX_Byte	CAL_APPEND(FC_CAL_I2C_Master_TX_Byte_, I2CMASTER_5_MX_I2C_UREF)
#define I2CMASTER_5_I2C_Master_RX_Byte	CAL_APPEND(FC_CAL_I2C_Master_RX_Byte_, I2CMASTER_5_MX_I2C_UREF)

extern void I2CMASTER_5_I2C_Master_Init ();
extern void I2CMASTER_5_I2C_Master_Uninit ();
extern void I2CMASTER_5_I2C_Master_Start ();
extern void I2CMASTER_5_I2C_Master_Restart ();
extern void I2CMASTER_5_I2C_Master_Stop ();
extern MX_UINT8 I2CMASTER_5_I2C_Master_TX_Byte (MX_UINT8 Data);
extern MX_UINT8 I2CMASTER_5_I2C_Master_RX_Byte (MX_UINT8 Last);




//I2C_Master(0): //Macro function declarations

void FCD_I2C_Master0_MI2C_Init();
void FCD_I2C_Master0_MI2C_Start();
void FCD_I2C_Master0_MI2C_Restart();
void FCD_I2C_Master0_MI2C_Stop();
MX_UINT8 FCD_I2C_Master0_MI2C_Transmit_Byte(MX_UINT8 Data);
MX_UINT8 FCD_I2C_Master0_MI2C_Receive_Byte(MX_UINT8 Last);
void FCD_I2C_Master0_MI2C_Send_Byte_Transaction(MX_UINT8 Device_ID, MX_UINT8 AddrH, MX_UINT8 AddrL, MX_UINT8 Data);
MX_UINT8 FCD_I2C_Master0_MI2C_Receive_Byte_Transaction(MX_UINT8 Device_ID, MX_UINT8 AddrH, MX_UINT8 AddrL);


//EEPROM(0): //Defines:

/**** Macro Substitutions ****
Component has no substitutions
******************************/

#ifndef MX_EEPROM_REF
	#define MX_EEPROM_REF

	#ifdef FC_CAL_PIC16BIT
		extern MX_UINT16 FC_CAL_EE_Read (MX_UINT16 Address);
		extern void FC_CAL_EE_Write (MX_UINT16 Address, MX_UINT16 Data);
	#else
		extern MX_UINT8 FC_CAL_EE_Read (MX_UINT16 Address);
		extern void FC_CAL_EE_Write (MX_UINT16 Address, MX_UINT8 Data);
	#endif
#endif




//EEPROM(0): //Macro function declarations

MX_UINT16 FCD_EEPROM0_EEPROMRead(MX_UINT16 addr);
void FCD_EEPROM0_WriteEEPROM(MX_UINT16 addr, MX_UINT16 data);


//RS232(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Uart Channel		(0-software / 1-4 hardware)
c = tx pin
d = tx port
e = rx pin
f = rx port
g = flow control		(0-Off / 1-On)
h = cts pin
i = cts port
j = rts pin
k = rts port
l = baud rate
m = data bits			(7/8/9) (7 only supported in software modes)
n = return type		(0-byte / 1-MX_UINT16)
o = echo enable		(0-Off / 1-On)
******************************/

//Definitions for RS232 UART slot allocation
#ifndef	MX_UART_REF1
	#define MX_UART_REF1
	#define RS232_7_MX_UART_UREF			1
	#define MX_UART_CHANNEL_1		1
	#define MX_UART_TX_PIN_1		0
	#define MX_UART_TX_PORT_1		porta
	#define MX_UART_TX_TRIS_1		trisa
	#define MX_UART_RX_PIN_1		0
	#define MX_UART_RX_PORT_1		porta
	#define MX_UART_RX_TRIS_1		trisa
	#define MX_UART_FLOWEN_1		0
	#define MX_UART_CTS_PIN_1		4
	#define MX_UART_CTS_PORT_1		portc
	#define MX_UART_CTS_TRIS_1		trisc
	#define MX_UART_RTS_PIN_1		0
	#define MX_UART_RTS_PORT_1		portc
	#define MX_UART_RTS_TRIS_1		trisc
	#define MX_UART_BAUD_1			9600
	#define MX_UART_DBITS_1			8
	#define MX_UART_RETURN_1		0
	#define MX_UART_ECHO_1			0
	#define MX_UART_INT_1			0
#else
 #ifndef	MX_UART_REF2
	#define MX_UART_REF2
	#define RS232_7_MX_UART_UREF			2
	#define MX_UART_CHANNEL_2		1
	#define MX_UART_TX_PIN_2		0
	#define MX_UART_TX_PORT_2		porta
	#define MX_UART_TX_TRIS_2		trisa
	#define MX_UART_RX_PIN_2		0
	#define MX_UART_RX_PORT_2		porta
	#define MX_UART_RX_TRIS_2		trisa
	#define MX_UART_FLOWEN_2		0
	#define MX_UART_CTS_PIN_2		4
	#define MX_UART_CTS_PORT_2		portc
	#define MX_UART_CTS_TRIS_2		trisc
	#define MX_UART_RTS_PIN_2		0
	#define MX_UART_RTS_PORT_2		portc
	#define MX_UART_RTS_TRIS_2		trisc
	#define MX_UART_BAUD_2			9600
	#define MX_UART_DBITS_2			8
	#define MX_UART_RETURN_2		0
	#define MX_UART_ECHO_2			0
	#define MX_UART_INT_2			0
 #else
  #ifndef	MX_UART_REF3
	#define MX_UART_REF3
	#define RS232_7_MX_UART_UREF			3
	#define MX_UART_CHANNEL_3		1
	#define MX_UART_TX_PIN_3		0
	#define MX_UART_TX_PORT_3		porta
	#define MX_UART_TX_TRIS_3		trisa
	#define MX_UART_RX_PIN_3		0
	#define MX_UART_RX_PORT_3		porta
	#define MX_UART_RX_TRIS_3		trisa
	#define MX_UART_FLOWEN_3		0
	#define MX_UART_CTS_PIN_3		4
	#define MX_UART_CTS_PORT_3		portc
	#define MX_UART_CTS_TRIS_3		trisc
	#define MX_UART_RTS_PIN_3		0
	#define MX_UART_RTS_PORT_3		portc
	#define MX_UART_RTS_TRIS_3		trisc
	#define MX_UART_BAUD_3			9600
	#define MX_UART_DBITS_3			8
	#define MX_UART_RETURN_3		0
	#define MX_UART_ECHO_3			0
	#define MX_UART_INT_3			0
  #else
   #ifndef	MX_UART_REF4
	#define MX_UART_REF4
	#define RS232_7_MX_UART_UREF			4
	#define MX_UART_CHANNEL_4		1
	#define MX_UART_TX_PIN_4		0
	#define MX_UART_TX_PORT_4		porta
	#define MX_UART_TX_TRIS_4		trisa
	#define MX_UART_RX_PIN_4		0
	#define MX_UART_RX_PORT_4		porta
	#define MX_UART_RX_TRIS_4		trisa
	#define MX_UART_FLOWEN_4		0
	#define MX_UART_CTS_PIN_4		4
	#define MX_UART_CTS_PORT_4		portc
	#define MX_UART_CTS_TRIS_4		trisc
	#define MX_UART_RTS_PIN_4		0
	#define MX_UART_RTS_PORT_4		portc
	#define MX_UART_RTS_TRIS_4		trisc
	#define MX_UART_BAUD_4			9600
	#define MX_UART_DBITS_4			8
	#define MX_UART_RETURN_4		0
	#define MX_UART_ECHO_4			0
	#define MX_UART_INT_4			0
   #endif
  #endif
 #endif
#endif

#define RS232_7_UART_Init		CAL_APPEND(FC_CAL_UART_Init_, RS232_7_MX_UART_UREF)
#define RS232_7_UART_Send		CAL_APPEND(FC_CAL_UART_Send_, RS232_7_MX_UART_UREF)
#define RS232_7_UART_Receive		CAL_APPEND(FC_CAL_UART_Receive_, RS232_7_MX_UART_UREF)
#define RS232_7_UART_Update_Baud CAL_APPEND(FC_CAL_UART_Update_Baud_, RS232_7_MX_UART_UREF)

extern void RS232_7_UART_Init();
extern void RS232_7_UART_Send(MX_UINT16 nChar);
extern MX_SINT16 RS232_7_UART_Receive(MX_UINT8 nTimeout);
extern void RS232_7_UART_Update_Baud(MX_UINT8 newbaud);




//RS232(0): //Macro function declarations

void FCD_RS2320_SendRS232Char(MX_SINT16 nChar);
void FCD_RS2320_SendRS232String(MX_STRING String, MX_UINT8 MSZ_String);
MX_SINT16 FCD_RS2320_ReceiveRS232Char(MX_UINT8 nTimeout);
void FCD_RS2320_ReceiveRS232String(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE, MX_UINT8 nTimeout, MX_UINT8 NumBytes);
void FCD_RS2320_ChangeHWBaud(MX_UINT8 newbaud);



//PWM(0): //Macro implementations


void FCD_PWM0_Enable()
{
	
		PWM_1_PWM_Change_Period (MX_PWM_PERIOD, MX_PWM_PRESCALE1);
		PWM_1_PWM_Enable_Channel ();

}

void FCD_PWM0_Disable()
{
	
		PWM_1_PWM_Disable_Channel();

}

void FCD_PWM0_SetDutyCycle(MX_UINT8 nDuty)
{
	
		PWM_1_PWM_Set_Duty_8Bit(nDuty);

}

void FCD_PWM0_ChangePeriod(MX_UINT8 nPeriodVal, MX_UINT8 nPrescalerVal)
{
	
		PWM_1_PWM_Change_Period (nPeriodVal, nPrescalerVal);

}

void FCD_PWM0_SetDutyCycle10bit(MX_SINT16 nDuty)
{
	
		PWM_1_PWM_Set_Duty_10Bit(nDuty);

}



//LED(0): //Macro implementations


void FCD_LED0_LEDOn()
{
	
		#if( LED_2__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#endif

}

void FCD_LED0_LEDOff()
{
	
		#if( LED_2__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_2__LED_PORT	, LED_2__LED_TRIS , LED_2__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_2__LED_PORT , LED_2__LED_TRIS , LED_2__LED_PIN );
		#endif

}



//LED(1): //Macro implementations


void FCD_LED1_LEDOn()
{
	
		#if( LED_3__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_High_DDR( LED_3__LED_PORT , LED_3__LED_TRIS , LED_3__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_Low_DDR( LED_3__LED_PORT , LED_3__LED_TRIS , LED_3__LED_PIN );
		#endif

}

void FCD_LED1_LEDOff()
{
	
		#if( LED_3__LED_POLE == 1)									//Active high polarity
			FC_CAL_Bit_Low_DDR( LED_3__LED_PORT	, LED_3__LED_TRIS , LED_3__LED_PIN );
		#else													//Active low polarity
			FC_CAL_Bit_High_DDR( LED_3__LED_PORT , LED_3__LED_TRIS , LED_3__LED_PIN );
		#endif

}



//I2C_Master(0): //Macro implementations


void FCD_I2C_Master0_MI2C_Init()
{
	
		I2CMASTER_5_I2C_Master_Init();

}

void FCD_I2C_Master0_MI2C_Start()
{
	
		I2CMASTER_5_I2C_Master_Start();

}

void FCD_I2C_Master0_MI2C_Restart()
{
	
		I2CMASTER_5_I2C_Master_Restart();

}

void FCD_I2C_Master0_MI2C_Stop()
{
	
		I2CMASTER_5_I2C_Master_Stop();

}

MX_UINT8 FCD_I2C_Master0_MI2C_Transmit_Byte(MX_UINT8 Data)
{
	
		return I2CMASTER_5_I2C_Master_TX_Byte(Data);

}

MX_UINT8 FCD_I2C_Master0_MI2C_Receive_Byte(MX_UINT8 Last)
{
	
		return I2CMASTER_5_I2C_Master_RX_Byte(Last);

}

void FCD_I2C_Master0_MI2C_Send_Byte_Transaction(MX_UINT8 Device_ID, MX_UINT8 AddrH, MX_UINT8 AddrL, MX_UINT8 Data)
{
	
		Device_ID = Device_ID << 1;					//Shift Device ID to enable write mode

		I2CMASTER_5_I2C_Master_Start();						//Start transaction
		I2CMASTER_5_I2C_Master_TX_Byte(Device_ID);			//Transmit Device Address
		I2CMASTER_5_I2C_Master_TX_Byte(AddrH);				//Transmit Internal Address
		I2CMASTER_5_I2C_Master_TX_Byte(AddrL);
		I2CMASTER_5_I2C_Master_TX_Byte(Data);				//Send Data byte
		I2CMASTER_5_I2C_Master_Stop();						//Stop Transaction

}

MX_UINT8 FCD_I2C_Master0_MI2C_Receive_Byte_Transaction(MX_UINT8 Device_ID, MX_UINT8 AddrH, MX_UINT8 AddrL)
{
	
		MX_UINT8 RetVal = 0;
		Device_ID = Device_ID << 1;					//Shift Device ID to enable write mode

		I2CMASTER_5_I2C_Master_Start();						//Start transaction
		I2CMASTER_5_I2C_Master_TX_Byte(Device_ID);			//Transmit Device Address
		I2CMASTER_5_I2C_Master_TX_Byte(AddrH);				//Transmit Internal Address
		I2CMASTER_5_I2C_Master_TX_Byte(AddrL);
		I2CMASTER_5_I2C_Master_Restart();					//Restart transaction

		Device_ID = Device_ID | 0x01;				//Change Device ID to read mode
		I2CMASTER_5_I2C_Master_TX_Byte(Device_ID);			//Transmit Device Address
		RetVal = I2CMASTER_5_I2C_Master_RX_Byte(1);			//Read data at address
		I2CMASTER_5_I2C_Master_Stop();						//Stop Transaction

		return RetVal;								//Return data

}



//EEPROM(0): //Macro implementations


MX_UINT16 FCD_EEPROM0_EEPROMRead(MX_UINT16 addr)
{
	
		return (FC_CAL_EE_Read (addr));

}

void FCD_EEPROM0_WriteEEPROM(MX_UINT16 addr, MX_UINT16 data)
{
	
		FC_CAL_EE_Write (addr, data);

}



//RS232(0): //Macro implementations


void FCD_RS2320_SendRS232Char(MX_SINT16 nChar)
{
	
		RS232_7_UART_Send ( nChar);

}

void FCD_RS2320_SendRS232String(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx;
		for(idx = 0; idx < MSZ_String; idx++)
		{
			if (String[idx] == 0)
				break;
			else RS232_7_UART_Send ( String[idx] );
		}

}

MX_SINT16 FCD_RS2320_ReceiveRS232Char(MX_UINT8 nTimeout)
{
	
		return ( RS232_7_UART_Receive ( nTimeout) );

}

void FCD_RS2320_ReceiveRS232String(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE, MX_UINT8 nTimeout, MX_UINT8 NumBytes)
{
	
		MX_UINT8 idx;
		MX_SINT16 RS232_TO = 255;
		MX_SINT16 in;

		if ( 0 != 0 )
			RS232_TO = 256;

		if (NumBytes > FCR_RETVAL_SIZE)
			NumBytes = FCR_RETVAL_SIZE;

		for (idx = 0; idx < NumBytes; idx++)
		{
			in = RS232_7_UART_Receive ( nTimeout);
			if(in < RS232_TO)
				FCR_RETVAL[idx] = in & 0xFF;
			else
				break;
		}

		if (idx < FCR_RETVAL_SIZE)
			FCR_RETVAL[idx] = 0;

}

void FCD_RS2320_ChangeHWBaud(MX_UINT8 newbaud)
{
	
		RS232_7_UART_Update_Baud (newbaud);

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_scan1()
{

	//Output
	//Output: 0 -> A0
	trisa = trisa & 0xFE;
	if ((0))
		porta = (porta & 0xFE) | 0x01;
	else
		porta = porta & 0xFE;

	//Output
	//Output: 0 -> A1
	trisa = trisa & 0xFD;
	if ((0))
		porta = (porta & 0xFD) | 0x02;
	else
		porta = porta & 0xFD;

	//Output
	//Output: 0 -> A2
	trisa = trisa & 0xFB;
	if ((0))
		porta = (porta & 0xFB) | 0x04;
	else
		porta = porta & 0xFB;

	//Output
	//Output: 1 -> A3
	trisa = trisa & 0xF7;
	if ((1))
		porta = (porta & 0xF7) | 0x08;
	else
		porta = porta & 0xF7;

}


void FCM_scan2()
{

	//Output
	//Output: 0 -> A0
	trisa = trisa & 0xFE;
	if ((0))
		porta = (porta & 0xFE) | 0x01;
	else
		porta = porta & 0xFE;

	//Output
	//Output: 0 -> A1
	trisa = trisa & 0xFD;
	if ((0))
		porta = (porta & 0xFD) | 0x02;
	else
		porta = porta & 0xFD;

	//Output
	//Output: 1 -> A2
	trisa = trisa & 0xFB;
	if ((1))
		porta = (porta & 0xFB) | 0x04;
	else
		porta = porta & 0xFB;

	//Output
	//Output: 0 -> A3
	trisa = trisa & 0xF7;
	if ((0))
		porta = (porta & 0xF7) | 0x08;
	else
		porta = porta & 0xF7;

}


void FCM_scan3()
{

	//Output
	//Output: 0 -> A0
	trisa = trisa & 0xFE;
	if ((0))
		porta = (porta & 0xFE) | 0x01;
	else
		porta = porta & 0xFE;

	//Output
	//Output: 1 -> A1
	trisa = trisa & 0xFD;
	if ((1))
		porta = (porta & 0xFD) | 0x02;
	else
		porta = porta & 0xFD;

	//Output
	//Output: 0 -> A2
	trisa = trisa & 0xFB;
	if ((0))
		porta = (porta & 0xFB) | 0x04;
	else
		porta = porta & 0xFB;

	//Output
	//Output: 0 -> A3
	trisa = trisa & 0xF7;
	if ((0))
		porta = (porta & 0xF7) | 0x08;
	else
		porta = porta & 0xF7;

}


void FCM_scan4()
{

	//Output
	//Output: 1 -> A0
	trisa = trisa & 0xFE;
	if ((1))
		porta = (porta & 0xFE) | 0x01;
	else
		porta = porta & 0xFE;

	//Output
	//Output: 0 -> A1
	trisa = trisa & 0xFD;
	if ((0))
		porta = (porta & 0xFD) | 0x02;
	else
		porta = porta & 0xFD;

	//Output
	//Output: 0 -> A2
	trisa = trisa & 0xFB;
	if ((0))
		porta = (porta & 0xFB) | 0x04;
	else
		porta = porta & 0xFB;

	//Output
	//Output: 0 -> A3
	trisa = trisa & 0xF7;
	if ((0))
		porta = (porta & 0xF7) | 0x08;
	else
		porta = porta & 0xF7;

}


void FCM_scan_off()
{

	//Output
	//Output: 0 -> A0
	trisa = trisa & 0xFE;
	if ((0))
		porta = (porta & 0xFE) | 0x01;
	else
		porta = porta & 0xFE;

	//Output
	//Output: 0 -> A1
	trisa = trisa & 0xFD;
	if ((0))
		porta = (porta & 0xFD) | 0x02;
	else
		porta = porta & 0xFD;

	//Output
	//Output: 0 -> A2
	trisa = trisa & 0xFB;
	if ((0))
		porta = (porta & 0xFB) | 0x04;
	else
		porta = porta & 0xFB;

	//Output
	//Output: 0 -> A3
	trisa = trisa & 0xF7;
	if ((0))
		porta = (porta & 0xF7) | 0x08;
	else
		porta = porta & 0xF7;

}


void FCM_test()
{

	//Output
	//Output: 0 -> B0
	trisb = trisb & 0xFE;
	if ((0))
		portb = (portb & 0xFE) | 0x01;
	else
		portb = portb & 0xFE;

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Output
	//Output: 1 -> B1
	trisb = trisb & 0xFD;
	if ((1))
		portb = (portb & 0xFD) | 0x02;
	else
		portb = portb & 0xFD;

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Output
	//Output: 1 -> B2
	trisb = trisb & 0xFB;
	if ((1))
		portb = (portb & 0xFB) | 0x04;
	else
		portb = portb & 0xFB;

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Output
	//Output: 1 -> B3
	trisb = trisb & 0xF7;
	if ((1))
		portb = (portb & 0xF7) | 0x08;
	else
		portb = portb & 0xF7;

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Output
	//Output: 1 -> B4
	trisb = trisb & 0xEF;
	if ((1))
		portb = (portb & 0xEF) | 0x10;
	else
		portb = portb & 0xEF;

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Output
	//Output: 1 -> B5
	trisb = trisb & 0xDF;
	if ((1))
		portb = (portb & 0xDF) | 0x20;
	else
		portb = portb & 0xDF;

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Output
	//Output: 1 -> B6
	trisb = trisb & 0xBF;
	if ((1))
		portb = (portb & 0xBF) | 0x40;
	else
		portb = portb & 0xBF;

	//Delay
	//Delay: 1 s
	delay_s(1);

	//Output
	//Output: 1 -> B7
	trisb = trisb & 0x7F;
	if ((1))
		portb = (portb & 0x7F) | 0x80;
	else
		portb = portb & 0x7F;

	//Delay
	//Delay: 1 s
	delay_s(1);

}


void FCM_seg_pattern()
{

	//Switch
	//Switch: digit?
	switch (FCV_DIGIT)
	{
		case 1:
		{
			//Output
			//Output: 0b00010011 -> PORTB
			trisb = 0x00;
			portb = (19);

			break;
		}
		case 2:
		{
			//Output
			//Output: 0b10111101 -> PORTB
			trisb = 0x00;
			portb = (189);

			break;
		}
		case 3:
		{
			//Output
			//Output: 0b10110111 -> PORTB
			trisb = 0x00;
			portb = (183);

			break;
		}
		case 4:
		{
			//Output
			//Output: 0b11010011 -> PORTB
			trisb = 0x00;
			portb = (211);

			break;
		}
		case 5:
		{
			//Output
			//Output: 0b11100111 -> PORTB
			trisb = 0x00;
			portb = (231);

			break;
		}
		case 6:
		{
			//Output
			//Output: 0b11101111 -> PORTB
			trisb = 0x00;
			portb = (239);

			break;
		}
		case 7:
		{
			//Output
			//Output: 0b00110011 -> PORTB
			trisb = 0x00;
			portb = (51);

			break;
		}
		case 8:
		{
			//Output
			//Output: 0b11111111 -> PORTB
			trisb = 0x00;
			portb = (255);

			break;
		}
		case 9:
		{
			//Output
			//Output: 0b11110111 -> PORTB
			trisb = 0x00;
			portb = (247);

			break;
		}
		case 0:
		{
			//Connection Point
			//Connection Point: [A]: A
FCC_seg_pattern_A:
;

			//Output
			//Output: 0b01111111 -> PORTB
			trisb = 0x00;
			portb = (127);

			break;
		}
		default:
		{
			//Goto Connection Point
			//Goto Connection Point: [A]: A
			goto FCC_seg_pattern_A;

		}
	}

}


void FCM_display_temp()
{

	//Calculation
	//Calculation:
	//  temp_tens = temp_c / 10
	//  temp_ones = temp_c MOD 10
	//  temp_dec = temp_cdp
	FCV_TEMP_TENS = FCV_TEMP_C / 10;
	FCV_TEMP_ONES = FCV_TEMP_C % 10;
	FCV_TEMP_DEC = FCV_TEMP_CDP;

	//Output
	//Output: 0b00000001 -> PORTB
	trisb = 0x00;
	portb = (1);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan1()
	FCM_scan1();

	//Calculation
	//Calculation:
	//  digit = temp_tens
	FCV_DIGIT = FCV_TEMP_TENS;

	//Call Macro
	//Call Macro: seg_pattern()
	FCM_seg_pattern();

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Output
	//Output: 0b00000001 -> PORTB
	trisb = 0x00;
	portb = (1);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan2()
	FCM_scan2();

	//Calculation
	//Calculation:
	//  digit = temp_ones
	FCV_DIGIT = FCV_TEMP_ONES;

	//Call Macro
	//Call Macro: seg_pattern()
	FCM_seg_pattern();

	//Output
	//Output: 0 -> B0
	trisb = trisb & 0xFE;
	if ((0))
		portb = (portb & 0xFE) | 0x01;
	else
		portb = portb & 0xFE;

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Output
	//Output: 0b00000001 -> PORTB
	trisb = 0x00;
	portb = (1);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan3()
	FCM_scan3();

	//Calculation
	//Calculation:
	//  digit = temp_dec
	FCV_DIGIT = FCV_TEMP_DEC;

	//Call Macro
	//Call Macro: seg_pattern()
	FCM_seg_pattern();

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Output
	//Output: 0b00000001 -> PORTB
	trisb = 0x00;
	portb = (1);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan4()
	FCM_scan4();

	//Output
	//Output: 0b11100000 -> PORTB
	trisb = 0x00;
	portb = (224);

	//Delay
	//Delay: 4 ms
	delay_ms(4);

}


void FCM_all_input()
{

	//Input
	//Input: C0 -> prox_bit
	trisc = trisc | 0x01;
	FCV_PROX_BIT = ((portc & 0x01) == 0x01);

	//Input
	//Input: A4 -> swg
	trisa = trisa | 0x10;
	FCV_SWG = ((porta & 0x10) == 0x10);

	//Input
	//Input: C2 -> swr
	trisc = trisc | 0x04;
	FCV_SWR = ((portc & 0x04) == 0x04);

}


void FCM_pass()
{

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED0_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED1_LEDOn();

}


void FCM_failed()
{

	//Call Component Macro
	//Call Component Macro: LEDOn()
	FCD_LED0_LEDOn();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED1_LEDOff();

}


void FCM_calc()
{

	//Calculation
	//Calculation:
	//  lsb = data0
	//  msb = data1
	FCV_LSB = FCV_DATA0;
	FCV_MSB = FCV_DATA1;

	//Calculation
	//Calculation:
	//  raw = msb
	FCV_RAW = FCV_MSB;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP3=0; FCLV_LOOP3<8; FCLV_LOOP3++)
	{

		//Calculation
		//Calculation:
		//  raw = raw << 1
		FCV_RAW = FCV_RAW << 1;


	}

	//Calculation
	//Calculation:
	//  raw = raw + lsb
	FCV_RAW = FCV_RAW + FCV_LSB;

	//Calculation
	//Calculation:
	//  temp_c = (raw / 50) - calib_subtractor
	FCV_TEMP_C = (FCV_RAW / 50) - FCV_CALIB_SUBTRACTOR;

	//Calculation
	//Calculation:
	//  dp2 = raw % 50
	FCV_DP2 = FCV_RAW % 50;

	//Decision
	//Decision: dp2 >= 100?
	if (FCV_DP2 >= 100)
	{

		//Calculation
		//Calculation:
		//  temp_cdp = dp2 / 100
		FCV_TEMP_CDP = FCV_DP2 / 100;

	} else {

		//Decision
		//Decision: dp2 >= 10 AND dp2 <= 100?
		if (FCV_DP2 >= 10 & FCV_DP2 <= 100)
		{

			//Calculation
			//Calculation:
			//  temp_cdp = dp2 / 10
			FCV_TEMP_CDP = FCV_DP2 / 10;

		} else {

			//Decision
			//Decision: dp2 < 10?
			if (FCV_DP2 < 10)
			{

				//Calculation
				//Calculation:
				//  temp_cdp = dp2
				FCV_TEMP_CDP = FCV_DP2;

			// } else {

			}

		}

	}

	//Calculation
	//Calculation:
	//  temp_cdp = temp_cdp + calib_offset
	FCV_TEMP_CDP = FCV_TEMP_CDP + FCV_CALIB_OFFSET;

}


void FCM_i2c_comm()
{

	//Call Component Macro
	//Call Component Macro: MI2C_Start()
	FCD_I2C_Master0_MI2C_Start();

	//Calculation
	//Calculation:
	//  rt_byte = 0
	FCV_RT_BYTE = 0;

	//Call Component Macro
	//Call Component Macro: rt_byte=MI2C_Transmit_Byte(0xB4)
	FCV_RT_BYTE = FCD_I2C_Master0_MI2C_Transmit_Byte(0xB4);

	//Calculation
	//Calculation:
	//  rt_byte = 0
	FCV_RT_BYTE = 0;

	//Call Component Macro
	//Call Component Macro: rt_byte=MI2C_Transmit_Byte(0x07)
	FCV_RT_BYTE = FCD_I2C_Master0_MI2C_Transmit_Byte(0x07);

	//Comment:
	//end of RD/WR cmd

	//Call Component Macro
	//Call Component Macro: MI2C_Restart()
	FCD_I2C_Master0_MI2C_Restart();

	//Calculation
	//Calculation:
	//  rt_byte = 0
	FCV_RT_BYTE = 0;

	//Call Component Macro
	//Call Component Macro: rt_byte=MI2C_Transmit_Byte(0xB4)
	FCV_RT_BYTE = FCD_I2C_Master0_MI2C_Transmit_Byte(0xB4);

	//Call Component Macro
	//Call Component Macro: i2c_rx=MI2C_Receive_Byte(rt_byte)
	FCV_I2C_RX = FCD_I2C_Master0_MI2C_Receive_Byte(FCV_RT_BYTE);

	//Calculation
	//Calculation:
	//  data0 = i2c_rx
	FCV_DATA0 = FCV_I2C_RX;

	//Call Component Macro
	//Call Component Macro: i2c_rx=MI2C_Receive_Byte(rt_byte)
	FCV_I2C_RX = FCD_I2C_Master0_MI2C_Receive_Byte(FCV_RT_BYTE);

	//Calculation
	//Calculation:
	//  data1 = i2c_rx
	FCV_DATA1 = FCV_I2C_RX;

	//Call Component Macro
	//Call Component Macro: i2c_rx=MI2C_Receive_Byte(rt_byte)
	FCV_I2C_RX = FCD_I2C_Master0_MI2C_Receive_Byte(FCV_RT_BYTE);

	//Calculation
	//Calculation:
	//  data2 = i2c_rx
	FCV_DATA2 = FCV_I2C_RX;

	//Call Component Macro
	//Call Component Macro: MI2C_Stop()
	FCD_I2C_Master0_MI2C_Stop();

}


void FCM_lights_off()
{

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED0_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED1_LEDOff();

}


void FCM_beep_once()
{

	//Call Component Macro
	//Call Component Macro: SetDutyCycle(160)
	FCD_PWM0_SetDutyCycle(160);

	//Delay
	//Delay: 100 ms
	delay_ms(100);

	//Call Component Macro
	//Call Component Macro: SetDutyCycle(0)
	FCD_PWM0_SetDutyCycle(0);

}


void FCM_get_temp()
{

	//Connection Point
	//Connection Point: [A]: A
FCC_get_temp_A:
;

	//Call Macro
	//Call Macro: i2c_comm()
	FCM_i2c_comm();

	//Calculation
	//Calculation:
	//  data_prev = data1
	FCV_DATA_PREV = FCV_DATA1;

	//Call Macro
	//Call Macro: i2c_comm()
	FCM_i2c_comm();

	//Calculation
	//Calculation:
	//  data_diff = data_prev - data1
	FCV_DATA_DIFF = FCV_DATA_PREV - FCV_DATA1;

	//Decision
	//Decision: data_diff > 10?
	if (FCV_DATA_DIFF > 10)
	{

		//Goto Connection Point
		//Goto Connection Point: [A]: A
		goto FCC_get_temp_A;

	// } else {

	}

	//Connection Point
	//Connection Point: [B]: B
FCC_get_temp_B:
;

	//Call Macro
	//Call Macro: i2c_comm()
	FCM_i2c_comm();

	//Calculation
	//Calculation:
	//  data_prev = data1
	FCV_DATA_PREV = FCV_DATA1;

	//Call Macro
	//Call Macro: i2c_comm()
	FCM_i2c_comm();

	//Calculation
	//Calculation:
	//  data_diff = data_prev - data1
	FCV_DATA_DIFF = FCV_DATA_PREV - FCV_DATA1;

	//Decision
	//Decision: data_diff > 10?
	if (FCV_DATA_DIFF > 10)
	{

		//Goto Connection Point
		//Goto Connection Point: [B]: B
		goto FCC_get_temp_B;

	// } else {

	}

	//Call Macro
	//Call Macro: calc()
	FCM_calc();

}


void FCM_display_repeat()
{

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan1()
	FCM_scan1();

	//Output
	//Output: 0b10000001 -> PORTB
	trisb = 0x00;
	portb = (129);

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan2()
	FCM_scan2();

	//Output
	//Output: 0b10000001 -> PORTB
	trisb = 0x00;
	portb = (129);

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan3()
	FCM_scan3();

	//Output
	//Output: 0b10000001 -> PORTB
	trisb = 0x00;
	portb = (129);

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Output
	//Output: 0b10000001 -> PORTB
	trisb = 0x00;
	portb = (129);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan4()
	FCM_scan4();

	//Output
	//Output: 0b11100000 -> PORTB
	trisb = 0x00;
	portb = (224);

	//Delay
	//Delay: 4 ms
	delay_ms(4);

}


void FCM_repeat()
{

	//Loop
	//Loop: Loop 10 times
	for (FCLV_LOOP4=0; FCLV_LOOP4<10; FCLV_LOOP4++)
	{

		//Call Macro
		//Call Macro: display_repeat()
		FCM_display_repeat();

		//Call Macro
		//Call Macro: lights_off()
		FCM_lights_off();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(0)
		FCD_PWM0_SetDutyCycle(0);


	}

	//Loop
	//Loop: Loop 10 times
	for (FCLV_LOOP5=0; FCLV_LOOP5<10; FCLV_LOOP5++)
	{

		//Call Macro
		//Call Macro: display_repeat()
		FCM_display_repeat();

		//Call Macro
		//Call Macro: lights_off()
		FCM_lights_off();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(160)
		FCD_PWM0_SetDutyCycle(160);


	}

	//Loop
	//Loop: Loop 10 times
	for (FCLV_LOOP6=0; FCLV_LOOP6<10; FCLV_LOOP6++)
	{

		//Call Macro
		//Call Macro: display_repeat()
		FCM_display_repeat();

		//Call Macro
		//Call Macro: lights_off()
		FCM_lights_off();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(0)
		FCD_PWM0_SetDutyCycle(0);


	}

	//Loop
	//Loop: Loop 10 times
	for (FCLV_LOOP7=0; FCLV_LOOP7<10; FCLV_LOOP7++)
	{

		//Call Macro
		//Call Macro: display_repeat()
		FCM_display_repeat();

		//Call Macro
		//Call Macro: lights_off()
		FCM_lights_off();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(160)
		FCD_PWM0_SetDutyCycle(160);


	}

	//Loop
	//Loop: Loop 10 times
	for (FCLV_LOOP8=0; FCLV_LOOP8<10; FCLV_LOOP8++)
	{

		//Call Macro
		//Call Macro: display_repeat()
		FCM_display_repeat();

		//Call Macro
		//Call Macro: lights_off()
		FCM_lights_off();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(0)
		FCD_PWM0_SetDutyCycle(0);


	}

	//Loop
	//Loop: Loop 10 times
	for (FCLV_LOOP9=0; FCLV_LOOP9<10; FCLV_LOOP9++)
	{

		//Call Macro
		//Call Macro: display_repeat()
		FCM_display_repeat();

		//Call Macro
		//Call Macro: lights_off()
		FCM_lights_off();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(160)
		FCD_PWM0_SetDutyCycle(160);


	}

	//Loop
	//Loop: Loop 10 times
	for (FCLV_LOOP10=0; FCLV_LOOP10<10; FCLV_LOOP10++)
	{

		//Call Macro
		//Call Macro: display_repeat()
		FCM_display_repeat();

		//Call Macro
		//Call Macro: lights_off()
		FCM_lights_off();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(0)
		FCD_PWM0_SetDutyCycle(0);


	}

}


void FCM_display_fail()
{

	//Loop
	//Loop: Loop 90 times
	for (FCLV_LOOP11=0; FCLV_LOOP11<90; FCLV_LOOP11++)
	{

		//Call Macro
		//Call Macro: display_temp()
		FCM_display_temp();

		//Call Macro
		//Call Macro: failed()
		FCM_failed();

		//Call Component Macro
		//Call Component Macro: SetDutyCycle(160)
		FCD_PWM0_SetDutyCycle(160);


	}

}


void FCM_calibrate()
{

	//Call Macro
	//Call Macro: lights_off()
	FCM_lights_off();

	//Loop
	//Loop: While swg = 0 OR swr = 0
	while (FCV_SWG == 0 | FCV_SWR == 0)
	{

		//Call Macro
		//Call Macro: all_input()
		FCM_all_input();

		//Call Macro
		//Call Macro: display_temp_calib()
		FCM_display_temp_calib();


	}

	//Calculation
	//Calculation:
	//  calib_count = 0
	FCV_CALIB_COUNT = 0;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Connection Point
		//Connection Point: [A]: A
FCC_calibrate_A:
;

		//Calculation
		//Calculation:
		//  reset_counter = 0
		FCV_RESET_COUNTER = 0;

		//Call Macro
		//Call Macro: all_input()
		FCM_all_input();

		//Decision
		//Decision: swg = 0 AND swr = 1?
		if (FCV_SWG == 0 & FCV_SWR == 1)
		{

			//Calculation
			//Calculation:
			//  calib_count = 0
			FCV_CALIB_COUNT = 0;

			//Calculation
			//Calculation:
			//  temp_cdp = temp_cdp + 1
			//  calib_offset = calib_offset + 1
			FCV_TEMP_CDP = FCV_TEMP_CDP + 1;
			FCV_CALIB_OFFSET = FCV_CALIB_OFFSET + 1;

			//Decision
			//Decision: calib_offset > 9?
			if (FCV_CALIB_OFFSET > 9)
			{

				//Calculation
				//Calculation:
				//  calib_offset = 0
				FCV_CALIB_OFFSET = 0;

			// } else {

			}

			//Decision
			//Decision: temp_cdp > 9?
			if (FCV_TEMP_CDP > 9)
			{

				//Calculation
				//Calculation:
				//  calib_subtractor = calib_subtractor - 1
				//  temp_c = temp_c + 1
				//  temp_cdp = 0
				FCV_CALIB_SUBTRACTOR = FCV_CALIB_SUBTRACTOR - 1;
				FCV_TEMP_C = FCV_TEMP_C + 1;
				FCV_TEMP_CDP = 0;

			// } else {

			}

			//Loop
			//Loop: While swg = 0
			while (FCV_SWG == 0)
			{

				//Call Macro
				//Call Macro: all_input()
				FCM_all_input();

				//Call Macro
				//Call Macro: display_temp_calib()
				FCM_display_temp_calib();


			}

		} else {

			//Decision
			//Decision: swg = 1 AND swr = 0?
			if (FCV_SWG == 1 & FCV_SWR == 0)
			{

				//Calculation
				//Calculation:
				//  calib_count = 0
				FCV_CALIB_COUNT = 0;

				//Calculation
				//Calculation:
				//  temp_cdp = temp_cdp - 1
				//  calib_offset = calib_offset - 1
				FCV_TEMP_CDP = FCV_TEMP_CDP - 1;
				FCV_CALIB_OFFSET = FCV_CALIB_OFFSET - 1;

				//Decision
				//Decision: calib_offset < 0?
				if (FCV_CALIB_OFFSET < 0)
				{

					//Calculation
					//Calculation:
					//  calib_offset = 9
					FCV_CALIB_OFFSET = 9;

				// } else {

				}

				//Decision
				//Decision: temp_cdp < 0?
				if (FCV_TEMP_CDP < 0)
				{

					//Calculation
					//Calculation:
					//  calib_subtractor = calib_subtractor + 1
					//  temp_c = temp_c - 1
					//  temp_cdp = 9
					FCV_CALIB_SUBTRACTOR = FCV_CALIB_SUBTRACTOR + 1;
					FCV_TEMP_C = FCV_TEMP_C - 1;
					FCV_TEMP_CDP = 9;

				// } else {

				}

				//Loop
				//Loop: While swr = 0
				while (FCV_SWR == 0)
				{

					//Call Macro
					//Call Macro: all_input()
					FCM_all_input();

					//Call Macro
					//Call Macro: display_temp_calib()
					FCM_display_temp_calib();

					//Decision
					//Decision: reset_counter = 255?
					if (FCV_RESET_COUNTER == 255)
					{

						//Call Macro
						//Call Macro: repeat()
						FCM_repeat();

						//Call Component Macro
						//Call Component Macro: Write(1, 21)
						FCD_EEPROM0_WriteEEPROM(1, 21);

						//Call Component Macro
						//Call Component Macro: Write(2, 3)
						FCD_EEPROM0_WriteEEPROM(2, 3);

						//Delay
						//Delay: 100 ms
						delay_ms(100);

						//Goto Connection Point
						//Goto Connection Point: [C]: C
						goto FCC_calibrate_C;

					} else {

						//Calculation
						//Calculation:
						//  reset_counter = reset_counter + 1
						FCV_RESET_COUNTER = FCV_RESET_COUNTER + 1;

					}


				}

			// } else {

			}

		}

		//Call Macro
		//Call Macro: display_temp_calib()
		FCM_display_temp_calib();

		//Calculation
		//Calculation:
		//  calib_count = calib_count + 1
		FCV_CALIB_COUNT = FCV_CALIB_COUNT + 1;

		//Decision
		//Decision: calib_count = 150?
		if (FCV_CALIB_COUNT == 150)
		{

			//Goto Connection Point
			//Goto Connection Point: [B]: B
			goto FCC_calibrate_B;

		// } else {

		}


	}

	//Connection Point
	//Connection Point: [B]: B
FCC_calibrate_B:
;

	//Calculation
	//Calculation:
	//  save_calib0 = calib_subtractor - 250
	//  save_calib1 = calib_offset
	FCV_SAVE_CALIB0 = FCV_CALIB_SUBTRACTOR - 250;
	FCV_SAVE_CALIB1 = FCV_CALIB_OFFSET;

	//Call Component Macro
	//Call Component Macro: Write(1, save_calib0)
	FCD_EEPROM0_WriteEEPROM(1, FCV_SAVE_CALIB0);

	//Call Component Macro
	//Call Component Macro: Write(2, save_calib1)
	FCD_EEPROM0_WriteEEPROM(2, FCV_SAVE_CALIB1);

	//Delay
	//Delay: 100 ms
	delay_ms(100);

	//Connection Point
	//Connection Point: [C]: C
FCC_calibrate_C:
;

}


void FCM_display_temp_calib()
{

	//Calculation
	//Calculation:
	//  temp_tens = temp_c / 10
	//  temp_ones = temp_c MOD 10
	//  temp_dec = temp_cdp
	FCV_TEMP_TENS = FCV_TEMP_C / 10;
	FCV_TEMP_ONES = FCV_TEMP_C % 10;
	FCV_TEMP_DEC = FCV_TEMP_CDP;

	//Output
	//Output: 0b00000001 -> PORTB
	trisb = 0x00;
	portb = (1);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan1()
	FCM_scan1();

	//Calculation
	//Calculation:
	//  digit = temp_tens
	FCV_DIGIT = FCV_TEMP_TENS;

	//Call Macro
	//Call Macro: seg_pattern()
	FCM_seg_pattern();

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Output
	//Output: 0b00000001 -> PORTB
	trisb = 0x00;
	portb = (1);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan2()
	FCM_scan2();

	//Calculation
	//Calculation:
	//  digit = temp_ones
	FCV_DIGIT = FCV_TEMP_ONES;

	//Call Macro
	//Call Macro: seg_pattern()
	FCM_seg_pattern();

	//Output
	//Output: 0 -> B0
	trisb = trisb & 0xFE;
	if ((0))
		portb = (portb & 0xFE) | 0x01;
	else
		portb = portb & 0xFE;

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Output
	//Output: 0b00000001 -> PORTB
	trisb = 0x00;
	portb = (1);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan3()
	FCM_scan3();

	//Calculation
	//Calculation:
	//  digit = temp_dec
	FCV_DIGIT = FCV_TEMP_DEC;

	//Call Macro
	//Call Macro: seg_pattern()
	FCM_seg_pattern();

	//Delay
	//Delay: 4 ms
	delay_ms(4);

	//Output
	//Output: 0b00000001 -> PORTB
	trisb = 0x00;
	portb = (1);

	//Call Macro
	//Call Macro: scan_off()
	FCM_scan_off();

	//Call Macro
	//Call Macro: scan4()
	FCM_scan4();

	//Output
	//Output: 0b11110000 -> PORTB
	trisb = 0x00;
	portb = (240);

	//Delay
	//Delay: 4 ms
	delay_ms(4);

}


void FCM_calc_calib()
{

}



void main()
{
	//Initialization
	adcon1 = 0x07;

	
		RS232_7_UART_Init( );		//Call initialise function


	//Interrupt initialization code
	option_reg = 0xC0;


	//Calculation
	//Calculation:
	//  data0 = 123
	//  data1 = 0xff
	//  data2 = 0xff
	//  lsb = 0x00
	//  msb = 0x00
	FCV_DATA0 = 123;
	FCV_DATA1 = 0xff;
	FCV_DATA2 = 0xff;
	FCV_LSB = 0x00;
	FCV_MSB = 0x00;

	//Calculation
	//Calculation:
	//  temp_tens = 0
	//  temp_ones = 0
	//  temp_dec = 0
	FCV_TEMP_TENS = 0;
	FCV_TEMP_ONES = 0;
	FCV_TEMP_DEC = 0;

	//Call Component Macro
	//Call Component Macro: MI2C_Init()
	FCD_I2C_Master0_MI2C_Init();

	//Call Component Macro
	//Call Component Macro: Enable()
	FCD_PWM0_Enable();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED0_LEDOff();

	//Call Component Macro
	//Call Component Macro: LEDOff()
	FCD_LED1_LEDOff();

	//Delay
	//Delay: 300 ms
	delay_ms(255);
	delay_ms(45);

	//Loop
	//Loop: While 1
	while (1)
	{

		//Call Macro
		//Call Macro: lights_off()
		FCM_lights_off();

		//Call Component Macro
		//Call Component Macro: calib_subtractor=Read(1)
		FCV_CALIB_SUBTRACTOR = FCD_EEPROM0_EEPROMRead(1);

		//Call Component Macro
		//Call Component Macro: calib_offset=Read(2)
		FCV_CALIB_OFFSET = FCD_EEPROM0_EEPROMRead(2);

		//Calculation
		//Calculation:
		//  calib_subtractor = calib_subtractor + 250
		FCV_CALIB_SUBTRACTOR = FCV_CALIB_SUBTRACTOR + 250;

		//Connection Point
		//Connection Point: [A]: A
FCC_Main_A:
;

		//Calculation
		//Calculation:
		//  prox_counter = 0
		//  sw_calib = 0
		FCV_PROX_COUNTER = 0;
		FCV_SW_CALIB = 0;

		//Connection Point
		//Connection Point: [B]: B
FCC_Main_B:
;

		//Call Macro
		//Call Macro: all_input()
		FCM_all_input();

		//Decision
		//Decision: prox_bit = 0?
		if (FCV_PROX_BIT == 0)
		{

			//Decision
			//Decision: prox_counter = 10?
			if (FCV_PROX_COUNTER == 10)
			{

			} else {

				//Delay
				//Delay: 30 ms
				delay_ms(30);

				//Calculation
				//Calculation:
				//  prox_counter = prox_counter + 1
				FCV_PROX_COUNTER = FCV_PROX_COUNTER + 1;

				//Goto Connection Point
				//Goto Connection Point: [B]: B
				goto FCC_Main_B;

			}

			//Call Macro
			//Call Macro: beep_once()
			FCM_beep_once();

			//Call Macro
			//Call Macro: get_temp()
			FCM_get_temp();

			//Calculation
			//Calculation:
			//  temp_tens = temp_c / 10
			//  temp_ones = temp_c MOD 10
			//  temp_dec = temp_cdp
			FCV_TEMP_TENS = FCV_TEMP_C / 10;
			FCV_TEMP_ONES = FCV_TEMP_C % 10;
			FCV_TEMP_DEC = FCV_TEMP_CDP;

			//Decision
			//Decision: temp_c < 34?
			if (FCV_TEMP_C < 34)
			{

				//Call Macro
				//Call Macro: repeat()
				FCM_repeat();

			} else {

				//Decision
				//Decision: temp_c >= 38?
				if (FCV_TEMP_C >= 38)
				{

					//Connection Point
					//Connection Point: [C]: C
FCC_Main_C:
;

					//Call Component Macro
					//Call Component Macro: SendRS232String("FAIL")
					FCD_RS2320_SendRS232String("FAIL", 4);

					//Call Macro
					//Call Macro: display_fail()
					FCM_display_fail();

				} else {

					//Decision
					//Decision: temp_c = 37 AND temp_cdp >= 8?
					if (FCV_TEMP_C == 37 & FCV_TEMP_CDP >= 8)
					{

						//Goto Connection Point
						//Goto Connection Point: [C]: C
						goto FCC_Main_C;

					} else {

						//Loop
						//Loop: Loop 90 times
						for (FCLV_LOOP2=0; FCLV_LOOP2<90; FCLV_LOOP2++)
						{

							//Call Macro
							//Call Macro: display_temp()
							FCM_display_temp();

							//Call Macro
							//Call Macro: pass()
							FCM_pass();


						}

						//Call Component Macro
						//Call Component Macro: ret_byte=ReceiveRS232Char(temp_tens)
						FCV_RET_BYTE = FCD_RS2320_ReceiveRS232Char(FCV_TEMP_TENS);

						//Call Component Macro
						//Call Component Macro: ret_byte=ReceiveRS232Char(temp_ones)
						FCV_RET_BYTE = FCD_RS2320_ReceiveRS232Char(FCV_TEMP_ONES);

						//Call Component Macro
						//Call Component Macro: ret_byte=ReceiveRS232Char('.')
						FCV_RET_BYTE = FCD_RS2320_ReceiveRS232Char('.');

						//Call Component Macro
						//Call Component Macro: ret_byte=ReceiveRS232Char(temp_dec)
						FCV_RET_BYTE = FCD_RS2320_ReceiveRS232Char(FCV_TEMP_DEC);

					}

				}

			}

			//Call Macro
			//Call Macro: scan_off()
			FCM_scan_off();

			//Loop
			//Loop: While prox_bit = 0
			while (FCV_PROX_BIT == 0)
			{

				//Call Macro
				//Call Macro: all_input()
				FCM_all_input();


			}

		} else {

			//Delay
			//Delay: 100 ms
			delay_ms(100);

			//Decision
			//Decision: swg = 0 AND swr = 0?
			if (FCV_SWG == 0 & FCV_SWR == 0)
			{

				//Decision
				//Decision: sw_calib = 10?
				if (FCV_SW_CALIB == 10)
				{

				} else {

					//Delay
					//Delay: 30 ms
					delay_ms(30);

					//Calculation
					//Calculation:
					//  sw_calib = sw_calib + 1
					FCV_SW_CALIB = FCV_SW_CALIB + 1;

					//Goto Connection Point
					//Goto Connection Point: [B]: B
					goto FCC_Main_B;

				}

				//Call Macro
				//Call Macro: calibrate()
				FCM_calibrate();

			} else {

				//Decision
				//Decision: swg = 1 AND swr = 0?
				if (FCV_SWG == 1 & FCV_SWR == 0)
				{

					//Loop
					//Loop: Loop 30 times
					for (FCLV_LOOP1=0; FCLV_LOOP1<30; FCLV_LOOP1++)
					{

						//Call Macro
						//Call Macro: all_input()
						FCM_all_input();

						//Delay
						//Delay: 100 ms
						delay_ms(100);

						//Decision
						//Decision: swr = 1?
						if (FCV_SWR == 1)
						{

							//Goto Connection Point
							//Goto Connection Point: [A]: A
							goto FCC_Main_A;

						// } else {

						}


					}

					//Output
					//Output: 1 -> C5
					trisc = trisc & 0xDF;
					if ((1))
						portc = (portc & 0xDF) | 0x20;
					else
						portc = portc & 0xDF;

					//Delay
					//Delay: 3 s
					delay_s(3);

					//Output
					//Output: 0 -> C5
					trisc = trisc & 0xDF;
					if ((0))
						portc = (portc & 0xDF) | 0x20;
					else
						portc = portc & 0xDF;

				} else {

					//Call Macro
					//Call Macro: scan_off()
					FCM_scan_off();

					//Call Component Macro
					//Call Component Macro: SetDutyCycle(0)
					FCD_PWM0_SetDutyCycle(0);

				}

			}

		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



