# MPLAB IDE generated this makefile for use with GNU make.
# Project: HUB12_RTC.mcp
# Date: Thu Jun 27 19:27:21 2019

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

HUB12_RTC5_fixdisplay.cof : HUB12_RTC5_fixdisplay.o
	$(CC) /p16F690 "HUB12_RTC5_fixdisplay.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"HUB12_RTC5_fixdisplay.cof" /M"HUB12_RTC5_fixdisplay.map" /W /x

HUB12_RTC5_fixdisplay.o : HUB12_RTC5_fixdisplay.ASM ../../../../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F690.inc
	$(AS) /q /p16F690 "HUB12_RTC5_fixdisplay.ASM" /l"HUB12_RTC5_fixdisplay.lst" /e"HUB12_RTC5_fixdisplay.err" /d__DEBUG=1

clean : 
	$(CC) "HUB12_RTC5_fixdisplay.o" "HUB12_RTC5_fixdisplay.hex" "HUB12_RTC5_fixdisplay.err" "HUB12_RTC5_fixdisplay.lst" "HUB12_RTC5_fixdisplay.cof"

