//************************************************************************************
//**  
//**  File name:     C:\Users\Acer-PC\Desktop\mimbala cueing\595test.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Sunday, January 13, 2019 15:47:33
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F883
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_7
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 20000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x20d2
#endif
#ifdef HI_TECH_C
__CONFIG(0x20d2);
#endif
#ifdef _BOOSTC
#pragma DATA 0x2008, 0x3eff
#endif
#ifdef HI_TECH_C
__CONFIG(0x3eff);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations


//Variable declarations
#define FCV_TRUE (1)
#define FCV_FALSE (0)
MX_BOOL FCV_DATA = (0);
MX_UINT8 FCV_CODE;

MX_UINT8 FCLV_LOOP1;


#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations



void main()
{
	//Initialization
	ansel = 0;
anselh = 0;


	//Interrupt initialization code
	option_reg = 0xC0;


	//dat
	//Output: 0 -> A0
	trisa = trisa & 0xFE;
	if ((0))
		porta = (porta & 0xFE) | 0x01;
	else
		porta = porta & 0xFE;

	//clk
	//Output: 0 -> A1
	trisa = trisa & 0xFD;
	if ((0))
		porta = (porta & 0xFD) | 0x02;
	else
		porta = porta & 0xFD;

	//reg
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Calculation
		//Calculation:
		//  code = 0b10101010
		FCV_CODE = 170;

		//Loop
		//Loop: Loop 8 times
		for (FCLV_LOOP1=0; FCLV_LOOP1<8; FCLV_LOOP1++)
		{

			//Calculation
			//Calculation:
			//  data = code AND 1
			FCV_DATA = FCV_CODE & 1;

			//dat
			//Output: data -> A0
			trisa = trisa & 0xFE;
			if ((FCV_DATA))
				porta = (porta & 0xFE) | 0x01;
			else
				porta = porta & 0xFE;

			//clk
			//Output: 1 -> A1
			trisa = trisa & 0xFD;
			if ((1))
				porta = (porta & 0xFD) | 0x02;
			else
				porta = porta & 0xFD;

			//clk
			//Output: 0 -> A1
			trisa = trisa & 0xFD;
			if ((0))
				porta = (porta & 0xFD) | 0x02;
			else
				porta = porta & 0xFD;

			//Calculation
			//Calculation:
			//  code = code >> 1
			FCV_CODE = FCV_CODE >> 1;


		}

		//reg
		//Output: 1 -> C3
		trisc = trisc & 0xF7;
		if ((1))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//Delay
		//Delay: 10 us
		delay_us(10);

		//reg
		//Output: 0 -> C3
		trisc = trisc & 0xF7;
		if ((0))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



