//************************************************************************************
//**  
//**  File name:     C:\Users\gerpe\OneDrive\GER-PER 2016\Documents\KennyNeutron\2020\FC\IC_TESTER.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Saturday, January 11, 2020 13:40:42
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F690
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_3
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portb
#define MX_SPI_1_MISO_TRIS trisb
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 7
#define MX_SPI_1_CLK_PORT portb
#define MX_SPI_1_CLK_TRIS trisb
#define MX_SPI_1_CLK_PIN 6
#define MX_SPI_1_SS_PORT portb
#define MX_SPI_1_SS_TRIS trisb
#define MX_UART_1
#define MX_UART_1_TX_PORT portb
#define MX_UART_1_TX_TRIS trisb
#define MX_UART_1_TX_PIN 7
#define MX_UART_1_RX_PORT portb
#define MX_UART_1_RX_TRIS trisb
#define MX_UART_1_RX_PIN 5
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portb
#define MX_I2C_1_SDA_TRIS trisb
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portb
#define MX_I2C_1_SCL_TRIS trisb
#define MX_I2C_1_SCL_PIN 6
#define MX_PWM
#define MX_PWM_CNT 1
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 5

//Functions
#define MX_CLK_SPEED 20000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x30d2
#endif
#ifdef HI_TECH_C
__CONFIG(0x30d2);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_INIT();


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_BOOL FCV_PB0 = (1);
MX_BOOL FCV_PB1 = (1);
MX_BOOL FCV_PB2 = (1);



#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_INIT()
{

	//O_628GND
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//O_628VCC
	//Output: 0 -> C1
	trisc = trisc & 0xFD;
	if ((0))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

	//O_690GND
	//Output: 0 -> C6
	trisc = trisc & 0xBF;
	if ((0))
		portc = (portc & 0xBF) | 0x40;
	else
		portc = portc & 0xBF;

	//O_690VCC
	//Output: 0 -> C4
	trisc = trisc & 0xEF;
	if ((0))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//O_COMGND
	//Output: 0 -> C3
	trisc = trisc & 0xF7;
	if ((0))
		portc = (portc & 0xF7) | 0x08;
	else
		portc = portc & 0xF7;

	//O_COMVCC
	//Output: 0 -> C7
	trisc = trisc & 0x7F;
	if ((0))
		portc = (portc & 0x7F) | 0x80;
	else
		portc = portc & 0x7F;

}



void main()
{
	//Initialization
	ansel = 0;
anselh = 0;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Call Macro
	//Call Macro: INIT()
	FCM_INIT();

	//Loop
	//Loop: While 1
	while (1)
	{

		//Input
		//Input: B4 -> PB0
		trisb = trisb | 0x10;
		FCV_PB0 = ((portb & 0x10) == 0x10);

		//Input
		//Input: B5 -> PB1
		trisb = trisb | 0x20;
		FCV_PB1 = ((portb & 0x20) == 0x20);

		//Input
		//Input: B6 -> PB2
		trisb = trisb | 0x40;
		FCV_PB2 = ((portb & 0x40) == 0x40);

		//Decision
		//Decision: PB0 = 0?
		if (FCV_PB0 == 0)
		{

			//Loop
			//Loop: While 1
			while (1)
			{

				//O_628VCC
				//Output: 1 -> C1
				trisc = trisc & 0xFD;
				if ((1))
					portc = (portc & 0xFD) | 0x02;
				else
					portc = portc & 0xFD;


			}

		} else {

			//O_628VCC
			//Output: 0 -> C1
			trisc = trisc & 0xFD;
			if ((0))
				portc = (portc & 0xFD) | 0x02;
			else
				portc = portc & 0xFD;

		}

		//Decision
		//Decision: PB1 = 0?
		if (FCV_PB1 == 0)
		{

			//Loop
			//Loop: While 1
			while (1)
			{

				//O_690VCC
				//Output: 1 -> C4
				trisc = trisc & 0xEF;
				if ((1))
					portc = (portc & 0xEF) | 0x10;
				else
					portc = portc & 0xEF;


			}

		} else {

			//O_690VCC
			//Output: 0 -> C4
			trisc = trisc & 0xEF;
			if ((0))
				portc = (portc & 0xEF) | 0x10;
			else
				portc = portc & 0xEF;

		}

		//Decision
		//Decision: PB2 = 0?
		if (FCV_PB2 == 0)
		{

			//O_COMVCC
			//Output: 1 -> C7
			trisc = trisc & 0x7F;
			if ((1))
				portc = (portc & 0x7F) | 0x80;
			else
				portc = portc & 0x7F;

			//Loop
			//Loop: While 1
			while (1)
			{

				//Output
				//Output: 0 -> B7
				trisb = trisb & 0x7F;
				if ((0))
					portb = (portb & 0x7F) | 0x80;
				else
					portb = portb & 0x7F;

				//Delay
				//Delay: 100 ms
				delay_ms(100);

				//Output
				//Output: 0 -> B7
				trisb = trisb & 0x7F;
				if ((0))
					portb = (portb & 0x7F) | 0x80;
				else
					portb = portb & 0x7F;

				//Delay
				//Delay: 100 ms
				delay_ms(100);


			}

		} else {

			//O_COMVCC
			//Output: 0 -> C7
			trisc = trisc & 0x7F;
			if ((0))
				portc = (portc & 0x7F) | 0x80;
			else
				portc = portc & 0x7F;

		}


	}

	//O_690VCC
	//Output: 1 -> C4
	trisc = trisc & 0xEF;
	if ((1))
		portc = (portc & 0xEF) | 0x10;
	else
		portc = portc & 0xEF;

	//O_COMVCC
	//Output: 1 -> C7
	trisc = trisc & 0x7F;
	if ((1))
		portc = (portc & 0x7F) | 0x80;
	else
		portc = portc & 0x7F;

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



