# MPLAB IDE generated this makefile for use with GNU make.
# Project: HUB6_RTC_GPU.mcp
# Date: Fri Nov 29 11:11:40 2019

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

20191125_RTCGPU.cof : 20191125_RTCGPU.o
	$(CC) /p18F4620 "20191125_RTCGPU.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"20191125_RTCGPU.cof" /M"20191125_RTCGPU.map" /W /x

20191125_RTCGPU.o : 20191125_RTCGPU.ASM ../../../../../../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P18F4620.INC
	$(AS) /q /p18F4620 "20191125_RTCGPU.ASM" /l"20191125_RTCGPU.lst" /e"20191125_RTCGPU.err" /d__DEBUG=1

clean : 
	$(CC) "20191125_RTCGPU.o" "20191125_RTCGPU.hex" "20191125_RTCGPU.err" "20191125_RTCGPU.lst" "20191125_RTCGPU.cof"

