//************************************************************************************
//**  
//**  File name:     D:\KennyNeutronsInnovations\MasterGio\final_program_FCF\ScoreBoard887.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.2.0.0
//**  Date:          Tuesday, March 12, 2019 09:56:24
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 2
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 1
//Defines for microcontroller
#define P16F887
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_7
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 20000000
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x20d2
#endif
#ifdef HI_TECH_C
__CONFIG(0x20d2);
#endif
#ifdef _BOOSTC
#pragma DATA 0x2008, 0x3fff
#endif
#ifdef HI_TECH_C
__CONFIG(0x3fff);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations
void FCM_data_bank();
void FCM_register();
void FCM_test_macro();


//Variable declarations
#define FCSZ_STRING_AWAY 3
#define FCSZ_END 2
#define FCSZ_STRING_TIME 4
#define FCSZ_STRING_FOPE 3
#define FCSZ_STRING_HOME 3
#define FCSZ_RCV 15
#define FCSZ_RCV 15
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_UINT8 FCV_DIGIT_FOPE = (0x0);
MX_UINT8 FCV_DIGIT_TIME;
MX_UINT32 FCV_STORED_HOME_SCORE = (0x0);
MX_UINT8 FCV_STORED_SEC = (0x0);
MX_UINT8 FCV_HOME_SCORE_ONES;
MX_BOOL FCV_DAT_SCORE;
MX_UINT8 FCV_STORED_MIN = (0x0);
MX_UINT8 FCV_PERIOD;
MX_UINT8 FCV_BITS_SCORE = (0x0);
MX_UINT8 FCV_AWAY_SCORE_TENS = (0x0);
MX_UINT8 FCV_STORED_HOME_FOUL = (0x0);
MX_UINT8 FCV_HOME_FOUL = (0x0);
MX_UINT8 FCV_MIN_ONES = (0x0);
MX_UINT8 FCV_STORED_PERIOD = (0x0);
MX_UINT8 FCV_RX;
MX_CHAR FCV_STRING_AWAY[FCSZ_STRING_AWAY] = ("");
MX_CHAR FCV_END[FCSZ_END] = ("");
MX_UINT32 FCV_AWAY_SCORE = (0x0);
MX_BOOL FCV_DAT_FOPE = (0);
MX_BOOL FCV_DAT_TIME = (0);
MX_UINT8 FCV_DIGIT = (0x0);
MX_CHAR FCV_STRING_TIME[FCSZ_STRING_TIME] = ("");
MX_UINT8 FCV_SEC_TENS;
MX_UINT8 FCV_AWAY_SCORE_ONES = (0x0);
MX_CHAR FCV_STRING_FOPE[FCSZ_STRING_FOPE] = ("");
MX_CHAR FCV_STRING_HOME[FCSZ_STRING_HOME] = ("");
MX_UINT32 FCV_HOME_SCORE;
MX_UINT8 FCV_DIGIT_SCORE = (0x0);
MX_UINT8 FCV_HOME_SCORE_TENS;
MX_UINT8 FCV_BITS_FOPE = (0x0);
MX_UINT8 FCV_BITS_TIME = (0x0);
MX_UINT8 FCV_SEC;
MX_UINT8 FCV_MIN = (0x0);
MX_UINT32 FCV_STORED_AWAY_SCORE = (0x0);
MX_UINT8 FCV_STORED_AWAY_FOUL = (0x0);
MX_UINT32 FCV_FOPE;
MX_UINT32 FCV_TIME = (0x0);
MX_UINT8 FCV_AWAY_FOUL = (0x0);
MX_UINT8 FCV_SEC_ONES;
MX_UINT8 FCV_MIN_TENS = (0x0);
MX_CHAR FCV_RCV[FCSZ_RCV] = ("");

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;
MX_UINT8 FCLV_LOOP5;
MX_UINT8 FCLV_LOOP6;
MX_UINT8 FCLV_LOOP7;
MX_UINT8 FCLV_LOOP8;



//RS232(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Uart Channel		(0-software / 1-4 hardware)
c = tx pin
d = tx port
e = rx pin
f = rx port
g = flow control		(0-Off / 1-On)
h = cts pin
i = cts port
j = rts pin
k = rts port
l = baud rate
m = data bits			(7/8/9) (7 only supported in software modes)
n = return type		(0-byte / 1-MX_UINT16)
o = echo enable		(0-Off / 1-On)
******************************/

//Definitions for RS232 UART slot allocation
#ifndef	MX_UART_REF1
	#define MX_UART_REF1
	#define RS232_1_MX_UART_UREF			1
	#define MX_UART_CHANNEL_1		1
	#define MX_UART_TX_PIN_1		0
	#define MX_UART_TX_PORT_1		porta
	#define MX_UART_TX_TRIS_1		trisa
	#define MX_UART_RX_PIN_1		0
	#define MX_UART_RX_PORT_1		porta
	#define MX_UART_RX_TRIS_1		trisa
	#define MX_UART_FLOWEN_1		0
	#define MX_UART_CTS_PIN_1		4
	#define MX_UART_CTS_PORT_1		portc
	#define MX_UART_CTS_TRIS_1		trisc
	#define MX_UART_RTS_PIN_1		0
	#define MX_UART_RTS_PORT_1		portc
	#define MX_UART_RTS_TRIS_1		trisc
	#define MX_UART_BAUD_1			38400
	#define MX_UART_DBITS_1			8
	#define MX_UART_RETURN_1		0
	#define MX_UART_ECHO_1			0
	#define MX_UART_INT_1			0
#else
 #ifndef	MX_UART_REF2
	#define MX_UART_REF2
	#define RS232_1_MX_UART_UREF			2
	#define MX_UART_CHANNEL_2		1
	#define MX_UART_TX_PIN_2		0
	#define MX_UART_TX_PORT_2		porta
	#define MX_UART_TX_TRIS_2		trisa
	#define MX_UART_RX_PIN_2		0
	#define MX_UART_RX_PORT_2		porta
	#define MX_UART_RX_TRIS_2		trisa
	#define MX_UART_FLOWEN_2		0
	#define MX_UART_CTS_PIN_2		4
	#define MX_UART_CTS_PORT_2		portc
	#define MX_UART_CTS_TRIS_2		trisc
	#define MX_UART_RTS_PIN_2		0
	#define MX_UART_RTS_PORT_2		portc
	#define MX_UART_RTS_TRIS_2		trisc
	#define MX_UART_BAUD_2			38400
	#define MX_UART_DBITS_2			8
	#define MX_UART_RETURN_2		0
	#define MX_UART_ECHO_2			0
	#define MX_UART_INT_2			0
 #else
  #ifndef	MX_UART_REF3
	#define MX_UART_REF3
	#define RS232_1_MX_UART_UREF			3
	#define MX_UART_CHANNEL_3		1
	#define MX_UART_TX_PIN_3		0
	#define MX_UART_TX_PORT_3		porta
	#define MX_UART_TX_TRIS_3		trisa
	#define MX_UART_RX_PIN_3		0
	#define MX_UART_RX_PORT_3		porta
	#define MX_UART_RX_TRIS_3		trisa
	#define MX_UART_FLOWEN_3		0
	#define MX_UART_CTS_PIN_3		4
	#define MX_UART_CTS_PORT_3		portc
	#define MX_UART_CTS_TRIS_3		trisc
	#define MX_UART_RTS_PIN_3		0
	#define MX_UART_RTS_PORT_3		portc
	#define MX_UART_RTS_TRIS_3		trisc
	#define MX_UART_BAUD_3			38400
	#define MX_UART_DBITS_3			8
	#define MX_UART_RETURN_3		0
	#define MX_UART_ECHO_3			0
	#define MX_UART_INT_3			0
  #else
   #ifndef	MX_UART_REF4
	#define MX_UART_REF4
	#define RS232_1_MX_UART_UREF			4
	#define MX_UART_CHANNEL_4		1
	#define MX_UART_TX_PIN_4		0
	#define MX_UART_TX_PORT_4		porta
	#define MX_UART_TX_TRIS_4		trisa
	#define MX_UART_RX_PIN_4		0
	#define MX_UART_RX_PORT_4		porta
	#define MX_UART_RX_TRIS_4		trisa
	#define MX_UART_FLOWEN_4		0
	#define MX_UART_CTS_PIN_4		4
	#define MX_UART_CTS_PORT_4		portc
	#define MX_UART_CTS_TRIS_4		trisc
	#define MX_UART_RTS_PIN_4		0
	#define MX_UART_RTS_PORT_4		portc
	#define MX_UART_RTS_TRIS_4		trisc
	#define MX_UART_BAUD_4			38400
	#define MX_UART_DBITS_4			8
	#define MX_UART_RETURN_4		0
	#define MX_UART_ECHO_4			0
	#define MX_UART_INT_4			0
   #endif
  #endif
 #endif
#endif

#define RS232_1_UART_Init		CAL_APPEND(FC_CAL_UART_Init_, RS232_1_MX_UART_UREF)
#define RS232_1_UART_Send		CAL_APPEND(FC_CAL_UART_Send_, RS232_1_MX_UART_UREF)
#define RS232_1_UART_Receive		CAL_APPEND(FC_CAL_UART_Receive_, RS232_1_MX_UART_UREF)
#define RS232_1_UART_Update_Baud CAL_APPEND(FC_CAL_UART_Update_Baud_, RS232_1_MX_UART_UREF)

extern void RS232_1_UART_Init();
extern void RS232_1_UART_Send(MX_UINT16 nChar);
extern MX_SINT16 RS232_1_UART_Receive(MX_UINT8 nTimeout);
extern void RS232_1_UART_Update_Baud(MX_UINT8 newbaud);




//RS232(0): //Macro function declarations

void FCD_RS2320_SendRS232Char(MX_SINT16 nChar);
void FCD_RS2320_SendRS232String(MX_STRING String, MX_UINT8 MSZ_String);
MX_SINT16 FCD_RS2320_ReceiveRS232Char(MX_UINT8 nTimeout);
void FCD_RS2320_ReceiveRS232String(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE, MX_UINT8 nTimeout, MX_UINT8 NumBytes);
void FCD_RS2320_ChangeHWBaud(MX_UINT8 newbaud);



//RS232(0): //Macro implementations


void FCD_RS2320_SendRS232Char(MX_SINT16 nChar)
{
	
		RS232_1_UART_Send ( nChar);

}

void FCD_RS2320_SendRS232String(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx;
		for(idx = 0; idx < MSZ_String; idx++)
		{
			if (String[idx] == 0)
				break;
			else RS232_1_UART_Send ( String[idx] );
		}

}

MX_SINT16 FCD_RS2320_ReceiveRS232Char(MX_UINT8 nTimeout)
{
	
		return ( RS232_1_UART_Receive ( nTimeout) );

}

void FCD_RS2320_ReceiveRS232String(MX_CHAR* FCR_RETVAL, MX_UINT8 FCR_RETVAL_SIZE, MX_UINT8 nTimeout, MX_UINT8 NumBytes)
{
	
		MX_UINT8 idx;
		MX_SINT16 RS232_TO = 255;
		MX_SINT16 in;

		if ( 0 != 0 )
			RS232_TO = 256;

		if (NumBytes > FCR_RETVAL_SIZE)
			NumBytes = FCR_RETVAL_SIZE;

		for (idx = 0; idx < NumBytes; idx++)
		{
			in = RS232_1_UART_Receive ( nTimeout);
			if(in < RS232_TO)
				FCR_RETVAL[idx] = in & 0xFF;
			else
				break;
		}

		if (idx < FCR_RETVAL_SIZE)
			FCR_RETVAL[idx] = 0;

}

void FCD_RS2320_ChangeHWBaud(MX_UINT8 newbaud)
{
	
		RS232_1_UART_Update_Baud (newbaud);

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations


void FCM_data_bank()
{

	//Switch
	//Switch: digit_time?
	switch (FCV_DIGIT_TIME)
	{
		case 1:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b00000110
			FCV_BITS_TIME = 6;

			break;
		}
		case 2:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b01011011
			FCV_BITS_TIME = 91;

			break;
		}
		case 3:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b01001111
			FCV_BITS_TIME = 79;

			break;
		}
		case 4:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b01100110
			FCV_BITS_TIME = 102;

			break;
		}
		case 5:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b01101101
			FCV_BITS_TIME = 109;

			break;
		}
		case 6:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b01111101
			FCV_BITS_TIME = 125;

			break;
		}
		case 7:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b00000111
			FCV_BITS_TIME = 7;

			break;
		}
		case 8:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b01111111
			FCV_BITS_TIME = 127;

			break;
		}
		case 9:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b01101111
			FCV_BITS_TIME = 111;

			break;
		}
		case 0:
		{
			//Calculation
			//Calculation:
			//  bits_time = 0b00111111
			FCV_BITS_TIME = 63;

			break;
		}
		// default:

	}

	//Switch
	//Switch: digit_fope?
	switch (FCV_DIGIT_FOPE)
	{
		case 1:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b00000110
			FCV_BITS_FOPE = 6;

			break;
		}
		case 2:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b01011011
			FCV_BITS_FOPE = 91;

			break;
		}
		case 3:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b01001111
			FCV_BITS_FOPE = 79;

			break;
		}
		case 4:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b01100110
			FCV_BITS_FOPE = 102;

			break;
		}
		case 5:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b01101101
			FCV_BITS_FOPE = 109;

			break;
		}
		case 6:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b01111101
			FCV_BITS_FOPE = 125;

			break;
		}
		case 7:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b00000111
			FCV_BITS_FOPE = 7;

			break;
		}
		case 8:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b01111111
			FCV_BITS_FOPE = 127;

			break;
		}
		case 9:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b01101111
			FCV_BITS_FOPE = 111;

			break;
		}
		case 0:
		{
			//Calculation
			//Calculation:
			//  bits_fope = 0b00111111
			FCV_BITS_FOPE = 63;

			break;
		}
		// default:

	}

	//Switch
	//Switch: digit_score?
	switch (FCV_DIGIT_SCORE)
	{
		case 1:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b00000110
			FCV_BITS_SCORE = 6;

			break;
		}
		case 2:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b01011011
			FCV_BITS_SCORE = 91;

			break;
		}
		case 3:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b01001111
			FCV_BITS_SCORE = 79;

			break;
		}
		case 4:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b01100110
			FCV_BITS_SCORE = 102;

			break;
		}
		case 5:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b01101101
			FCV_BITS_SCORE = 109;

			break;
		}
		case 6:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b01111101
			FCV_BITS_SCORE = 125;

			break;
		}
		case 7:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b00000111
			FCV_BITS_SCORE = 7;

			break;
		}
		case 8:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b01111111
			FCV_BITS_SCORE = 127;

			break;
		}
		case 9:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b01101111
			FCV_BITS_SCORE = 111;

			break;
		}
		case 0:
		{
			//Calculation
			//Calculation:
			//  bits_score = 0b00111111
			FCV_BITS_SCORE = 63;

			break;
		}
		// default:

	}

}


void FCM_register()
{

	//Calculation
	//Calculation:
	//  digit_time = min_tens
	//  digit_fope = 8
	//  digit_score = home_score_tens
	FCV_DIGIT_TIME = FCV_MIN_TENS;
	FCV_DIGIT_FOPE = 8;
	FCV_DIGIT_SCORE = FCV_HOME_SCORE_TENS;

	//Call Macro
	//Call Macro: data_bank()
	FCM_data_bank();

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP1=0; FCLV_LOOP1<8; FCLV_LOOP1++)
	{

		//clk
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  dat_time = bits_time AND 1
		//  dat_fope = bits_fope AND 1
		//  dat_score = bits_score AND 1
		FCV_DAT_TIME = FCV_BITS_TIME & 1;
		FCV_DAT_FOPE = FCV_BITS_FOPE & 1;
		FCV_DAT_SCORE = FCV_BITS_SCORE & 1;

		//data_time
		//Output: dat_time -> C2
		trisc = trisc & 0xFB;
		if ((FCV_DAT_TIME))
			portc = (portc & 0xFB) | 0x04;
		else
			portc = portc & 0xFB;

		//data_fope
		//Output: dat_fope -> C4
		trisc = trisc & 0xEF;
		if ((FCV_DAT_FOPE))
			portc = (portc & 0xEF) | 0x10;
		else
			portc = portc & 0xEF;

		//data_score
		//Output: dat_score -> C3
		trisc = trisc & 0xF7;
		if ((FCV_DAT_SCORE))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//clk
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  bits_time = bits_time >> 1
		//  bits_fope = bits_fope >> 1
		//  bits_score = bits_score >> 1
		FCV_BITS_TIME = FCV_BITS_TIME >> 1;
		FCV_BITS_FOPE = FCV_BITS_FOPE >> 1;
		FCV_BITS_SCORE = FCV_BITS_SCORE >> 1;


	}

	//Calculation
	//Calculation:
	//  digit_time = min_ones
	//  digit_fope = period
	//  digit_score = home_score_ones
	FCV_DIGIT_TIME = FCV_MIN_ONES;
	FCV_DIGIT_FOPE = FCV_PERIOD;
	FCV_DIGIT_SCORE = FCV_HOME_SCORE_ONES;

	//Call Macro
	//Call Macro: data_bank()
	FCM_data_bank();

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP2=0; FCLV_LOOP2<8; FCLV_LOOP2++)
	{

		//clk
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  dat_time = bits_time AND 1
		//  dat_fope = bits_fope AND 1
		//  dat_score = bits_score AND 1
		FCV_DAT_TIME = FCV_BITS_TIME & 1;
		FCV_DAT_FOPE = FCV_BITS_FOPE & 1;
		FCV_DAT_SCORE = FCV_BITS_SCORE & 1;

		//data_time
		//Output: dat_time -> C2
		trisc = trisc & 0xFB;
		if ((FCV_DAT_TIME))
			portc = (portc & 0xFB) | 0x04;
		else
			portc = portc & 0xFB;

		//data_fope
		//Output: dat_fope -> C4
		trisc = trisc & 0xEF;
		if ((FCV_DAT_FOPE))
			portc = (portc & 0xEF) | 0x10;
		else
			portc = portc & 0xEF;

		//data_score
		//Output: dat_score -> C3
		trisc = trisc & 0xF7;
		if ((FCV_DAT_SCORE))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//clk
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  bits_time = bits_time >> 1
		//  bits_fope = bits_fope >> 1
		//  bits_score = bits_score >> 1
		FCV_BITS_TIME = FCV_BITS_TIME >> 1;
		FCV_BITS_FOPE = FCV_BITS_FOPE >> 1;
		FCV_BITS_SCORE = FCV_BITS_SCORE >> 1;


	}

	//Calculation
	//Calculation:
	//  digit_time = sec_tens
	//  digit_fope = home_foul
	//  digit_score = away_score_tens
	FCV_DIGIT_TIME = FCV_SEC_TENS;
	FCV_DIGIT_FOPE = FCV_HOME_FOUL;
	FCV_DIGIT_SCORE = FCV_AWAY_SCORE_TENS;

	//Call Macro
	//Call Macro: data_bank()
	FCM_data_bank();

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP3=0; FCLV_LOOP3<8; FCLV_LOOP3++)
	{

		//clk
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  dat_time = bits_time AND 1
		//  dat_fope = bits_fope AND 1
		//  dat_score = bits_score AND 1
		FCV_DAT_TIME = FCV_BITS_TIME & 1;
		FCV_DAT_FOPE = FCV_BITS_FOPE & 1;
		FCV_DAT_SCORE = FCV_BITS_SCORE & 1;

		//data_time
		//Output: dat_time -> C2
		trisc = trisc & 0xFB;
		if ((FCV_DAT_TIME))
			portc = (portc & 0xFB) | 0x04;
		else
			portc = portc & 0xFB;

		//data_fope
		//Output: dat_fope -> C4
		trisc = trisc & 0xEF;
		if ((FCV_DAT_FOPE))
			portc = (portc & 0xEF) | 0x10;
		else
			portc = portc & 0xEF;

		//data_score
		//Output: dat_score -> C3
		trisc = trisc & 0xF7;
		if ((FCV_DAT_SCORE))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//clk
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  bits_time = bits_time >> 1
		//  bits_fope = bits_fope >> 1
		//  bits_score = bits_score >> 1
		FCV_BITS_TIME = FCV_BITS_TIME >> 1;
		FCV_BITS_FOPE = FCV_BITS_FOPE >> 1;
		FCV_BITS_SCORE = FCV_BITS_SCORE >> 1;


	}

	//Calculation
	//Calculation:
	//  digit_time = sec_ones
	//  digit_fope = away_foul
	//  digit_score = away_score_ones
	FCV_DIGIT_TIME = FCV_SEC_ONES;
	FCV_DIGIT_FOPE = FCV_AWAY_FOUL;
	FCV_DIGIT_SCORE = FCV_AWAY_SCORE_ONES;

	//Call Macro
	//Call Macro: data_bank()
	FCM_data_bank();

	//Calculation
	//Calculation:
	//  bits_time = bits_time + 0b10000000
	FCV_BITS_TIME = FCV_BITS_TIME + 128;

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP4=0; FCLV_LOOP4<8; FCLV_LOOP4++)
	{

		//clk
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  dat_time = bits_time AND 1
		//  dat_fope = bits_fope AND 1
		//  dat_score = bits_score AND 1
		FCV_DAT_TIME = FCV_BITS_TIME & 1;
		FCV_DAT_FOPE = FCV_BITS_FOPE & 1;
		FCV_DAT_SCORE = FCV_BITS_SCORE & 1;

		//data_time
		//Output: dat_time -> C2
		trisc = trisc & 0xFB;
		if ((FCV_DAT_TIME))
			portc = (portc & 0xFB) | 0x04;
		else
			portc = portc & 0xFB;

		//data_fope
		//Output: dat_fope -> C4
		trisc = trisc & 0xEF;
		if ((FCV_DAT_FOPE))
			portc = (portc & 0xEF) | 0x10;
		else
			portc = portc & 0xEF;

		//data_score
		//Output: dat_score -> C3
		trisc = trisc & 0xF7;
		if ((FCV_DAT_SCORE))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//clk
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  bits_time = bits_time >> 1
		//  bits_fope = bits_fope >> 1
		//  bits_score = bits_score >> 1
		FCV_BITS_TIME = FCV_BITS_TIME >> 1;
		FCV_BITS_FOPE = FCV_BITS_FOPE >> 1;
		FCV_BITS_SCORE = FCV_BITS_SCORE >> 1;


	}

	//reg
	//Output: 1 -> C1
	trisc = trisc & 0xFD;
	if ((1))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

	//reg
	//Output: 0 -> C1
	trisc = trisc & 0xFD;
	if ((0))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

}


void FCM_test_macro()
{

	//Calculation
	//Calculation:
	//  digit_score = home_score_tens
	FCV_DIGIT_SCORE = FCV_HOME_SCORE_TENS;

	//Call Macro
	//Call Macro: data_bank()
	FCM_data_bank();

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP5=0; FCLV_LOOP5<8; FCLV_LOOP5++)
	{

		//clk
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  dat_time = bits_time AND 1
		//  dat_fope = bits_fope AND 1
		//  dat_score = bits_score AND 1
		FCV_DAT_TIME = FCV_BITS_TIME & 1;
		FCV_DAT_FOPE = FCV_BITS_FOPE & 1;
		FCV_DAT_SCORE = FCV_BITS_SCORE & 1;

		//data_score
		//Output: dat_score -> C3
		trisc = trisc & 0xF7;
		if ((FCV_DAT_SCORE))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//clk
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  bits_time = bits_time >> 1
		//  bits_fope = bits_fope >> 1
		//  bits_score = bits_score >> 1
		FCV_BITS_TIME = FCV_BITS_TIME >> 1;
		FCV_BITS_FOPE = FCV_BITS_FOPE >> 1;
		FCV_BITS_SCORE = FCV_BITS_SCORE >> 1;


	}

	//Calculation
	//Calculation:
	//  digit_score = home_score_ones
	FCV_DIGIT_SCORE = FCV_HOME_SCORE_ONES;

	//Call Macro
	//Call Macro: data_bank()
	FCM_data_bank();

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP6=0; FCLV_LOOP6<8; FCLV_LOOP6++)
	{

		//clk
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  dat_time = bits_time AND 1
		//  dat_fope = bits_fope AND 1
		//  dat_score = bits_score AND 1
		FCV_DAT_TIME = FCV_BITS_TIME & 1;
		FCV_DAT_FOPE = FCV_BITS_FOPE & 1;
		FCV_DAT_SCORE = FCV_BITS_SCORE & 1;

		//data_score
		//Output: dat_score -> C3
		trisc = trisc & 0xF7;
		if ((FCV_DAT_SCORE))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//clk
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  bits_time = bits_time >> 1
		//  bits_fope = bits_fope >> 1
		//  bits_score = bits_score >> 1
		FCV_BITS_TIME = FCV_BITS_TIME >> 1;
		FCV_BITS_FOPE = FCV_BITS_FOPE >> 1;
		FCV_BITS_SCORE = FCV_BITS_SCORE >> 1;


	}

	//Calculation
	//Calculation:
	//  digit_score = away_score_tens
	FCV_DIGIT_SCORE = FCV_AWAY_SCORE_TENS;

	//Call Macro
	//Call Macro: data_bank()
	FCM_data_bank();

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP7=0; FCLV_LOOP7<8; FCLV_LOOP7++)
	{

		//clk
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  dat_time = bits_time AND 1
		//  dat_fope = bits_fope AND 1
		//  dat_score = bits_score AND 1
		FCV_DAT_TIME = FCV_BITS_TIME & 1;
		FCV_DAT_FOPE = FCV_BITS_FOPE & 1;
		FCV_DAT_SCORE = FCV_BITS_SCORE & 1;

		//data_score
		//Output: dat_score -> C3
		trisc = trisc & 0xF7;
		if ((FCV_DAT_SCORE))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//clk
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  bits_time = bits_time >> 1
		//  bits_fope = bits_fope >> 1
		//  bits_score = bits_score >> 1
		FCV_BITS_TIME = FCV_BITS_TIME >> 1;
		FCV_BITS_FOPE = FCV_BITS_FOPE >> 1;
		FCV_BITS_SCORE = FCV_BITS_SCORE >> 1;


	}

	//Calculation
	//Calculation:
	//  digit_score = away_score_ones
	FCV_DIGIT_SCORE = FCV_AWAY_SCORE_ONES;

	//Call Macro
	//Call Macro: data_bank()
	FCM_data_bank();

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//Loop
	//Loop: Loop 8 times
	for (FCLV_LOOP8=0; FCLV_LOOP8<8; FCLV_LOOP8++)
	{

		//clk
		//Output: 0 -> C0
		trisc = trisc & 0xFE;
		if ((0))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  dat_time = bits_time AND 1
		//  dat_fope = bits_fope AND 1
		//  dat_score = bits_score AND 1
		FCV_DAT_TIME = FCV_BITS_TIME & 1;
		FCV_DAT_FOPE = FCV_BITS_FOPE & 1;
		FCV_DAT_SCORE = FCV_BITS_SCORE & 1;

		//data_score
		//Output: dat_score -> C3
		trisc = trisc & 0xF7;
		if ((FCV_DAT_SCORE))
			portc = (portc & 0xF7) | 0x08;
		else
			portc = portc & 0xF7;

		//clk
		//Output: 1 -> C0
		trisc = trisc & 0xFE;
		if ((1))
			portc = (portc & 0xFE) | 0x01;
		else
			portc = portc & 0xFE;

		//Calculation
		//Calculation:
		//  bits_time = bits_time >> 1
		//  bits_fope = bits_fope >> 1
		//  bits_score = bits_score >> 1
		FCV_BITS_TIME = FCV_BITS_TIME >> 1;
		FCV_BITS_FOPE = FCV_BITS_FOPE >> 1;
		FCV_BITS_SCORE = FCV_BITS_SCORE >> 1;


	}

	//reg
	//Output: 1 -> C1
	trisc = trisc & 0xFD;
	if ((1))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

	//reg
	//Output: 0 -> C1
	trisc = trisc & 0xFD;
	if ((0))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

}



void main()
{
	//Initialization
	ansel = 0;
anselh = 0;

	
		RS232_1_UART_Init( );		//Call initialise function


	//Interrupt initialization code
	option_reg = 0xC0;


	//Output
	//Output: 0 -> A1
	trisa = trisa & 0xFD;
	if ((0))
		porta = (porta & 0xFD) | 0x02;
	else
		porta = porta & 0xFD;

	//clk
	//Output: 0 -> C0
	trisc = trisc & 0xFE;
	if ((0))
		portc = (portc & 0xFE) | 0x01;
	else
		portc = portc & 0xFE;

	//reg
	//Output: 0 -> C1
	trisc = trisc & 0xFD;
	if ((0))
		portc = (portc & 0xFD) | 0x02;
	else
		portc = portc & 0xFD;

	//Loop
	//Loop: While 1
	while (1)
	{

		//Connection Point
		//Connection Point: [A]: A
FCC_Main_A:
;

		//Call Component Macro
		//Call Component Macro: rx=ReceiveRS232Char(1)
		FCV_RX = FCD_RS2320_ReceiveRS232Char(1);

		//Decision
		//Decision: rx = 'E'?
		if (FCV_RX == 'E')
		{

			//Output
			//Output: 1 -> A1
			trisa = trisa & 0xFD;
			if ((1))
				porta = (porta & 0xFD) | 0x02;
			else
				porta = porta & 0xFD;

		// } else {

		}

		//Decision
		//Decision: rx = 'F'?
		if (FCV_RX == 'F')
		{

			//Output
			//Output: 0 -> A1
			trisa = trisa & 0xFD;
			if ((0))
				porta = (porta & 0xFD) | 0x02;
			else
				porta = porta & 0xFD;

		// } else {

		}

		//Decision
		//Decision: rx = 'A'?
		if (FCV_RX == 'A')
		{

			//Call Component Macro
			//Call Component Macro: rx=ReceiveRS232Char(1)
			FCV_RX = FCD_RS2320_ReceiveRS232Char(1);

			//Decision
			//Decision: rx = 'B'?
			if (FCV_RX == 'B')
			{

				//Call Component Macro
				//Call Component Macro: rcv=ReceiveRS232String(1, 15)
				FCD_RS2320_ReceiveRS232String(FCV_RCV,FCSZ_RCV, 1, 15);

				//Decision
				//Decision: home_score = 10?
				if (FCV_HOME_SCORE == 10)
				{

				// } else {

				}

				//Calculation
				//Calculation:
				//  string_time = Right$ (rcv,15)
				//  time = StringToInt$ (string_time)
				//  min = time / 100
				//  sec = time % 100
				//  string_fope = Right$ (rcv,11)
				//  fope = StringToInt$ (string_fope)
				//  home_foul = fope / 100
				//  away_foul = fope % 10
				//  period = (fope % 100) / 10
				//  string_home = Right$ (rcv,8)
				//  home_score = StringToInt$ (string_home)
				//  string_away = Right$ (rcv,5)
				//  away_score = StringToInt$ (string_away)
				//  end = Right$ (rcv,2)
				FCI_RIGHTSTRING(FCV_RCV, FCSZ_RCV, 15, FCV_STRING_TIME,FCSZ_STRING_TIME);
				FCV_TIME = FCI_STRING_TO_INT(FCV_STRING_TIME, FCSZ_STRING_TIME);
				FCV_MIN = FCV_TIME / 100;
				FCV_SEC = FCV_TIME % 100;
				FCI_RIGHTSTRING(FCV_RCV, FCSZ_RCV, 11, FCV_STRING_FOPE,FCSZ_STRING_FOPE);
				FCV_FOPE = FCI_STRING_TO_INT(FCV_STRING_FOPE, FCSZ_STRING_FOPE);
				FCV_HOME_FOUL = FCV_FOPE / 100;
				FCV_AWAY_FOUL = FCV_FOPE % 10;
				FCV_PERIOD = (FCV_FOPE % 100) / 10;
				FCI_RIGHTSTRING(FCV_RCV, FCSZ_RCV, 8, FCV_STRING_HOME,FCSZ_STRING_HOME);
				FCV_HOME_SCORE = FCI_STRING_TO_INT(FCV_STRING_HOME, FCSZ_STRING_HOME);
				FCI_RIGHTSTRING(FCV_RCV, FCSZ_RCV, 5, FCV_STRING_AWAY,FCSZ_STRING_AWAY);
				FCV_AWAY_SCORE = FCI_STRING_TO_INT(FCV_STRING_AWAY, FCSZ_STRING_AWAY);
				FCI_RIGHTSTRING(FCV_RCV, FCSZ_RCV, 2, FCV_END,FCSZ_END);

				//Decision
				//Decision: end[0] = 'C' && end[1] = 'D'?
				if (FCV_END[0] == 'C' && FCV_END[1] == 'D')
				{

					//Calculation
					//Calculation:
					//  stored_away_score = away_score
					//  stored_home_score = home_score
					//  stored_home_foul = home_foul
					//  stored_away_foul = away_foul
					//  stored_period = period
					//  stored_min = min
					//  stored_sec = sec
					FCV_STORED_AWAY_SCORE = FCV_AWAY_SCORE;
					FCV_STORED_HOME_SCORE = FCV_HOME_SCORE;
					FCV_STORED_HOME_FOUL = FCV_HOME_FOUL;
					FCV_STORED_AWAY_FOUL = FCV_AWAY_FOUL;
					FCV_STORED_PERIOD = FCV_PERIOD;
					FCV_STORED_MIN = FCV_MIN;
					FCV_STORED_SEC = FCV_SEC;

				} else {

					//Calculation
					//Calculation:
					//  away_score = stored_away_score
					//  home_score = stored_home_score
					//  home_foul = stored_home_foul
					//  away_foul = stored_away_foul
					//  period = stored_period
					//  min = stored_min
					//  sec = stored_sec
					FCV_AWAY_SCORE = FCV_STORED_AWAY_SCORE;
					FCV_HOME_SCORE = FCV_STORED_HOME_SCORE;
					FCV_HOME_FOUL = FCV_STORED_HOME_FOUL;
					FCV_AWAY_FOUL = FCV_STORED_AWAY_FOUL;
					FCV_PERIOD = FCV_STORED_PERIOD;
					FCV_MIN = FCV_STORED_MIN;
					FCV_SEC = FCV_STORED_SEC;

					//Goto Connection Point
					//Goto Connection Point: [A]: A
					goto FCC_Main_A;

				}

			// } else {

			}

		// } else {

		}

		//Calculation
		//Calculation:
		//  home_score_tens = home_score / 10
		//  home_score_ones = home_score % 10
		//  away_score_tens = away_score / 10
		//  away_score_ones = away_score % 10
		//  min_tens = min / 10
		//  min_ones = min % 10
		//  sec_tens = sec / 10
		//  sec_ones = sec % 10
		FCV_HOME_SCORE_TENS = FCV_HOME_SCORE / 10;
		FCV_HOME_SCORE_ONES = FCV_HOME_SCORE % 10;
		FCV_AWAY_SCORE_TENS = FCV_AWAY_SCORE / 10;
		FCV_AWAY_SCORE_ONES = FCV_AWAY_SCORE % 10;
		FCV_MIN_TENS = FCV_MIN / 10;
		FCV_MIN_ONES = FCV_MIN % 10;
		FCV_SEC_TENS = FCV_SEC / 10;
		FCV_SEC_ONES = FCV_SEC % 10;

		//Call Macro
		//Call Macro: register()
		FCM_register();


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



